### ISSUE TITLE
$FERMI_DIR not expanded in self.logLike.readXml call

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#10]
I'm getting this error from all the example notebooks:
https://gist.github.com/cdeil/844d88982b705a92a09e

```
RuntimeError: File not found: $FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_v06.txt
```
The `$FERMI_DIR` environment variable is set and `$FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_v06.txt` exists.

I don't understand why it's not expanded for me ... it seems to work for everyone else?

**Comment by woodmd** [comment]
This was a bug.  It should be fixed in the latest commit.  Could you try running the notebook again?

**Comment by cdeil** [comment]
This issue is resolved, `ic443.ipynb` now works for me.
:smile:
