### ISSUE TITLE
Improve Parameter Handling in ROIModel

### ISSUE THREAD

**Issue by woodmd** [fermiPy/fermipy#103]
Parameter values and errors are currently duplicated in two different data structures within a Model object which necessitates synchronizing values when loading from a file or updating after a fit. This could be simplified by having a single `ParameterSet` data structure which would own a list of `Parameter`objects that would have properties like `value`, `error`, `free` etc.

**Comment by eacharles** [comment]
This would be better, but at this point it is beyond the scope of what is feasible, as it would involve a lot of resturcturing of code.
