### ISSUE TITLE
fermipy installation problem on Mac

### ISSUE THREAD

**Issue by suvenduat** [fermiPy/fermipy#107]
Hi, I am trying to install fermipy on a mac OS X 10.11.2. I have a ScienceTools-v10r0p5 installed on this computer. If I run "python setup.py install" command I found the following error:
Processing healpy-1.10.1.tar.gz
Writing /tmp/easy_install-UJBYV3/healpy-1.10.1/setup.cfg
Running healpy-1.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UJBYV3/healpy-1.10.1/egg-dist-tmp-BW0jzM
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'cython_directives'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    all=[],
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
........
.......
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-UJBYV3/healpy-1.10.1/setup.py", line 353, in finalize_options
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

I also tried using pip but there I have probelm in healpy installation with the error:
configure: error: could not find the cfitsio library
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
.......
 raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/bin/sh', '/private/tmp/pip-build-gziv16/healpy/healpixsubmodule/src/cxx/autotools/configure', '--prefix=/private/tmp/pip-build-gziv16/healpy/build/temp.macosx-10.6-intel-2.7', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 1

Don't know how to solve this installation problem. Please let me know if you have any solution
Thanks.

**Comment by woodmd** [comment]
It looks like you are using your system python rather than the one that comes installed with the STs.  Are you following the [pip installation](http://fermipy.readthedocs.io/en/latest/install.html#installing-with-pip) instructions?  What do you see when you run `which python`?

**Comment by suvenduat** [comment]
I am using system python. The which python gives /Library/Frameworks/Python.framework/Versions/2.7/bin/python
In fact, with this python, I am able to run the likelihood python tutorial given in scitools
http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html
But not able to install fermipy. so, what do you suggest?

**Comment by woodmd** [comment]
Fermipy is only compatible with the python installation that comes with the STs.  Using your system python with the Fermi STs is not recommended.  Alternatively you could try following the [docker installation](http://fermipy.readthedocs.io/en/latest/install.html#installing-with-docker) instructions.

**Comment by suvenduat** [comment]
Can't find that python and ipython executable! How to use that python only for Fermipy?

**Comment by woodmd** [comment]
If you source the ST setup script it should but the ST python installation into your path.  I recommend putting something like the following in `.profile`:
```
FERMI_DIR=/path/to/ST/installation/x86_64-apple-darwin14.4.0/
```
Then to initialize your environment you can do:
```
source $FERMI_DIR/fermi-init.sh
```

**Comment by suvenduat** [comment]
I already have it. I am able to run fermi data reduction and python LATAnalysisScripts. But if I run "pip install fermipy", I got a problem in the step of healpy installation with a message "Running setup.py install for healpy ... error....."

**Comment by woodmd** [comment]
It sounds like a build error with the healpy package.  Are you sure that you're using pip from the STs?  The path for both pip and python should contain the ST bin directory.

**Comment by suvenduat** [comment]
Strangely, I don't have pip in ST bin directory but I have python there!

**Comment by woodmd** [comment]
The STs do not come with pip preinstalled.  You can bootstrap an installation of pip with the following command:
```
curl https://bootstrap.pypa.io/get-pip.py | python -
```
