### ISSUE TITLE
docker login?

### ISSUE THREAD

**Issue by grburgess** [fermiPy/fermipy#108]
I'm being presented with a login screen to Jupyter when I run the docker per the instructions. Have I missed a password somewhere?

**Comment by woodmd** [comment]
No password should be necessary.  Could you provide a screenshot?  What kind of machine are you running on?

**Comment by grburgess** [comment]
I'm running macOS 10.12.2

The login looks a little funny because I have a css style in jupyter:



![screen shot 2017-01-04 at 10 47 31 pm](https://cloud.githubusercontent.com/assets/6764007/21660513/fc8f9972-d2cf-11e6-8509-af5eb146b394.png)
![screen shot 2017-01-04 at 10 46 31 pm](https://cloud.githubusercontent.com/assets/6764007/21660517/01de54cc-d2d0-11e6-828e-e47981d826b3.png)
![screen shot 2017-01-04 at 10 49 23 pm](https://cloud.githubusercontent.com/assets/6764007/21660534/130f3c16-d2d0-11e6-8089-5e7ae46a9beb.png)

**Comment by woodmd** [comment]
That's very odd.  I don't see this on El Capitan but I'm running a slightly older version of the docker image (i have the image configured to auto-update whenever changes are pushed to the fermipy repo). It looks like this is something that was changed very recently in the behavior of jupyter notebook:
http://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/
Unfortunately they don't provide any instructions on how to disable token authentication.

**Comment by grburgess** [comment]
No worries. Thanks!
