### ISSUE TITLE
Changing model while running the analysis

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#112]
Hi Matthew,

Is it possible to change the spectrum type of the source of interest while running the analysis? Say, e.g., a source is defined as a log parabola model in 3FGL and to generate its light curve, I want to use a simpler model (power law) since the time binning would be small. This will also help in determining the best spectral shape during a particular flaring state of the blazar. If we can test which model provides the best fit, a power law, a log parabola, or exponential cut-off, it will help in extracting science.

Thanks.

**Comment by woodmd** [comment]
You can have a look at the `GTAnalysis.set_source_spectrum` method.  This will let you change the spectral type of a source at runtime.  I believe Mattia has been using this successfully to do these kinds of spectral model comparisons.
