### ISSUE TITLE
error in residmap.py related to numpy version >= 1.12.0

### ISSUE THREAD

**Issue by ldivenere** [fermiPy/fermipy#113]
Hi,
I've recently upgraded to fermipy version v0.13 (from v0.11) and I got these errors when producing residual maps.

Error 1 :

Traceback (most recent call last):
  File "fermipy_analysis_pipeline_disk.py", line 32, in <module>
    gta = fit_and_save(gta,outname,my_source)
  File "/afs/slac/g/glast/users/divenere/scripts/fermipy_utils.py", line 94, in fit_and_save
    m0 = gta.residmap(outname,model=test_src_model)
  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 165, in residmap
    maps = self._make_residual_map(prefix, **config)
  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 251, in _make_residual_map
    ccs = convolve_map(cc, sm[i], cpix, imin=imin, imax=imax)
  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 70, in convolve_map
    mx = ks[cpix[0], :] > ks[cpix[0], cpix[1]] * threshold
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

---------------------------------------------
Error 2 :

  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 165, in residmap
    maps = self._make_residual_map(prefix, **config)
  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 251, in _make_residual_map
    ccs = convolve_map(cc, sm[i], cpix, imin=imin, imax=imax)
  File "/u/ki/divenere/.local/lib/python2.7/site-packages/fermipy/residmap.py", line 85, in convolve_map
    ks = ks[sx, sy]
TypeError: slice indices must be integers or None or have an __ index __ method

This is related to a new version of numpy (>=1.12.0, released a few days ago), which was automatically upgraded by 'pip' when upgrading fermipy. This now raises an error when using non integer indices for numpy arrays, while in previous versions a DeprecationWarning was raised. 
(see https://docs.scipy.org/doc/numpy/release.html#deprecationwarning-to-error)

I solved the problems by modifying the file residmap.py:
- line 202:
`        cpix = np.array([xpix, ypix]).astype(int)`
- lines 73-74:
`        nx = int(max(3, np.round(np.sum(mx) / 2.)))`
`        ny = int(max(3, np.round(np.sum(my) / 2.)))`

Probably some other code lines will raise similar errors with this numpy version.

Leonardo

**Comment by woodmd** [comment]
Thanks for pointing these out.  I'll start working on a patch release to fix these errors.

However I'm curious why you're installing numpy yourself.  When you upgrade fermipy I recommend always using the `--no-deps` option, e.g.
```
pip install fermipy --upgrade --no-deps
```
This avoids unnecessarily upgrading fermipy dependencies (numpy, scipy, etc.) which are installed in GLAST_EXT.

**Comment by ldivenere** [comment]
You're right, I forgot to add the `--no-deps` option and upgraded all dependencies.
If I still have troubles with this numpy version, I'll downgrade it to a previous version (or link to the GLAST_EXT lib). 
Anyway, it is worthy to know about this new error to keep compatibility with future numpy versions.
Leonardo

**Comment by woodmd** [comment]
These errors should now be fixed in master.  I'm planning to make a new release that will include these changes in the next few days.
