### ISSUE TITLE
example light curve of mkn421

### ISSUE THREAD

**Issue by suvenduat** [fermiPy/fermipy#115]
Hi,

I am running the fermipy example script of mkn421. It runs perfectly producing the SED plot but when I add "gta.lightcurve" to generate light curve, it shows
WARNING GTAnalysis._make_lc(): Analysis failed in time range XX to YY.
It produces many folders but the results are all 0.00
Am I missing something?

My code is:

gta = GTAnalysis('config.yaml')
gta.setup()
gta.write_roi('fit0')
gta.optimize()
gta.write_roi('fit1')
gta.free_sources(distance=1.0,pars='norm')
gta.fit()
gta.sed('mkn421', make_plots=True)
gta.write_roi('fit2')
c = np.load('fit1.npy').flat[0]
print "source name", c['sources'].keys()
print "ts", c['sources']['3FGL J1104.4+3812']['ts']
print "npred", c['sources']['3FGL J1104.4+3812']['npred']
# Create TS map:
model = {'Index' : 2.0, 'SpatialModel' : 'PointSource'}
maps = gta.tsmap('fit1',model=model, make_plots=True)
gta.plotter.make_tsmap_plots(maps, roi=gta.roi)

# Generate a lightcurve with 2-week binning
lc = gta.lightcurve('3FGL J1104.4+3812', binsz=86400.*14.0, make_plots=True)

**Comment by woodmd** [comment]
If you using the sample analysis of Mkn421 then I suspect the problem is that you didn't pass a spacecraft file (i.e. with `data.scfile`).  The spacecraft file for the full mission is quite large (~1 GB) so I intentionally left it out of the tarball.

**Comment by suvenduat** [comment]
Ohh...I see...now it works...Thank you
