### ISSUE TITLE
Residual maps generation

### ISSUE THREAD

**Issue by skumarudel** [fermiPy/fermipy#119]
![casa_analysis02-08-2017 002](https://cloud.githubusercontent.com/assets/20157341/22834174/4d175ad2-ef82-11e6-8a11-2fe7852ca8df.jpg)

I am using fermipy version 0.11.0 and trying to do an analysis from 300 MeV to 300 GeV. After I optimize the global model for the analysis, I tried to produce the residual excess maps like this:

model = {'Index' : 2.0, 'SpatialModel' : 'PointSource'}
maps = gta.residmap('fit1_emin300MeV',model=model, loge_bounds=[np.log10(300),None])
maps = gta.residmap('fit1_emin1000MeV',model=model, loge_bounds=[np.log10(1000),None])
maps = gta.residmap('fit1_emin10GeV',model=model, loge_bounds=[np.log10(10000),None])
maps = gta.residmap('fit1_emin100GeV',model=model, loge_bounds=[np.log10(100000),None])

where loge_bounds takes a list as 
loge_bounds : list
   Restrict the analysis to an energy range (emin,emax) in
   log10(E/MeV) that is a subset of the analysis energy range.
   By default the full analysis energy range will be used.  If
   either emin/emax are None then only an upper/lower bound on
   the energy range wil be applied. 

If you look at the picture of residual maps for all four different "emin", they all look same. It is quite weird. Looks like a bug.
Can anybody do a quick check

thanks
Sajan!

**Comment by woodmd** [comment]
Sorry for the long delay in replying.  This should now be fixed in release 0.13.4.
