### ISSUE TITLE
Remove installation notebook?

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#12]
I'd suggest to remove https://github.com/fermiPy/fermipy/blob/master/notebooks/Installation.ipynb and keep the install instructions in one place: http://fermipy.readthedocs.org/en/latest/install.html

It's hard to keep different docs up to date ... currently both are outdated (still mentioning `pywcsgrid` instead of `wcsaxes`).

I'd also suggest to remove the notebooks from here:
https://github.com/gammapy/PyGamma15/tree/gh-pages/tutorials/fermi
and just maintain the version in the Fermipy repo.

**Comment by cdeil** [comment]
For the `PG 1553+113` notebook I'm still getting this error because the file at that URL is corrupt:
```
--2015-11-23 17:59:49--  http://www.slac.stanford.edu/~mdwood/fermipy/pg1553.tar.gz
Resolving www.slac.stanford.edu (www.slac.stanford.edu)... 134.79.121.151, 2620:114:d000:c5e6::11
Connecting to www.slac.stanford.edu (www.slac.stanford.edu)|134.79.121.151|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 131072 (128K) [application/x-tar]
Saving to: ‘pg1553.tar.gz’

pg1553.tar.gz       100%[=====================>] 128.00K   113KB/s   in 1.1s   

2015-11-23 17:59:51 (113 KB/s) - ‘pg1553.tar.gz’ saved [131072/131072]

pg1553/bexpmap_00.fits: (Empty error message)
tar: Error exit delayed from previous errors.
```

**Comment by woodmd** [comment]
Good idea.  I removed the notebooks from the PyGamma repo and updated the tutorial instructions to reflect the change (although I guess it's unlikely that anyone will be revisiting the tutorials at this point).  I also fixed the corrupted tarball so I think you should be able to run the pg1553 notebook now.

**Comment by cdeil** [comment]
Thanks, the pg1553 tutorial now works.

> I guess it's unlikely that anyone will be revisiting the tutorials at this point

I think the notebooks are a very nice resource to learn Fermipy and should be linked to from the official docs: http://fermipy.readthedocs.org/en/latest/index.html
Notebooks are harder to maintain than Sphinx docs (diffs often large when images change and often hard to read), but they are better for demos or users exploring interactively.

FYI: If you want to maintain them / make them parts of the docs, there's  https://github.com/paulgb/runipy which can be used to check that the notebooks still run without raising an exception in continuous integration. And there's projects like http://mybinder.org/ that make it possible to make these notebooks available online for people to play with without having to install software on their computer. These are things I'd like to set up for Gammapy as well, but haven't gotten around to yet.
