### ISSUE TITLE
How to test if the Source finding module find real or spurious sources in the field of view?

### ISSUE THREAD

**Issue by skumarudel** [fermiPy/fermipy#129]
Hi,
I am trying to analyze 8 years of Fermi-LAT data which is almost double the amount of data used in 3FGL catalogue. In order to avoid the biases in the spectral analysis of my source of interest, I did a dedicated search for new point sources in the field of view. Here is the procedure I followed:
model = {'Index' : 2.0, 'SpatialModel' : 'PointSource'}
srcs = gta.find_sources(model=model, sqrt_ts_threshold=8.0, min_separation=0.5)
gta.optimize()
srcs = gta.find_sources(model=model, sqrt_ts_threshold=6.0, min_separation=0.4)
gta.optimize()
srcs = gta.find_sources(model=model, sqrt_ts_threshold=4.0, min_separation=0.3)
gta.optimize()

With this procedure, I found lot of new sources in the field of view. My question is, how to test whether the newly found sources are real or fake (may be due to defects in galactic diffuse model)? 

Secondly, Should I use model source with a index of '2.0' or I should I try to use other indexes also, for example 1.0 and 3.0?
thanks for help!

**Comment by woodmd** [comment]
The standard practice for assessing sensitivity to diffuse systematics is to repeat your analysis with so-called alternative models such as the ones developed for the SNR catalog:

https://fermi.gsfc.nasa.gov/ssc/data/access/lat/1st_SNR_catalog/

However unless your source is close to the plane (galactic latitude less than ~10 deg) diffuse-induced systematics for point-source analysis should be fairly small.  

Also it probably isn't necessary to call `find_sources` more than once (maybe twice if you have a particularly complex region).  The `min_separation` cut is only applied to the separation of sources found within a given iteration so unless you have a specific motivation I'd recommend sticking with the default value (0.5 deg).  The only real advantage to using smaller values is to improve the computational efficiency (finding more sources in a given iteration).
