### ISSUE TITLE
fermipy instillation with docker

### ISSUE THREAD

**Issue by reginacaputo** [fermiPy/fermipy#130]
Hi, 
I was running an older version of fermipy with docker (17.03.1-ce-mac5) on my Mac (OSx 10.12.4). It was able to open jupyter notebooks with the command from the instillation instructions.

I updated to the latest version of fermipy today and run the same command and this is what I get: 
$ docker run -it --rm -p 8888:8888 -v $PWD:/workdir -w /workdir fermipy/fermipy
[I 20:00:55.484 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 20:00:55.499 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[C 20:00:55.505 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.

The first two lines are expected but the 3rd is new. I can not figure out how to get around this (I've tried putting the --allow-root flag in various places with no luck). I'll also note that the following works: 
docker run -it --rm -v $PWD:/workdir -w /workdir fermipy/fermipy ipython

**Comment by cdeil** [comment]
@cnachi had the same error yesterday and asked me about it. I haven't used this myself and don't know.

@woodmd ?

**Comment by woodmd** [comment]
It may be that a recent change in the behavior of jupyter could have triggered this (the image is always picking up the latest version).  I'll investigate this now to see if I can reproduce the issue.

**Comment by woodmd** [comment]
I've regenerated the image adding the `--allow-root` flag as directed by the error message and afterward was able to successfully launch a container.  I'm still not sure if there is some potential security issue with running things in the container as root but doing so seems to be simpler than creating a dummy user account.  In any event you should be able to grab the latest image by running `docker pull fermipy/fermipy`.

**Comment by reginacaputo** [comment]
Great, Thank you. It's working now

**Comment by cnachi** [comment]
@woodmd , @cdeil : Just tried it works for me too now, thanks !
