### ISSUE TITLE
diffuse response corrected file 

### ISSUE THREAD

**Issue by suvenduat** [fermiPy/fermipy#135]
I want to use fermipy to reduce data on a large number of objects. I have the diffuse response corrected file downloaded from Fermi site. I assume if I use diffuse response corrected file, the reduction will be faster but how to use them in gta.setup()?
Thanks.

**Comment by woodmd** [comment]
The diffuse response columns are only used for unbinned analysis while fermipy uses exclusively binned analysis.  Using an FT1 file with diffuse responses will have no effect on the speed of your analysis.
