### ISSUE TITLE
Improve and cleanup logging

### ISSUE THREAD

**Issue by woodmd** [fermiPy/fermipy#137]
There are several improvements we should make to have a better and more consistent scheme for logging:
* Currently there are some modules that are using print statements.  These should be updated to use the python logger.
* Logging is currently performed with a single logger instance owned by the `GTAnalysis` instance but this isn't really compatible with logging that needs to be done in standalone functions (e.g. in `fermipy.utils`) or in external libraries (eventually gammapy once we finished the maps class transition).  We should think about a unified scheme for logging that handles both cases.  astropy and gammapy both use a pattern of instantiating a logger instance at the top of each module so I think this approach could probably be adapted for fermipy.

I don't have time to work on this now but this would potentially a nice self-contained project for someone that wanted to contribute to fermipy.

**Comment by eacharles** [comment]
Good enough for now.
