### ISSUE TITLE
Systematic error due to galactic diffuse model?

### ISSUE THREAD

**Issue by skumarudel** [fermiPy/fermipy#139]
Hi,
I did an analysis for a 20x20 degree region around a source. The model I used contain all the sources with in 20 degree radius from the source of interest. I did the fitting of data with this model using standard likelihood routine in fermipy.  Then I produced the SED by freezing all the background sources and use the bin index for source = -2.0.
 My next job is to estimate the systematic error on the spectral measurements due to the galactic diffuse model. The procedure I followed is that I change the normalization parameter of galactic diffuse model by +/- 5 %  artifically and freeze all the background sources and then produce the SED again. Is it the the right way to do it?
My next question is if I need to  calculate the expected number of counts from galactic diffuse model within 3 degree radius from the source of interest, how can I do that in fermipy. This will give me the relative importance of my source and galactic model...
I hope it is clear enough what I want to ask.
thanks!

**Comment by woodmd** [comment]
Your method of changing the normalization of the galactic diffuse by 5% is probably going to overestimate the diffuse systematic in most regions of the sky (although along the ridge it may actually be an underestimate in some cases).  The recommended procedure for testing diffuse systematics is to rerun your analysis with alternative diffuse models.  There is a set of alternative IEMs that were generated for the 1st SNR catalog that can be downloaded from the [FSSC](https://fermi.gsfc.nasa.gov/ssc/data/access/lat/1st_SNR_catalog/).  For more details on how to use these models I would recommend reading the relevant section of the SNR catalog paper.

Regarding the integrated counts around the source of interest.  At present there is no function to do this in fermipy but I agree that it would be a nice functionality to have.  If you open a feature request for this we can add it to our todo list.
