### ISSUE TITLE
Undefined name errors

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#14]
I looked a bit at the Fermipy code in PyCharm and it points out some issues.

@woodmd Are these bugs or is this old unused code?
```
$ pyflakes-2.7 fermipy | grep undefined
fermipy/plotting.py:313: undefined name 'hdulist'
fermipy/plotting.py:316: undefined name 'hdulist'
fermipy/residmap.py:250: undefined name 'enumbins'
fermipy/residmap.py:251: undefined name 'enumbins'
```

**Comment by woodmd** [comment]
Those were in a section of unused code.  I went through and cleaned up most of the errors reported by pyflakes.  In the future I'll try to be more diligent about running a code checker to catch these kinds of issues (or just doing my development in pycharm).
