### ISSUE TITLE
Directory handling

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#141]
Hello,

I'm having issues with the way fermipy is using directories. My goal is to use one script in a parent directory to start a new instance of GTAnalysis for each of several subdirectories such that ALL working and output files be placed inside each of them. I've tried using the configurations fileio/outdir, fileio/workdir, and fileio/scratchdir and nothing so far has changed where fermipy is creating files (such as evfile_00.txt, ft1_00.fits, etc.). It always drops everything into the parent directory from where I'm running the script. I've also tried changing the current python working directory using this: https://stackoverflow.com/a/24176022
but nothing changes.

I'm actually not sure what is the intended behavior of those config options.

Any help?
Thanks!

**Comment by woodmd** [comment]
It should be sufficient to set `outdir` to the path of the directory where you want the output products to go.  For instance this is how you would create two instances that use different output directories:
```
gta0 = GTAnalysis('config.yaml',fileio={'outdir' : 'outputdir0'})
gta1 = GTAnalysis('config.yaml',fileio={'outdir' : 'outputdir1'})
```
If you point me to a copy of your working area I could have a look to see what might be wrong with the configuration you're using.
