### ISSUE TITLE
gta.lightcurve()

### ISSUE THREAD

**Issue by tlewis13** [fermiPy/fermipy#142]
I am working with 3C 279 data published in Hayashida et al. (2015), Epoch B, which was the exciting 2013 flare.  It was 0.2 days of data for which those authors were able to make a 192 min lightcurve.  I tried repeating that analysis, and failed in the likelihood analysis because the background sources were not sufficiently detected.  

Then, I took 3 months prior and 3 months post flare.  I was not able to get the likelihood analysis and run the lightcurve function, freeing 3C 273 and the background for 1 month time bins.  I was not able to get the lightcurve function to run for 1 week time bins or 1 day time bins.  It tends to fail quickly in each bin without running the LTcube.

I began again in a new directory, copying over the setup files, but not the lightcurve files and directories.  I reloaded the setup.  I applied an energy cut (gta.set_energy_range(2,3)).  I ran the 6 month dataset with 1 month bins, but cut in energy.  The lightcurve function fails in each bin, declining to calculate the LTcube.  

I repeated this analysis on about 1 month of data for the same source (Hayashida et al., 2012, epoch A), binned into 1 week bins.  I left 3C 273 and the background free.  The lightcurve function fails. I tried NOT freeing 3C 273 and the background, and got a lightcurve.

I began again in a new directory, copying over the setup files, but not the lightcurve files and directories.  I reloaded the setup.  I applied an energy cut (gta.set_energy_range(2,3)).  I ran the 1  month dataset with 1 week bins, but cut in energy.  The lightcurve function fails in each bin, declining to calculate the LTcube.  I tried un-freeing the background and 3C 273, but nothing was improved. 

So, I cannot calculate any useful light curves using the lightcurve function because the bins are far too large and cannot be divided into energy bands.  Otherwise it does not return a light curve at all.

**Comment by woodmd** [comment]
If you point me to your configuration and log files I can try to have a closer look.  I haven't tested the lightcurve function on very short time scales so it may be that there are some issues that specifically arise for this type of analysis.

**Comment by tlewis13** [comment]
I just tried sending the log file for the shorter analysis I ran, but your
mail system kicked it back because it was too big.  Is there somewhere else
I can send it?

After talking with some other students, we suspect that the problem may be
with the Fermi Summer School VM.  I have not been able to verify this by
rerunning the analysis without it yet.  But, 3C 279 is a fairly bright
blazar - it should be visible on timescales of a few hours, especially
during flares.  I was intentionally working through previously
analyzed/published data for that reason.

**Comment by woodmd** [comment]
I'm closing this issue since it's not clear how relevant it is given the recent improvements we've made to the lightcurve method.  These aren't yet in a tagged release but you can try installing the current development version as follows:

`pip install git+https://github.com/fermiPy/fermipy.git`

We still see failures on very short time scales (< day) which we hope to address in the near future.  On week and longer time scales the method should be fairly robust (we've run it successfully on all 3FGL sources with only a few failures).  If you're still encountering issues like your original one feel free to reopen this issue.

**Comment by tlewis13** [comment]
The project I was attempting several months ago was to take 1 day of data
during a hard bright flare in 3C 279 (which lasted only 12 hours) and bin
the light curve by 3 hours.  The counts are present to support this extreme
measure for this particular observation, but since the lightcurve function
is unable to address the data reduction, I have not been able to make any
progress, and focused instead on other projects.

The lack of functionality is disappointing because it prevents probing
anything close to the minimum variability timescale of blazars, even when
the data is intrinsically sufficient to do so.
