### ISSUE TITLE
gta.setup hard codes the fermipy.log path

### ISSUE THREAD

**Issue by tlewis13** [fermiPy/fermipy#143]
This is problematic because I copy the setup files into other places in order to begin from the likelihood analysis output, but I want to create different branches of the subsequent analysis (i.e. light curves in separate energy bands).  So, I should have the analysis write to the "fermipy.log" file which is located in the data directory that I am working from.  

We tried running 
gta.config['fileio']['logfile'] = './fermipy'
to reset the path, then reran "gta.setup()", but it did not reset the path, and my present notebook continued writing to a log file in the previous directory (where it was initially created).  This created the problem that multiple notebooks are writing to a single log file, which is at the very least confusing.

**Comment by woodmd** [comment]
At present there is no way to change the logging path of `GTAnalysis` once it's been instantiated.  Logging is performed with the python `logging` module and as such the logger can only point to a single log file at a time.  There is an outstanding feature request to make the logging functionality more flexible (see #137) which could include having multiple log files open at once.  

In the meantime my suggestion would be to simply create a new `GTAnalysis` instance and assigned it to the same reference, e.g.
```
gta = GTAnalysis('config.yaml',fileio={'logfile' : {<path for first log file> } })
<do some analysis>
gta = GTAnalysis('config.yaml',fileio={'logfile' : {<path for second log file> } })
```
Creating the second `GTAnalysis` instance should trigger the change to the logging configuration.  However at this point you will no longer be able to write to the original log file.

One additional note -- in general it is not valid to change the configuration dictionary as in your example.  Configuration can *only* be controlled with the configuration that you pass to the `GTAnalysis` constructor.
