### ISSUE TITLE
add_source error when adding a file

### ISSUE THREAD

**Issue by jani404** [fermiPy/fermipy#144]
Hello! First of all, I'd like to thank you all for your hard work pulling out this project.

We get an error message when adding a template (for an extended source) like:
-As indicated in http://fermipy.readthedocs.io/en/latest/model.html -
gta.add_source('SourceA',{ 'ra' : 120.0, 'dec' : -3.0,
                'SpectrumType' : 'PowerLaw', 'Index' : 2.0, 'Scale' : 1000, 'Prefactor' : 1e-11,
    'SpatialModel': 'SpatialMap', 'file' : 'template.fits' })

Qing-wen Tang found in:
http://fermipy.readthedocs.io/en/latest/_modules/fermipy/gtanalysis.html#GTAnalysis.add_source
that instead of 'file' we should use 'Spatial_Filename'.
Best!

**Comment by woodmd** [comment]
Yes the example in the documentation is wrong -- I've now committed a fix to the documentation page.  As you found you should use `Spatial_Filename` to pass in the name of the spatial template file.
