### ISSUE TITLE
EblAtten::FileFunction Error

### ISSUE THREAD

**Issue by Mitsunari-Takahashi** [fermiPy/fermipy#145]
Hello, 
I got an error when I tried to set up a source model with 'SpectrumType' : 'EblAtten::FileFunction'. I can successfully set up for 'FileFunction' and 'EblAtten::PowerLaw2' but failed for 'EblAtten::FileFunction' because of a runtime error, the source map fits file was not found.
I defined the source as this.
```
  sources :
    - { 'name' : 'testsrc', 'ra' : 311.75371, 'dec' :76.108033, 'SpectrumType' : 'EblAtten::FileFunction', 'Normalization' : { value : 1.0, max : !!float 1e5, min : !!float 1e-5, scale : 1, free : '0' }, 'Spectrum_Filename' : 'spectrum.txt', 'tau_norm' : { value : 1.0, max : 10, min : 0, scale : 1.0, free : '0' }, 'redshift' : { value : 1.17, max : 10, min : 0, scale : 1, free : '0' }, 'ebl_model' : { value : 4, max : 8, min : 0, scale : 1.0, free : '0'}, 'SpatialModel': 'PointSource'}
```

I got the following output of fermipy.
 
> bash-4.1$ python
> Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> \>>> from fermipy.gtanalysis import GTAnalysis
> \>>> gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})
> 2017-06-12 06:28:03 INFO    GTAnalysis.__init__():
> \--------------------------------------------------------------------------------
> fermipy version 0.14.1
> ScienceTools version ScienceTools-11-05-00
> \>>> gta.setup()
> 2017-06-12 06:28:12 INFO    GTAnalysis.setup(): Running setup.
> 2017-06-12 06:28:12 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
> 2017-06-12 06:28:12 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
> 2017-06-12 06:28:12 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/GRB/Regualr/DATA/FITS/LAT/160509374_P8_P302_ALL_ft1_484476630_484487930.fits outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ft1_00.fits ra=311.75371 dec=76.108033 rad=21.7132034356 tmin=484477130.0 tmax=484477250.0 emin=100.0 emax=100000.0 zmin=0.0 zmax=100.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version ScienceTools-11-05-00
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): Applying filter string: angsep(RA,DEC,311.75371,76.108033) < 21.71320344 && ((EVENT_CLASS&o200) != o0) && ((EVENT_TYPE&o3) != o0) && 100 < ENERGY && ENERGY <= 100000 && 484477130 < TIME && TIME <= 484477250 && 0 < ZENITH_ANGLE && ZENITH_ANGLE <= 100 && gtifilter()
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): Done.
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 1.36 s
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
> 2017-06-12 06:28:13 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ft1_00.fits" evtable="EVENTS" scfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/GRB/Regualr/DATA/FITS/LAT/160509374_P8_P302_BASE_ft2_484476630_484487930.fits sctable="SC_DATA" outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=100.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
> 2017-06-12 06:28:17 INFO    GTBinnedAnalysis.run_gtapp(): Working on file /nfs/farm/g/glast/u/mtakahas/FermiAnalysis/GRB/Regualr/DATA/FITS/LAT/160509374_P8_P302_BASE_ft2_484476630_484487930.fits
> 2017-06-12 06:28:17 INFO    GTBinnedAnalysis.run_gtapp(): .........................!
> 2017-06-12 06:28:17 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 3.27 s
> 2017-06-12 06:28:17 INFO    GTBinnedAnalysis.run_gtapp(): Running gtbin.
> 2017-06-12 06:28:17 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtbin evfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ft1_00.fits scfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/GRB/Regualr/DATA/FITS/LAT/160509374_P8_P302_BASE_ft2_484476630_484487930.fits outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ccube_00.fits algorithm="ccube" ebinalg="LOG" emin=100.0 emax=100000.0 enumbins=6 ebinfile=NONE tbinalg="LIN" tbinfile=NONE nxpix=300 nypix=300 binsz=0.1 coordsys="CEL" xref=311.75371 yref=76.108033 axisrot=0.0 rafield="RA" decfield="DEC" proj="AIT" hpx_ordering_scheme="RING" hpx_order=3 hpx_ebin=yes hpx_region="" evtable="EVENTS" sctable="SC_DATA" efield="ENERGY" tfield="TIME" chatter=3 clobber=yes debug=no gui=no mode="ql"
> 2017-06-12 06:28:18 INFO    GTBinnedAnalysis.run_gtapp(): This is gtbin version ScienceTools-11-05-00
> 2017-06-12 06:28:18 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtbin. Execution time: 0.79 s
> 2017-06-12 06:28:18 INFO    GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
> 2017-06-12 06:28:18 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtexpcube2 infile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ltcube_00.fits cmap=none outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./bexpmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 nxpix=360 nypix=180 binsz=1.0 coordsys="CEL" xref=0.0 yref=0.0 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=100000.0 enumbins=6 ebinfile="NONE" bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version ScienceTools-11-05-00
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 5.82 s
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
> 2017-06-12 06:28:24 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtexpcube2 infile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ltcube_00.fits cmap=none outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./bexpmap_roi_00.fits irfs="P8R2_SOURCE_V6" evtype=3 nxpix=300 nypix=300 binsz=0.1 coordsys="CEL" xref=311.75371 yref=76.108033 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=100000.0 enumbins=6 ebinfile="NONE" bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version ScienceTools-11-05-00
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 7.62 s
> WARNING: FITSFixedWarning: RADECSYS= 'FK5 '
> the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
> 2017-06-12 06:28:32 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtsrcmaps scfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/GRB/Regualr/DATA/FITS/LAT/160509374_P8_P302_BASE_ft2_484476630_484487930.fits sctable="SC_DATA" expcube=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ltcube_00.fits cmap=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./ccube_00.fits srcmdl=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./srcmdl_00.xml bexpmap=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./bexpmap_00.fits wmap=none outfile=/nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version ScienceTools-11-05-00
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named testsrc
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named isodiff
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named galdiff
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff....................!
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff....................!
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for testsrc....................!
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 146.25 s
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
> 2017-06-12 06:30:58 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/u/gl/mtakahas/work/pip_local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 978, in setup
>     self._create_likelihood()
>   File "/u/gl/mtakahas/work/pip_local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1003, in _create_likelihood
>     c._create_binned_analysis(srcmdl)
>   File "/u/gl/mtakahas/work/pip_local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 4792, in _create_binned_analysis
>     self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
>   File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-05-00/python/BinnedAnalysis.py", line 61, in __init__
>     pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
>   File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-05-00/python/pyLikelihood.py", line 3550, in AppHelpers_checkExposureMap
>     return _pyLikelihood.AppHelpers_checkExposureMap(*args)
> RuntimeError: File not found: /nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/./srcmap_00.fits

I'm working in a directory of the SLAC server, </nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test>.
The full config file is </nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test/config.yaml>.

Could you help me to use this funciton?

Thank you,
Mitsunari

**Comment by vaidehiratna** [comment]
I just looked into your file directory. I presume that the file function you are using corresponds to the file 'spectrum.txt'. In this file, I guess the first column is energy in MeV and second column is flux. Now, I see that the energy column starts from 10 MeV and goes up to 1 TeV. I believe that you are using the standard galactic diffuse background model 'gll_iem_v06.fits' which is not defined below 58 MeV or so. Therefore, if you set the minimum energy in your spectrum.txt file as 100 MeV, then this problem may get solved. Hope this helps.

**Comment by Mitsunari-Takahashi** [comment]
Thank you for your response. 
I removed the rows from 10 MeV to 89 MeV (just before 100 MeV) of 'spectrum.txt' but the error did not change.
I also tried removing 'galdiff' component and setting the redshift of my test source to 0, but the same error was output in neither case.

**Comment by woodmd** [comment]
Did you ever resolve this? (sorry for taking so long to respond)

I haven't used the EBL file functions extensively so this could be a bug.  Could you point me to an analysis directory at SLAC that demonstrates the issue?

**Comment by Mitsunari-Takahashi** [comment]
No, I didn't.
The directory is /nfs/farm/g/glast/u/mtakahas/FermiAnalysis/fermipy_test.
Thank you.

**Comment by woodmd** [comment]
I was able to reproduce this error -- however it looks like it is a bug in the STs rather than fermipy.  The analysis is failing due to a segfault that occurs when running gtsrcmaps.  I don't see the error when switching to `EblAtten::PowerLaw2` so it seems to be a specific problem with `EblAtten::FileFunction`.  @me-manu found a similar issue with `EblAtten::PLSupExpCutOff` so I suspect the two are related.  I will try to take a closer look at this and see if I can put together a fix for the STs in the meantime you may want to try using one of the other EblAtten models.

**Comment by Mitsunari-Takahashi** [comment]
Thank you very much. I will report the results when I try the others.

**Comment by CorneliaArcaro** [comment]
Hi could you please paste a minium example where to take account for the source to be analysed for for the EBL attenuation, with the possibility to define the redshift and the EBL model to be used for the correction? Thanks
