### ISSUE TITLE
Error in GTAnalysis. Probably Python3 problem?

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#150]
I tried to run `gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})`. I use Python3.5 in Spyder, fermipy was installed from anaconda. I got an error in pyLikelihood.py (^ is under "Error")

>raise AttributeError,name
>                       ^
>SyntaxError: invalid syntax

I found out that such syntax is not allowed in new codes and changed all such lines in pyLikelihood.py to `raise AttributeError(name)`.
Now I get

>File "\<ipython-input-2-db92e0b6ad31\>", line 1, in \<module\>
    runfile('/home/bulat/work/fermi/tools/flare1/roi30/100_MeV/py/gt.py', wdir='/home/bulat/work/fermi/tools/flare1/roi30/100_MeV/py')
  File "/home/bulat/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/home/bulat/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "/home/bulat/work/fermi/tools/flare1/roi30/100_MeV/py/gt.py", line 8, in \<module\>
    from fermipy.gtanalysis import GTAnalysis
  File "/home/bulat/anaconda3/lib/python3.5/site-packages/fermipy/gtanalysis.py", line 20, in \<module\>
    import fermipy.gtutils as gtutils
  File "/home/bulat/anaconda3/lib/python3.5/site-packages/fermipy/gtutils.py", line 6, in \<module\>
    import pyLikelihood as pyLike
  File "/home/bulat/ScienceTools-v10r0p5/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/pyLikelihood.py", line 7, in \<module\>
    import lib_pyLikelihood
ImportError: /home/bulat/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC

and don't know what to do. I saw a couple of issues with Python3 here, but they don't seem to concern my problem.
Typing `conda info fermipy` gives a long list of packages the last of which is fermipy 0.14.1 py35_0. That is python3, right? So I'm really confused, could anyone help?

**Comment by woodmd** [comment]
The Fermi STs are currently only compatible with python 2.7.  There is a subset of modules in fermipy which can be run without a Fermi STs installation and are both python 2.7 and 3.5 compatible.  However if you want to do likelihood analysis your only option is to run under python 2.7.

**Comment by jeget** [comment]
Thanks for your response! Do I understand correctly that likelihood analysis is at the moment not available in conda package at all? Because I tried to make a python2-environment with
`conda create --name python2 python=2.7 spyder fermipy`
and the first error disappeared, but the second is still there

> ImportError: /home/bulat/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC

Does it mean fermipy should be installed with pip only?

**Comment by woodmd** [comment]
If you're running linux you should be able to install Fermipy with either pip or anaconda (although anaconda is recommended).  However when working with multiple python environments you need to ensure that you run the ST conda setup script *after* you activate the environment, e.g.:
```
source activate python2
source condasetup.sh
```
Instructions for setting up an anaconda installation with fermipy are available on this page: http://fermipy.readthedocs.io/en/latest/install.html#installing-with-anaconda-python

**Comment by jeget** [comment]
I see that previously I forgot to source condasetup.sh... I tried to do everything from the beginning.

```
conda install fermipy
conda create --name python2 python=2.7 spyder fermipy
source activate python2
source condasetup.sh
spyder
```

(Setup file is already there.) Now, writing `from fermipy.gtanalysis import GTAnalysis` brings the same error

> /home/bulat/anaconda3/envs/python2/bin/../lib/libreadline.so.6: undefined symbol: PC

What do I do incorrectly?

**Comment by woodmd** [comment]
I don't see any obvious mistake.  What OS are you running?

**Comment by jeget** [comment]
Ubuntu 16.04.

**Comment by jeget** [comment]
Please, look at the following (file gt.py contains lines `from fermipy.gtanalysis import GTAnalysis` and `gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})`)
```
bulat@bulat-N46VB:py$ source activate python2
(python2) bulat@bulat-N46VB:py$ which python
/home/bulat/anaconda3/envs/python2/bin/python
(python2) bulat@bulat-N46VB:py$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from fermipy.gtanalysis import GTAnalysis
Plotter is MatPlotlib
>>> gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})
2017-09-14 12:27:57 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.14.1 
ScienceTools version 
WARNING: UnitsWarning: 'photon/cm**2/MeV/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'photon/cm**2/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'erg/cm**2/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
>>> exit()
(python2) bulat@bulat-N46VB:py$ python gt.py
Traceback (most recent call last):
  File "gt.py", line 8, in <module>
    from fermipy.gtanalysis import GTAnalysis
  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 20, in <module>
    import fermipy.gtutils as gtutils
  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtutils.py", line 6, in <module>
    import pyLikelihood as pyLike
  File "/home/bulat/ScienceTools-v10r0p5/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/pyLikelihood.py", line 7, in <module>
    import lib_pyLikelihood
ImportError: /home/bulat/anaconda3/envs/python2/bin/../lib/libreadline.so.6: undefined symbol: PC
(python2) bulat@bulat-N46VB:py$ source condasetup.sh
(python2) bulat@bulat-N46VB:py$ which python
/home/bulat/ScienceTools-v10r0p5/x86_64-unknown-linux-gnu-libc2.19-0/bin/python
(python2) bulat@bulat-N46VB:py$ python
Python 2.7.8 (default, May 20 2015, 10:33:48) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fermipy.gtanalysis import GTAnalysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fermipy.gtanalysis
```
And `print(sys.path)` returns a bunch of directories all inside $FERMI_DIR.
If I run Spyder (after `source condasetup.sh`) then `from fermipy.gtanalysis import GTAnalysis` results in `ImportError: /home/bulat/anaconda3/envs/python2/bin/../lib/libreadline.so.6: undefined symbol: PC` as I wrote before.
A similar problem was discussed here https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/v9ce7qDhLww but in my case fermipy was installed with conda.

**Comment by woodmd** [comment]
I'm afraid that I probably won't have time to track this down as I don't have access to an Ubuntu 16.0 machine.  I know that this installation procedure should work on Ubuntu 14.0 since that's the distribution running the CI tests on travis.  You might try with a different Linux distribution -- formally the binaries you're using were built for Ubuntu 14.0 so I don't know if that could be the issue.  If you have root access to your machine you could also try following the Docker instructions (http://fermipy.readthedocs.io/en/latest/install.html#installing-with-docker).

**Comment by jeget** [comment]
I found the solution to my initial problem [here](https://github.com/ContinuumIO/anaconda-recipes/issues/56). After installation the readline package from the conda-forge channel the error has disappeared. Sorry, this was not a fermipy problem, but I didn't know it.
But now I ran into another issue. (I don't know if it's better to close this issue and start a new one.) Running gta.setup() reaches gtsrcmaps, then sticks at some point and starts to fill the memory so that finally everything stops. I tried to track the execution in debug mode. These are the last lines before I have to interrupt the process:
```
ipdb> n
> /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py(161)run_gtapp()
    159     stdin, stdout = gtapp.runWithOutput(print_command=False)
    160 
1-> 161     for line in stdout:
    162         logger.log(loglevel, line.strip())
    163 


ipdb> print(line)
Creating source named 3FGL J0530.8+1330


ipdb> n
KeyboardInterrupt: None
```
And here is the backtrace:
```
ipdb> bt
  /home/bulat/anaconda3/envs/python2/lib/python2.7/bdb.py(400)run()
    398             cmd = cmd+'\n'
    399         try:
--> 400             exec cmd in globals, locals
    401         except BdbQuit:
    402             pass

  <string>(1)<module>()

  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py(710)runfile()
    708             ipython_shell.run_cell_magic('cython', '', f.read())
    709     else:
--> 710         execfile(filename, namespace)
    711 
    712     clear_post_mortem()

  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py(93)execfile()
     91             else:
     92                 filename = fname
---> 93             builtins.execfile(filename, *where)
     94 except ImportError:
     95     # Python 3

  /home/bulat/work/fermi/tools/flare1/roi30/100_MeV/py/gt.py(11)<module>()
      7 
      8 from fermipy.gtanalysis import GTAnalysis
      9 
     10 gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})
---> 11 gta.setup()

  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py(975)setup()
    973         # Run setup for each component
    974         for i, c in enumerate(self.components):
--> 975             c.setup(overwrite=overwrite)
    976 
    977         # Create likelihood

  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py(4558)setup()
   4556         # Create source maps file
   4557         if not use_external_srcmap:
-> 4558             self._create_srcmaps(overwrite=overwrite)
   4559 
   4560         if not self.config['data']['cacheft1'] and os.path.isfile(self.files['ft1']):

  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py(4770)_create_srcmaps()
   4768 
   4769         if not os.path.isfile(self.files['srcmap']) or overwrite:
-> 4770             run_gtapp('gtsrcmaps', self.logger, kw, loglevel=loglevel)
   4771         else:
   4772             self.logger.log(loglevel, 'Skipping gtsrcmaps.')

> /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py(161)run_gtapp()
    159     stdin, stdout = gtapp.runWithOutput(print_command=False)
    160 
1-> 161     for line in stdout:
    162         logger.log(loglevel, line.strip())
    163 
```

**Comment by woodmd** [comment]
Did you ever manage to resolve this issue?  If you send me a link to a tarball of your analysis directory I could try to reproduce it on my end.

**Comment by jeget** [comment]
Sorry for silence... (I switched to gtapps from FSSC for a while.)
I tried running fermipy with newly downloaded data and it worked. The example with mkn421 from the docs also worked.
But then I tried building a light curve and encountered new problems...
I upgraded to 0.17.2 and also upgraded ST to 11.5.3. Then the line `from fermipy.gtanalysis import GTAnalysis` results in an error reported in #214. I tried the solution suggested there and got a problem with pip installation like here #211. I switched back to ST 10.0.5 and fermipy seems to work, but now `lc = gta.lightcurve('3FGL J0112.1+2245')` results in an error

```2018-07-02 02:13:11 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for 3FGL J0112.1+2245
2018-07-02 02:13:12 INFO    lightcurve_239557483_240162283 GTAnalysis._process_lc_bin(): Fitting time range 239557483 240162283
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter value: invalid date '        ''. [astropy.wcs.wcs]
Analysis failed in time range 239557483 240162283
<type 'exceptions.RuntimeError'>
Traceback (most recent call last):

  File "<ipython-input-9-0566cb4b90c6>", line 1, in <module>
    lc = gta.lightcurve('3FGL J0112.1+2245')

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/lightcurve.py", line 264, in lightcurve
    o = self._make_lc(name, **config)

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/lightcurve.py", line 409, in _make_lc
    mapo = map(wrap, itimes)

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/lightcurve.py", line 158, in _process_lc_bin
    gta.setup()

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1042, in setup
    self._create_likelihood()

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1072, in _create_likelihood
    self._init_roi_model()

  File "/home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1100, in _init_roi_model
    crd['loglike'] = -c.like()

  File "/home/bulat/ScienceTools-v10r0p5/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/AnalysisBase.py", line 73, in __call__
    return -self.logLike.value()

  File "/home/bulat/ScienceTools-v10r0p5/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/pyLikelihood.py", line 6159, in value
    return lib_pyLikelihood.BinnedLikelihood_value(*args)

RuntimeError: vector::_M_range_check
```
The error 'vector::_M_range_check' is mentioned in [FSSC FAQ](https://fermi.gsfc.nasa.gov/ssc/help/faq.html) but I think the answer is not relevant because in my case `gta.fit()` did return successfully.

**Comment by jeget** [comment]
I solved the problem just taking a template from [here](https://github.com/fermiPy/fermipy-extra).
