### ISSUE TITLE
Setting energy range during likelihood fitting

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#165]
Hello,

I am trying to perform the LAT data analysis using fermiPy for the energy range emin=100 MeV to emax=1 TeV. I generated all the files and perform the fitting and got the results. Now, I want to perform the likelihood fitting using the same files in two energy bands; (i) emin = 100 MeV to emax = 10 GeV (ii) emin = 10 GeV to emax = 1 TeV. The model I want to test, is EblAtten::PowerLaw2.

I understand that it can be done using gta.sed tool. However, I want to determine the accurate value of the power law photon index (with uncertainties) in each energy bin. The SED tool, I think, does not allow the photon index to vary.

Could you please let me know if it is possible to set the desired energy range before performing the fitting? Or, do I need to first generate the files for these two energy ranges and perform the fitting separately? It would be great if we can set the energy range during the fitting itself, e.g.

gta.fit(emin=100, emax=10000) or something similar.

Thanks.

**Comment by jefemagril** [comment]
Just my opinion, but adding `emin=` and `emax=` options to `gta.fit()` doesn't sound like the best idea because I believe it would need to rerun the setup scripts anyway to make the appropriate new files. Since the underlying Science Tools don't support this type of thing, it would require these ad hoc steps to create whole new analyses. Instead, you could use a meta script to run the energy bands separately as you described.

**Comment by vaidehiratna** [comment]
Hi Jeff,
Thanks for the suggestion. I think, in the conventional pylikelihood method, we can set the desired energy range without generating new set of files. Something like as follows

from BinnedAnalysis import *
obs = BinnedObs(srcMaps='srcmap_00.fits',expCube='LTCube.fits',binnedExpMap='bexpmap_00.fits',irfs='P8R2_SOURCE_V6')
like1 = BinnedAnalysis(obs,'fit.xml',optimizer='DRMNFB')
like1.setEnergyRange(emin,emax)     #Desired energy range can be inserted here
likeobj = pyLike.Minuit(like1.logLike)
like1.fit(verbosity=1,covar=True,optObject=likeobj)

I was just wondering whether something similar can be done within fermiPy environment. Let me know if I am missing something here.

Thanks.

**Comment by woodmd** [comment]
@vaidehiratna there is a `set_energy_range` method that I think does what you want.  See here:

http://fermipy.readthedocs.io/en/latest/fermipy.html#fermipy.gtanalysis.GTAnalysis.set_energy_range

You can use this to limit the fit to a subset of bins in the full energy range.  To restrict the fit to energies > 10 GeV you would use:
```
gta.set_energy_range(4.0,None)
```

**Comment by vaidehiratna** [comment]
Thanks. I will try and post the outcome.

**Comment by jefemagril** [comment]
Ah, sorry, I didn't know about this.

**Comment by sarabuson** [comment]
FYI, another way to do it in pyLikelihood is asking the estimated flux in just an energy range:

like.flux('Vela', emin=100, emax=3e5)

**Comment by vaidehiratna** [comment]
Thanks all. I am able to get the results. 👍

**Comment by woodmd** [comment]
@sarabuson what you suggest is slightly different than setting the energy range.  The arguments to `flux` change the range of integration but not the data that enter in the fit.
