### ISSUE TITLE
lightcurve problem

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#166]
This is the result when I try to run my script.

KeyError: 'Invalid configuration key: multithread (section : lightcurve)'

In my config.yaml I have this options

`lightcurve:
  multithread: false
  nthread: 2
  save_bin_data: false`

It returns the same error also for the other options in lightcurve.

**Comment by woodmd** [comment]
What version are you running?  I think the `multithread` option is only in `master` at the moment.

**Comment by imereu** [comment]
fermipy     0.15.1

**Comment by woodmd** [comment]
Ok as I indicate above to use the `multithread` option you'll need to upgrade to `master`.  Here's a command you can use to install the master branch with pip:

`pip install git+https://github.com/fermiPy/fermipy.git`

**Comment by imereu** [comment]
Thanks!
