### ISSUE TITLE
Fermipy installation issue

### ISSUE THREAD

**Issue by pmunar** [fermiPy/fermipy#17]
Dear fermipy team,

I am trying to install the fermipy distribution on a Fedora 21 with the ScienceTools-v10r0p5. I followed the steps in the installation tutorial but when I try to install it with the command 

python setup.py install --user

it produces an error that finishes like that:
  File "/tmp/easy_install-9RCj2h/healpy-1.9.1/setup.py", line 397, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

I attach the complete log file.

Any idea of what is missing that causes this crash? I have already installed healpy and other packages needed by fermipy.

Thanks.

    Pere.

[Fermipy_installation_log.txt](https://github.com/fermiPy/fermipy/files/57233/Fermipy_installation_log.txt)

**Comment by woodmd** [comment]
The primary installation procedure described in the documentation only works on OSX.  Are you using a source or a binary installation of the ScienceTools?  If you're using a binary installation then you can try these [alternate installation instructions](http://fermipy.readthedocs.org/en/latest/install.html#installing-with-anaconda-python) for anaconda python.

**Comment by pmunar** [comment]
Ok, thanks.
But before trying this, since I see that it will install a mini Anaconda distribution on my system, I want to know if this will affect my current python installation (I have a "normal" python and all libraries installed with pip, not Anaconda).

Thanks again!

**Comment by woodmd** [comment]
Everything installed by this procedure will live inside the $HOME/miniconda directory so it shouldn't affect your existing python installation.  Your shell environment (PATH, etc) is only modified when you run the condasetup.sh script so if you launch a fresh shell you should get back to your system python.

**Comment by woodmd** [comment]
Did this ever work for you?  There have been some reported issues with the healpy part of the installation so I was curious if you had encountered something similar.
