### ISSUE TITLE
getting error in running "gta.sed('source')"

### ISSUE THREAD

**Issue by poojabi1990** [fermiPy/fermipy#171]
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('config.yaml')
gta.setup()
gta.write_roi('fit0')
gta.optimize()
gta.write_roi('fit1')
gta.free_sources(distance=5.0,pars='norm')
gta.fit()
gta.sed('sourceA')

Then I got this error,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pooja/miniconda/lib/python2.7/site-packages/fermipy/sed.py", line 86, in sed
    o = self._make_sed(name, **config)
  File "/home/pooja/miniconda/lib/python2.7/site-packages/fermipy/sed.py", line 356, in _make_sed
    g = 1 - np.log10(f0 / f1) / np.log10(emin / emax)
ZeroDivisionError: float division by zero

"Can you please guide me, how to solve this?"

**Comment by TarekHC** [comment]
Hi @poojabi1990 

Can you print the model and the parameters before the `gta.sed()`?

You can do that by adding:
```python
gta.print_model()
gta.print_params()
```

Perhaps you are setting a min/max value in energy to zero in the model?

**Comment by poojabi1990** [comment]
Thank you @TarekHC ,
after writing,  gta.print_model() & gta.print_params(), 

2017-12-23 22:47:39 INFO    GTAnalysis.print_model(): 
I got this value for my source,
sourcename            offset    norm  eflux     index        ts       npred free
--------------------------------------------------------------------------------
SourceA              0.000  62.929  3.87e-08   3.22      0.07         8.1    *

2017-12-23 22:56:49 INFO    GTAnalysis.print_params(): 
 idx parname                  value     error       min       max     scale free
--------------------------------------------------------------------------------
SourceA
  91 norm                     0.987         0     1e-05     1e+05     1e+16     
  92 sigmav                    62.9       210         0     5e+03     1e-25    *
  93 mass                        35         0         1     5e+03         1     
  94 bratio                       1         0         0         1         1     
  95 channel0                     4         0         1        10         1     
  96 channel1                     1         0         1        10         1     


Actually, here I am modelling my source with DMFIitFunction. I think the problem is arising from my modelling selection.
Is there any constrain for using DMFitFunction in fermipy? 
I am new to this and would to like to use fermipy for my dark matter analysis.

**Comment by TarekHC** [comment]
Hi @poojabi1990 ,

I have never really used that model... So I'm afraid I won be able to help you much. 

> g = 1 - np.log10(f0 / f1) / np.log10(emin / emax)
ZeroDivisionError: float division by zero

What is clear is that the error you are getting is a ```ZeroDivisionError```. Make sure none of the flux and energy values is set to exactly 0.

**Comment by dimauromattia** [comment]
Hi @poojabi1990 ,

Could you provide more informations on your analysis? If you share a tarball of your analysis directory I can try to debug this further.

Cheers

Mattia

**Comment by poojabi1990** [comment]
Thank you @dimauromattia 

Here I have attached files for Ursa Minor analysis.

You could find two cofig.yaml files. 
[UMi.tar.gz](https://github.com/fermiPy/fermipy/files/1878864/UMi.tar.gz)
One is config_UMi_dmfit.yaml, in which I want to model Ursa Minor with DMFit Function but it always gives me error. The other config file is config_UMi_power_law.yaml, in which I modeled Ursa Minor with power law and it works completely fine. I want to model Ursa Minor with DmFit Function and would like to obtain sed values for dmfit function. But I couldn't solve it. Please suggest me if you have any idea of how to solve it.

With Regards,
Pooja
