### ISSUE TITLE
python fails loading libLikelihood.dylib after updating to El Capitan

### ISSUE THREAD

**Issue by robertazanin** [fermiPy/fermipy#18]
After having updated my operating system to El Capitan, fermipy gives me the following error:

GTBinnedAnalysis - INFO - dyld: Library not loaded: libLikelihood.dylib
2016-01-08 09:56:44 - GTBinnedAnalysis - INFO - Referenced from: /Users/roberta/FermiPASS8v10/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin13.4.0-without-root/x86_64-apple-darwin13.4.0/bin/gtsrcmaps
2016-01-08 09:56:44 - GTBinnedAnalysis - INFO - Reason: image not found
Traceback (most recent call last):
  ......
  File "/Users/roberta/FermiPASS8v10/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin13.4.0-without-root/x86_64-apple-darwin13.4.0/lib/python/pyLikelihood.py", line 4567, in AppHelpers_checkExposureMap
    return lib_pyLikelihood.AppHelpers_checkExposureMap(*args)
RuntimeError: File not found: srcmap_00.fits

If I run gtsrcmap by command-line than it works perfectly. 
Has someone else experienced the same problem?

Cheers, 
Roberta

**Comment by kialio** [comment]
Hi Roberta,

It's probably a library conflict and you'll probably need to recompile the science tools.  I put some instructions for doing this here:  https://gist.github.com/kialio/990325c1c4ef8b506e87  These instructions were for Yosemite but they should work on El Capitan.  It's also using brew instead of macports or fink.  If you have issues, let me know.

Another thing would be to double check that you're using the python that's in the tools and the system python isn't being loaded for some reason.  

Matt might have more suggestions.

Jeremy

**Comment by woodmd** [comment]
I haven't upgraded to El Capitan yet so unfortunately I don't have a good way of testing your exact setup.  Could you link the analysis yaml configuration and full log file somewhere?

**Comment by kialio** [comment]
I have El Capitan running so I can give this a test if you post the config files.

**Comment by robertazanin** [comment]
Hi Jeremy, Matthew,

thank you guys.
In this dropbox you can find the conf files and a Log.txt where I copied
the output of my screen.

https://www.dropbox.com/sh/r0xkln6k8kndafc/AACdCJy70sR0JyqaTPzlrQ-ka?dl=0


Thanks in advance.
Roberta


On 14 Jan 2016, at 15:18, Jeremy Perkins <notifications@github.com> wrote:

I have El Capitan running so I can give this a test if you post the config
files.

—
Reply to this email directly or view it on GitHub
<https://github.com/fermiPy/fermipy/issues/18#issuecomment-171655249>.

**Comment by kialio** [comment]
Hi Roberta,

I tracked this down to the new System Integrity Program (SIP) in El Capitan.  One of the things this does is disable access to DYLD_LIBRARY_PATH to 'protected' programs like python.  If you disable SIP (see http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11) then it should work.  I am not sure what the long term plans for working with SIP are but we need to think about it.

Jeremy

**Comment by robertazanin** [comment]
Hi Jeremy, 

you were right. Thank you very much. 

Cheers, 
R.

**Comment by akira-okumura** [comment]
Another workaround is to copy .so and .dylib files to /usr/lib, /usr/local/lib, or ~/lib if you want to keep SIP enabled. Creating symbolic links under one of these directories works as well.
