### ISSUE TITLE
Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by Fdepalma** [fermiPy/fermipy#182]
While localizing I get this error:
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.
I'm on a rhel6-64 slac server with this setup:
fermipy version 0.16.0+94.ga062 
ScienceTools version ScienceTools-11-07-00

**Comment by woodmd** [comment]
Are you using the slacsetup script to configure your environment?  What do you see when you run `which python`?

**Comment by Fdepalma** [comment]
Using your setup (mine was similar to the standard one), this issue disappeared. 
Thanks!
