### ISSUE TITLE
gta.sed error while plotting SED

### ISSUE THREAD

**Issue by TarekHC** [fermiPy/fermipy#185]
I found an annoying error while running "gta.sed". I reproduce it many times while trying to draw the SED of a log parabola fit of faint sources. 

First, the fit (and later on the SED drawing) show warnings of "Failed to create spline", e.g.

```python
Failed to create spline:  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.] [  1.45530720e+18   1.45530720e+18   1.45530720e+18   1.45530720e+18
   1.45530720e+18   1.45530720e+18   1.45530720e+18   1.45530720e+18
   1.45530720e+18   1.45530720e+18   1.45530720e+18   1.45530720e+18
   1.45530720e+18   1.45530720e+18   1.45530720e+18   1.45530720e+18
   1.45530720e+18   1.45530720e+18   1.45530720e+18   1.45530720e+18
   1.45530720e+18]
```

And finally the error when calling the "make_sed_plots" function:

```python
Traceback (most recent call last):
  File "run_LP.py", line 84, in <module>
    gta.sed(new_source_name)
  File "[PATH-TO-LIB]/python2.7/site-packages/fermipy/sed.py", line 108, in sed
    self._plotter.make_sed_plots(o, **config)
  File "[PATH-TO-LIB]/python2.7/site-packages/fermipy/plotting.py", line 1256, in make_sed_plots
    p.plot()
  File "[PATH-TO-LIB]/python2.7/site-packages/fermipy/plotting.py", line 865, in plot
    return SEDPlotter.plot_sed(self.sed, showlnl, **kwargs)
  File "[PATH-TO-LIB]/python2.7/site-packages/fermipy/plotting.py", line 848, in plot_sed
    SEDPlotter.plot_flux_points(sed, **kwargs)
  File "[PATH-TO-LIB]/python2.7/site-packages/fermipy/plotting.py", line 770, in plot_flux_points
    ax.set_ylim(10 ** fmin, 10 ** fmax)
  File "[PATH-TO-LIB]/python2.7/site-packages/matplotlib/axes/_base.py", line 3225, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "[PATH-TO-LIB]/python2.7/site-packages/matplotlib/axes/_base.py", line 2836, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

The configuration:

```python
'SpectrumType': 'LogParabola',
 'config': {'bin_index': 2.0,
  'cov_scale': 3.0,
  'free_background': False,
  'free_pars': [],
  'free_radius': None,
  'loge_bins': [],
  'make_plots': True,
  'optimizer': {'init_lambda': 0.0001,
   'max_iter': 100,
   'min_fit_quality': 2,
   'optimizer': 'MINUIT',
   'retries': 3,
   'tol': 0.001,
   'verbosity': 0},
  'outfile': None,
  'prefix': '',
  'ul_confidence': 0.95,
  'use_local_index': True,
  'write_fits': True,
  'write_npy': True}
```

I am aware that fitting a log parabola to such a faint source is not a good idea... But shouldn't the error be handled differently? (calculating upper limits?) 

I think the error never happened for a powerlaw fit (but many times for a LP). Any idea where the problem might be?

**Comment by woodmd** [comment]
If you share a tarball of your analysis directory I can try to debug this further.  I recently was encountering similar issues and made some changes to improve the robustness of the SED and likelihood scanning algorithms in #175.  What version of fermipy are you using?  You might give the development version a try to see if it resolves this issue.  

The core problem is that MINUIT sometimes does not converge (e.g. especially when the source is very faint).  Because the likelihood scanning algorithm assumes that the current parameter value is already at the maximum of the likelihood function when the fit fails to converge the resulting likelihood scan does not encompass the peak.

**Comment by TarekHC** [comment]
Hi @woodmd, thank you for the help!

I uploaded an example tarball and log file here. Let me know if you need anything else. 
https://www.dropbox.com/sh/6ck6h0lltf7u6tx/AABMd2HcRRgwez3HxP1agPgQa?dl=0

> What version of fermipy are you using? You might give the development version a try to see if it resolves this issue.

I first tried with the latest release, and then also tested the dev version. Same result.

> The core problem is that MINUIT sometimes does not converge (e.g. especially when the source is very faint). Because the likelihood scanning algorithm assumes that the current parameter value is already at the maximum of the likelihood function when the fit fails to converge the resulting likelihood scan does not encompass the peak.

And the fact that the error only happens with the logparabola model at the plotting stage? If the problem is caused by MINUIT not converging, shouldn't it also occur for PL fits? It should be less likely, but should also occur, no?

**Comment by TarekHC** [comment]
Hi @woodmd , 

Just a quick update. I just found the same error while fitting a powerlaw, so indeed the problem is not only related to the log parabola model. I'm actually fitting PG1553, so it does not happen only to faint sources... So essentially the title of the issue is terribly wrong! :) (fixed)

**Comment by dimauromattia** [comment]
Hi, 
Are you finding this error in fitting a particular source? Is it PG1553? 
I am trying to run your analysis but I probably need the file /lustre/fs19/group/cta/users/thassan/LAT/3FHL/gll_psch_v12.xml .

**Comment by TarekHC** [comment]
>  I am trying to run your analysis but I probably need the file /lustre/fs19/group/cta/users/thassan/LAT/3FHL/gll_psch_v12.xml .

Sorry I took my time... That file is the 3FHL catalog in xml format. You can find it here:
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3FHL/gll_psch_v12.xml

Thank you @dimauromattia !!
