### ISSUE TITLE
SpatialTemplate

### ISSUE THREAD

**Issue by Fdepalma** [fermiPy/fermipy#188]
From the documentation http://fermipy.readthedocs.io/en/latest/model.html#editing-the-model-at-runtime
the name of the model for using a Spatial template is:
SpatialTemplate

but I got this error:
Exception: Invalid Function Name: SpatialTemplate

Inspecting the code I find out that the extended model might be called as SpatialMap, from a first test this seems to work fine.

Is it possible that the guide is not up to date?
I'm using:
fermipy version 0.16.0+94.ga062 
ScienceTools version ScienceTools-11-07-00

Regards
Francesco

**Comment by dimauromattia** [comment]
Hi @Fdepalma,

The correct name for the model SpatiaTemplate is SpatialMap. We will fix this error in the documentation.

Regards.

Mattia

**Comment by dimauromattia** [comment]
Hi @Fdepalma We have corrected this issue in the documentation page. See: http://fermipy.readthedocs.io/en/latest/model.html.
Best Mattia

**Comment by dimauromattia** [comment]
Hi @Fdepalma, Can you close the issue if you think it is solved?
