### ISSUE TITLE
make_plots=True with gta.write_roi

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#189]
I find this error when I use the make_plots=True option in gta.write_roi function.
I am using:
fermipy version 0.16.0+118.g7c11.dirty 
ScienceTools version ScienceTools-11-05-03
This is the error:
In [9]: gta.write_roi('fit0_ext',make_plots=True,save_model_map=True)
2018-02-19 10:41:14 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/slac/kipac/fs1/u/mdimauro/workdir/fermipytutorial/SMC/fit0_ext_00.xml...
2018-02-19 10:41:14 INFO    GTAnalysis.write_fits(): Writing /nfs/slac/kipac/fs1/u/mdimauro/workdir/fermipytutorial/SMC/fit0_ext.fits...
2018-02-19 10:41:16 INFO    GTBinnedAnalysis.write_model_map(): Generating model map for component 00.
2018-02-19 10:41:18 INFO    GTAnalysis.write_roi(): Writing /nfs/slac/kipac/fs1/u/mdimauro/workdir/fermipytutorial/SMC/fit0_ext.npy...
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-9-6963c915e680> in <module>()
----> 1 gta.write_roi('fit0_ext',make_plots=True,save_model_map=True)

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.pyc in write_roi(self, outfile, save_model_map, **kwargs)
   3687         if make_plots:
   3688             self.make_plots(prefix, None,
-> 3689                             **kwargs.get('plotting', {}))
   3690 
   3691     def write_fits(self, fitsfile):

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.pyc in make_plots(self, prefix, mcube_map, **kwargs)
   3762                                            fileio=self.config['fileio'],
   3763                                            logging=self.config['logging'])
-> 3764         plotter.run(self, mcube_map, prefix=prefix, **kwargs)
   3765 
   3766     def curvature(self, name, **kwargs):

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/plotting.pyc in run(self, gta, mcube_map, **kwargs)
    978         for x in loge_bounds:
    979             self.make_roi_plots(gta, mcube_map, loge_bounds=x,
--> 980                                 **kwargs)
    981 
    982         imfile = utils.format_filename(self.config['fileio']['workdir'],

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/plotting.pyc in make_roi_plots(self, gta, mcube_map, **kwargs)
   1262             model_data = mcube_map.counts.T
   1263             diffuse_data = mcube_diffuse.counts.T
-> 1264             weight_data = wmap.counts.T
   1265             xmin = -1
   1266             xmax = 1

UnboundLocalError: local variable 'wmap' referenced before assignment

**Comment by woodmd** [comment]
This is a bug that was introduced when merging in some of @eacharles recent changes.  I'll try to have a look at it today.
