### ISSUE TITLE
sh: dmpipe-calc-sed-limits: command not found

### ISSUE THREAD

**Issue by xihou** [fermiPy/fermipy#195]
Hi,

I successfully installed the develop version of dmpipe following the procedure in https://github.com/fermiPy/dmpipe, but the code does not work when calling the "dmpipe-calc-sed-limits" function to convert sed UL to sigmav UL. Sometimes it worked in my SLAC home directory, not the work directory, and seems that it also depends on the installation procedure of fermipy: whether you install first the tagged version then the develop version, or directly install the develop version only.

Thanks!
Xian

**Comment by woodmd** [comment]
Sometimes python package links can get out of sync when you switch between development and tagged package versions within the same environment.  This is one reason it's generally better to always work in a separate conda environment for each software version you want to test.  To clean your old installations of dmpipe try running `pip uninstall dmpipe` repeatedly until it says dmpipe is no longer installed.  Then reinstall the version you want, e.g. with `python setup.py install`.

**Comment by xihou** [comment]
Hi, I have installed a conda version, and the problem is solved. 
Thanks!
