### ISSUE TITLE
No module named gammapy.maps

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#196]
I have just checkout to the latest version (0.16.0+157.g8552) and when I do from fermipy.gtanalysis import GTAnalysis it says:
from fermipy import utils
utils.init_matplotlib_backend()
from fermipy.gtanalysis import GTAnalysis
import argparse
import numpy as np
from fermipy.castro import CastroData

## -- End pasted text --
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-817cb732a428> in <module>()
      5 from fermipy import utils
      6 utils.init_matplotlib_backend()
----> 7 from fermipy.gtanalysis import GTAnalysis
      8 import argparse
      9 import numpy as np

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in <module>()
     13 from astropy.io import fits
     14 from astropy.table import Table, Column, vstack
---> 15 from gammapy.maps import Map, HpxGeom, WcsGeom, MapAxis, WcsNDMap, HpxNDMap
     16 import fermipy
     17 import fermipy.defaults as defaults

ImportError: No module named gammapy.maps

I checked that this error is generated by the commit fde4e7008b84df5696507bd5f2968b98a9f8d7ad where we switched to gammapy conda packages and added gammapy dependences.

**Comment by woodmd** [comment]
I forgot to include `gammapy` in the `setup.py` dependencies.  I'll make a PR to fix this but in the meantime you can resolve this error by installing gammapy yourself with `conda install gammapy`.

**Comment by dimauromattia** [comment]
Yes I confirm that we the last commit this issue is solved.
