### ISSUE TITLE
Mechanism to fix or remove weak sources

### ISSUE THREAD

**Issue by woodmd** [fermiPy/fermipy#2]
Currently there is no simple way to ignore weak sources in the likelihood fit which can issues with fit convergence in crowded ROIs.  The proposed functionality would be one or more functions that would automatically free or remove low TS sources from the ROI.

**Comment by terrijb** [comment]
Thanks for adding the ability to fix sources via min_ts and min_npred options in free_sources() Matthew! 

In addition, having the option to remove those below min_ts or min_npred in delete_source() would also be useful in a variety of situations involving complex regions and/or using data sets different from initial starting catalogs (eg in energy range or time). Not/having low significance sources can also affect an extension measurement.

**Comment by woodmd** [comment]
This functionality is now implemented since several releases ago.  Note that the options for selecting sources on TS and Npred are now called `minmax_ts` and `minmax_npred`.  These can be used to define an open or closed interval for the selection.  For instance calling `delete_sources(minmax_ts=[None,10])` will delete all sources with TS < 10 while `free_sources(minmax_ts=[10,None])` will free sources with TS > 10.

**Comment by terrijb** [comment]
Super, thanks!
