### ISSUE TITLE
Fermi ScienceTools conda package

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#20]
We've talked a bit about it in #16, but I wanted to make a separate issue for this.

What's the status on building Fermi ScienceTools conda packages for Linux and Mac?
We're agreed that it would be good to have those, right?
Has anyone tried to build them or plans to do so?

I'm at the [PyAstro16](http://python-in-astronomy.github.io/2016/) conference this coming week, and there might be opportunities to work on this with people that know conda very well.

cc @woodmd @kialio

**Comment by woodmd** [comment]
I think having conda packages for the ScienceTools is still a long-term goal but there are several obstacles that will needs to be overcome before that happens.  NASA already has a well-established model for building and distributing software and there will necessarily be some resistance to making any changes to that model.  One concern is about the potential licensing issues related to tying the STs to a commercial product (i.e. anaconda python).  I don't know enough about the anaconda licensing model to know if this is a real concern or not.  Given the large number of open source projects that are using conda for distribution I would guess that this shouldn't be an issue but it would be useful if you could point us to some documentation on this point.

We're currently in discussions with the FSSC software team about moving to ST builds that could be used with anaconda python or the user's existing system python.  Once we have that working I think the next logical step would be to put together ST conda builds but it's not clear if NASA would be able to directly support these.  Even if NASA doesn't want to support conda packages we might be able to find people within the LAT collaboration who could support them.  

One technical issue is related to building cross-platform Linux binaries.  Currently we build a separate ST binary for each Linux platform to account for differences in GLIBC versions.  Looking through the conda documentation it wasn't immediately clear how conda handles Linux dependencies.  Does it have a way of detecting the version of Linux and installing the appropriate binary?  I think this is where having some input from conda experts could be useful.

**Comment by cdeil** [comment]
I don't see why there would be any concerns with conda / anaconda licensing.
conda is a package manager  and anaconda a package server and independent of licensing of the ST source code or binary packages.

The conda packages would be something that has to be built and distributed in addition to what FSSC is doing now. If someone from NASA or the LAT collaboration is willing to do it, that would be great!
Please post updates here.

My understanding is that with conda only build one Linux package, which then works for most people.
The way to do it is something like http://phusion.github.io/holy-build-box/ ... I'm not sure what setup Continuum or others use exactly.

I just learned of https://conda-forge.github.io/ . It looks like this might become the large community-maintained forge of conda packages for things Continuum doesn't build / maintain. So following their instructions and use their setup to try building the ST on Linux and Mac might be good.
Anyone has time for this?

**Comment by woodmd** [comment]
I also don't see that there shouldn't be any issues with licensing but the fact that it is partially a commercial product may still be an issue.  NASA has a very long time horizon when it comes to software support and thus tends to be rather conservative when it comes to making changes to its development or distribution model.  

In any event we'll continue pushing for a ST conda package.  I'm already working with the NASA folks to develop an anaconda-compatible ST build so I'll volunteer myself to work on the conda packaging part as well.  What remains to be seen is the extent to which the FSSC will be willing to support this mode of distribution.  I'll keep you updated on this thread as things progress.

**Comment by woodmd** [comment]
A quick update on this issue -- NASA/FSSC has finally come around to the idea of distributing the ST via conda.  Work is underway on this and I imagine we may have a ST conda package within the next 6 months to a year.  We'll plan to update the fermipy documentation accordingly once this is available.
