### ISSUE TITLE
CompositeSource in FermiPy

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#201]
this may be either a new feature or a feature which if implemented should be documented. A long while ago (Dec 2016) Eric introduced *composite* sources in the Science Tools. Is there an equivalent in FermiPy? If so, we should document this.

**Comment by woodmd** [comment]
There is some support for composite sources in fermipy but it isn't documented at present and I'm not entirely sure that is still works as we don't have any regression tests for this functionality.  It would be great if someone could add a composite source test and update the documentation with some examples (e.g. [here](http://fermipy.readthedocs.io/en/latest/model.html)).
