### ISSUE TITLE
Fermipy installation issues with the new Science Tools ( v11r5p3)

### ISSUE THREAD

**Issue by sonnenblu** [fermiPy/fermipy#211]
Hi,

I had been using the Fermipy package with the ST version (v10r0p5) without any issues on my mac (macOS Sierra v10.12.6). However, after I updated the Fermi ST to the new version (v11r5p3), I am having issues installing Fermipy. When I do "which python", it points to the python under ST. But "which pip" points to /usr/local/bin/pip. So, next I did "curl https://bootstrap.pypa.io/get-pip.py | python -" and that's where the issue starts. I get error as shown below. I tried different ways to download pip and install fermipy, but no luck! I have tried to copy down the exact steps and all the warning/error messages. I would greatly appreciate some help in fixing this issue!

---------------------------------------------------------------------------------
$ curl https://bootstrap.pypa.io/get-pip.py | python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1738k  100 1738k    0     0  2146k      0 --:--:-- --:--:-- --:--:-- 2146k
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
------------------------------------------------------------------------------

Finally, I decided to install the old ST (v10r0p5) and see if the problem persists (because I had fermipy running successfully under this version). With the older version, I was able to get pip successfully (pls see below). So maybe the python under new ST is giving the issue!? 

-------------------------------------------------------------------------------
$ curl https://bootstrap.pypa.io/get-pip.py | python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1738k  100 1738k    0     0  2189k      0 --:--:-- --:--:-- --:--:-- 2187k
Collecting pip
  Using cached pip-9.0.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.2 setuptools-39.0.1 wheel-0.30.0
------------------------------------------------------------------------------

Next, I tried to install fermipy! This seemed successful, but shows a "requirement satisfied" message for scipy and numpy. Is that okay? 

------------------------------------------------------------------------------
$ pip install fermipy
Collecting fermipy
Collecting healpy (from fermipy)
Collecting matplotlib>=1.5.0 (from fermipy)
  Using cached matplotlib-2.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting wcsaxes (from fermipy)
Collecting pyyaml (from fermipy)
Requirement already satisfied: scipy>=0.14 in ./.local/lib/python2.7/site-packages (from fermipy)
Requirement already satisfied: numpy>=1.6.1 in ./.local/lib/python2.7/site-packages (from fermipy)
Collecting astropy>=1.2.1 (from fermipy)
  Using cached astropy-2.0.5-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six (from healpy->fermipy)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib>=1.5.0->fermipy)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Collecting backports.functools-lru-cache (from matplotlib>=1.5.0->fermipy)
  Using cached backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib>=1.5.0->fermipy)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib>=1.5.0->fermipy)
Collecting kiwisolver>=1.0.1 (from matplotlib>=1.5.0->fermipy)
  Using cached kiwisolver-1.0.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib>=1.5.0->fermipy)
  Using cached python_dateutil-2.7.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=1.5.0->fermipy)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pytest>=2.8 (from astropy>=1.2.1->fermipy)
  Using cached pytest-3.4.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./sw2016/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.0->fermipy)
Collecting py>=1.5.0 (from pytest>=2.8->astropy>=1.2.1->fermipy)
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting attrs>=17.2.0 (from pytest>=2.8->astropy>=1.2.1->fermipy)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest>=2.8->astropy>=1.2.1->fermipy)
Collecting funcsigs; python_version < "3.0" (from pytest>=2.8->astropy>=1.2.1->fermipy)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Installing collected packages: six, pytz, backports.functools-lru-cache, cycler, subprocess32, kiwisolver, python-dateutil, pyparsing, matplotlib, py, attrs, pluggy, funcsigs, pytest, astropy, healpy, wcsaxes, pyyaml, fermipy
  Found existing installation: matplotlib 1.1.1
    DEPRECATION: Uninstalling a distutils installed project (matplotlib) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling matplotlib-1.1.1:
      Successfully uninstalled matplotlib-1.1.1
Successfully installed astropy-2.0.5 attrs-17.4.0 backports.functools-lru-cache-1.5 cycler-0.10.0 fermipy-0.16.0 funcsigs-1.0.2 healpy-1.11.0 kiwisolver-1.0.1 matplotlib-2.2.2 pluggy-0.6.0 py-1.5.2 pyparsing-2.2.0 pytest-3.4.2 python-dateutil-2.7.0 pytz-2018.3 pyyaml-3.12 six-1.11.0 subprocess32-3.2.7 wcsaxes-0.9
----------------------------------------------------------------

Installing jupyter notebook next! But again, I am getting this "Requirement already satisfied" message. I thought it was alright, but when I tried to open the jupyter notebook from the ST to run fermipy, I get the error as '$ -bash: jupyter: command not found'. I also tried a forced upgrade, but still getting the same warning message. I am not sure how to fix this issue. I am really stuck and cannot do my analysis anymore. 

--------------------------------------------------------------------
$ pip install jupyter
Requirement already satisfied: jupyter in ./.local/lib/python2.7/site-packages
Requirement already satisfied: nbconvert in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: notebook in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: jupyter-console in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: ipykernel in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: ipywidgets in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: qtconsole in ./.local/lib/python2.7/site-packages (from jupyter)
Requirement already satisfied: jinja2 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: pygments in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: nbformat>=4.4 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: mistune>=0.7.4 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: traitlets>=4.2 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: entrypoints>=0.2.2 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: testpath in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: bleach in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: jupyter-core in ./.local/lib/python2.7/site-packages (from nbconvert->jupyter)
Requirement already satisfied: terminado>=0.8.1 in ./.local/lib/python2.7/site-packages (from notebook->jupyter)
Requirement already satisfied: ipython-genutils in ./.local/lib/python2.7/site-packages (from notebook->jupyter)
Requirement already satisfied: tornado>=4 in ./.local/lib/python2.7/site-packages (from notebook->jupyter)
Requirement already satisfied: jupyter-client>=5.2.0 in ./.local/lib/python2.7/site-packages (from notebook->jupyter)
Requirement already satisfied: Send2Trash in ./.local/lib/python2.7/site-packages (from notebook->jupyter)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.0 in ./.local/lib/python2.7/site-packages (from jupyter-console->jupyter)
Requirement already satisfied: ipython in ./.local/lib/python2.7/site-packages (from jupyter-console->jupyter)
Requirement already satisfied: widgetsnbextension~=3.1.0 in ./.local/lib/python2.7/site-packages (from ipywidgets->jupyter)
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python2.7/site-packages (from jinja2->nbconvert->jupyter)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./.local/lib/python2.7/site-packages (from nbformat>=4.4->nbconvert->jupyter)
Requirement already satisfied: six in ./sw2016/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages (from traitlets>=4.2->nbconvert->jupyter)
Requirement already satisfied: enum34; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from traitlets>=4.2->nbconvert->jupyter)
Requirement already satisfied: decorator in ./.local/lib/python2.7/site-packages (from traitlets>=4.2->nbconvert->jupyter)
Requirement already satisfied: configparser>=3.5; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from entrypoints>=0.2.2->nbconvert->jupyter)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in ./.local/lib/python2.7/site-packages (from bleach->nbconvert->jupyter)
Requirement already satisfied: ptyprocess; os_name != "nt" in ./.local/lib/python2.7/site-packages (from terminado>=0.8.1->notebook->jupyter)
Requirement already satisfied: singledispatch in ./.local/lib/python2.7/site-packages (from tornado>=4->notebook->jupyter)
Requirement already satisfied: futures in ./.local/lib/python2.7/site-packages (from tornado>=4->notebook->jupyter)
Requirement already satisfied: backports-abc>=0.4 in ./.local/lib/python2.7/site-packages (from tornado>=4->notebook->jupyter)
Requirement already satisfied: pyzmq>=13 in ./.local/lib/python2.7/site-packages (from jupyter-client>=5.2.0->notebook->jupyter)
Requirement already satisfied: python-dateutil>=2.1 in ./sw2016/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages (from jupyter-client>=5.2.0->notebook->jupyter)
Requirement already satisfied: wcwidth in ./.local/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: simplegeneric>0.8 in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: setuptools>=18.5 in ./sw2016/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: pickleshare in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./.local/lib/python2.7/site-packages (from ipython->jupyter-console->jupyter)
Requirement already satisfied: functools32; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert->jupyter)
Requirement already satisfied: webencodings in ./.local/lib/python2.7/site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->jupyter)
Requirement already satisfied: scandir; python_version < "3.5" in ./.local/lib/python2.7/site-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->jupyter-console->jupyter)
-----------------------------------------------------------------------

Thanks for reading this issue and I would appreciate some help to get the fermipy installed with the new ST or the jupyter notebook issue with the older version of ST.

**Comment by dimauromattia** [comment]
Hi @sonnenblu ,
Why did you install fermipy after you updated the STs? It would have been enough to update Fermipy probably. The fact that when you do "which pip" you have /usr/local/bin/pip something went wrong in the installation. What I would suggest is to uninstall Fermipy and the Science Tools and start again from the beginning. You can follow the documentation page: http://fermipy.readthedocs.io/en/latest/install.html.

**Comment by sonnenblu** [comment]
I had to install fermipy again because fermipy was not running with the new ST. I had uninstalled and installed new science tools, fermipy, old science tools several times. When I couldn't resolve the issue, I thought of posting it here. As I had explained very well above, the pip will give me SSL error with the new ST, but won't with the old ST. When I reinstalled the older ST, I can get the pip and fermipy running, but not jupyter notebook anymore. I followed the documentation exactly as it is..

**Comment by woodmd** [comment]
I'm afraid that installation of fermipy+ST has always been a bit fragile under OSX.  This is one reason that the Fermi team is migrating soon to a conda-based solution for distributing the STs.  This should work much more reliably than the pip-based installation method.  In the meantime if you want to run newer ST releases under OSX you could also try following the docker-based installation instructions.
