### ISSUE TITLE
ImportError: libtinfo.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#214]
How can I solve this error?
Traceback (most recent call last):
  File "../../../script/run.py", line 4, in <module>
    from fermipy.gtanalysis import GTAnalysis
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 21, in <module>
    import fermipy.gtutils as gtutils
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/fermipy/gtutils.py", line 6, in <module>
    import pyLikelihood as pyLike
  File "/home/ubuntu/ScienceTools/libc/lib/python/pyLikelihood.py", line 7, in <module>
    import lib_pyLikelihood
ImportError: libtinfo.so.6: cannot open shared object file: No such file or directory

**Comment by giacomov** [comment]
Hi,
this might solve your problem: from the error message it looks like you have fermipy installed on a miniconda installation, while the Science Tools are installed in another python (the one that comes with the ST). This can cause problems.

Try installing fermipy in the same python that comes with the ST:
* make sure that your `PATH` env. variable does not contain `/home/ubuntu/miniconda/bin` or any other conda-related path
* install `fermipy` using `pip`: `pip install fermipy`

try again. If that doesn't solve your problem, please report back.

Cheers,

**Comment by dimauromattia** [comment]
Hi @imereu,
Did you try to follow @giacomov suggestion? Is the error fixed?
Cheers

**Comment by imereu** [comment]
Yes is fixed.
