### ISSUE TITLE
Multicore processing

### ISSUE THREAD

**Issue by astro-fermi** [fermiPy/fermipy#22]
Hello,

Does fermipy supports multi-processing to speed up the LAT data reduction (especially time consuming steps like ltcube, expmap generation and diffuse response calculation)?

Thanks.

**Comment by woodmd** [comment]
No this currently is not supported.  @kialio wrote a set of nice utilities for this so it's been on my to-do list to add the option to use these in fermipy.  We'll use this issue to track this as a feature request.

**Comment by cameronrulten** [comment]
Hi @woodmd, is there any update on the status of this feature request?

**Comment by woodmd** [comment]
Some of the API methods have multicore support (e.g. `tsmap` and `lightcurve`) but at the moment we are lacking still lacking this for the preprocessing steps.  Note that you can speed up the LT cube generation (which is generally the slowest part of the preprocessing by far) by setting `ltcube.use_local_ltcube : True` in the configuration file.  This uses a pure-python implementation of the LT calculation that is roughly ~10-100x faster than gtltcube.
