### ISSUE TITLE
Contours not coincident - gta.residmap()

### ISSUE THREAD

**Issue by marti-devesa** [fermiPy/fermipy#220]
Hi, 
For fermipy version 0.16.0+179.g1a8e, when using gta.residmap(the make_plots=True) function, in the significance map the contours do not match with the significances (neither using GAL or CEL coordinates).

It seems just a rotation around the diagonal of the plot.
Is that known?
Thanks

**Comment by jefemagril** [comment]
I fixed this in PR #216

**Comment by marti-devesa** [comment]
Oh okey, thanks
