### ISSUE TITLE
error in gta.write_roi output file

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#222]
If I use gta.write_roi() the program records a file.fits in which the errors on ra and dec are not the same ones reported in the file.fits obtained from gta.localize() but they coincide with glat_err and with glon_err.

**Comment by dimauromattia** [comment]
Hi @imereu, thanks for pointing out this error. I checked and indeed I found the same error. I will make a PR with a fix to this issue.

**Comment by zimmerst** [comment]
this should be fixed as per #225 Thanks for reporting to @imereu and @dimauromattia for fixing.
