### ISSUE TITLE
improve plotting of *Plotter objects - support for axis

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#226]
following the draco example https://github.com/fermiPy/fermipy-extra/blob/master/notebooks/draco.ipynb, I played with the `SEDPlotter`. I usually use matplotlib creating the axes & figures a priori and filling the content afterwards (by looping through axes iteratively). So I'd like to do something like:

```
seds = [list of 10 seds]
fig, axes = plt.subplots(ncols=2,nrows=5,figsize=(20,6), sharex=True)
for i, ax in enumerate(axes.flatten):
 SEDPlotter(seds[i]).plot()
```
which in the current implementation however will always use `plt.gca()`; It'd be great if there was kwargs support in which the user can do something like `SEDPlotter(seds[i]).plot(ax=ax)` and only if ax=None, it should fall back to plt.gca()

**Comment by omodei** [comment]
You can pass "ax" as keyword in SEDPlotter.plot_flux_points method. [here the code you might want to look](https://github.com/fermiPy/fermipy/blob/fbd4c95ffadbff31cbb9cc862ff84a78dc734ef5/fermipy/plotting.py#L745)
