### ISSUE TITLE
Bug: Locked params not saved with write_roi()

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#234]
The expected behavior is that the list of currently locked parameters will be saved in the npy file upon calling `GTAnalysis.write_roi()` and then later loaded again by `GTAnalysis.create()`. However, this does not happen.

**Comment by zimmerst** [comment]
@jefemagril could you please clarify this? I would have assumed that GTAnalysis.load_roi() should be the method to re-load an npy-representation of the ROI you have written before.

**Comment by jefemagril** [comment]
I'm referring to this functionality:
https://fermipy.readthedocs.io/en/latest/fermipy.html#fermipy.gtanalysis.GTAnalysis.lock_parameter
The locked parameter states are not saved by `write_roi()` or loaded with `load_roi()`.

**Comment by eacharles** [comment]
I think that this is fixed with branch fermipy-234, this will be in release 0.19.1
