### ISSUE TITLE
issue with the installation of fermipy on macOS high sierra

### ISSUE THREAD

**Issue by esayaso** [fermiPy/fermipy#239]
Hello everyone,

I get the following error message when I try to install fermipy on a macOS high sierra:
-------------------------------------------------------------------------------------
                   from healpy/src/_sphtools.cpp:499:
  /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  healpy/src/_sphtools.cpp:521:26: fatal error: weight_utils.h: No such file or directory
   #include "weight_utils.h"
                            ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for healpy
  Running setup.py clean for healpy
Failed to build healpy
Installing collected packages: matplotlib, healpy, pyyaml, regions, click, gammapy, fermipy
  Found existing installation: matplotlib 1.2.1
Cannot uninstall 'matplotlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

----------------------------------------------------------------------------------------

Someone had faced similar problem and can help me with it?

Thank you in advance!

Estrella

**Comment by dimauromattia** [comment]
Hello @esayaso can you give more infos on how you tried to install Fermipy? Did you used the github repository, conda, pip? Can you check which python are you using making which python?

**Comment by esayaso** [comment]
Hello @dimauromattia,

This is what I get when I try to install it with pip:
---------------------------------------------------------------------------------
MacBook-Pro-de-Estrella:~ estrella$ which python
/usr/local/bin/python
MacBook-Pro-de-Estrella:~ estrella$ fermi
MacBook-Pro-de-Estrella:~ estrella$ which python
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/bin/python
MacBook-Pro-de-Estrella:~ estrella$ curl https://bootstrap.pypa.io/get-pip.py | python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1603k  100 1603k    0     0  1040k      0  0:00:01  0:00:01 --:--:-- 1040k
Collecting pip
/var/folders/x7/c4ctcpjs2mb3d59s4tcwkntw0000gn/T/tmpMzFmu6/pip.zip/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/var/folders/x7/c4ctcpjs2mb3d59s4tcwkntw0000gn/T/tmpMzFmu6/pip.zip/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-10.0.1
MacBook-Pro-de-Estrella:~ estrella$ which pip
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/bin/pip
MacBook-Pro-de-Estrella:~ estrella$ pip install fermipy
Collecting fermipy
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Collecting healpy (from fermipy)
  Using cached https://files.pythonhosted.org/packages/57/a8/d96f274e3f71763ddc31a2eace228ab682957284ad505948fde447b704a6/healpy-1.12.3.tar.gz
Collecting matplotlib>=1.5.0 (from fermipy)
  Using cached https://files.pythonhosted.org/packages/61/38/d70e8bf77d5cb27d5f3595edd0b3978825063feadd023786d2591e393e6e/matplotlib-2.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyyaml (from fermipy)
Requirement already satisfied: scipy>=0.14 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from fermipy) (0.14.0)
Collecting gammapy (from fermipy)
Requirement already satisfied: numpy>=1.6.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from fermipy) (1.9.1)
Requirement already satisfied: astropy>=1.2.1 in ./.local/lib/python2.7/site-packages (from fermipy) (2.0.7)
Requirement already satisfied: six in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from healpy->fermipy) (1.11.0)
Requirement already satisfied: pytz in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2018.5)
Requirement already satisfied: backports.functools-lru-cache in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (1.5)
Requirement already satisfied: cycler>=0.10 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (0.10.0)
Requirement already satisfied: subprocess32 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (3.5.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2.7.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2.2.0)
Collecting regions (from gammapy->fermipy)
Collecting click (from gammapy->fermipy)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Requirement already satisfied: pytest>=2.8 in ./.local/lib/python2.7/site-packages (from astropy>=1.2.1->fermipy) (3.6.2)
Requirement already satisfied: setuptools in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.0->fermipy) (40.0.0)
Requirement already satisfied: py>=1.5.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.5.4)
Requirement already satisfied: more-itertools>=4.0.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (4.2.0)
Requirement already satisfied: atomicwrites>=1.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.1.5)
Requirement already satisfied: pluggy<0.7,>=0.5 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (0.6.0)
Requirement already satisfied: funcsigs; python_version < "3.0" in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.0.2)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (18.1.0)
Building wheels for collected packages: healpy
  Running setup.py bdist_wheel for healpy ... error
  Complete output from command /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x7/c4ctcpjs2mb3d59s4tcwkntw0000gn/T/pip-install-DXBNzv/healpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/x7/c4ctcpjs2mb3d59s4tcwkntw0000gn/T/pip-wheel-evbghs --python-tag cp27:
  /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'cython_directives'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-x86_64-2.7
  creating build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/pixelfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/sphtfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/visufunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/fitsfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/projector.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/rotator.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/projaxes.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/version.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/zoomtool.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/cookbook.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  copying healpy/newvisufunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy
  creating build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_pixelweights.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_query_disc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/conftest.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_visufunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_fitsfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_rotator.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_pixelfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_spinfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  copying healpy/test/test_sphtfunc.py -> build/lib.macosx-10.12-x86_64-2.7/healpy/test
  creating build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0016.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0128.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0256.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n4096.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00512.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00256.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n04096.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00128.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00016.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0512.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0032.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00002.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0008.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0004.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n02048.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n08192.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n1024.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0064.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00008.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n0002.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00032.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00004.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n2048.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/pixel_window_n8192.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n00064.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/weight_ring_n01024.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  copying healpy/data/totcls.dat -> build/lib.macosx-10.12-x86_64-2.7/healpy/data
  creating build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/gaussbeam_10arcmin_lmax512_pol.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_smoothed10deg_fortran.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_WVxspec_v4_udgraded32_II_lmax64_rmmono_3iter.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_V_v4_udgraded32_masked.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_II_lmax64_rmmono_3iter.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_II_lmax64_rmmono_3iter_nomask.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_masked_smoothed10deg_fortran.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/map_synfast_seed12345.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_masked.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_IQU_lmax64_rmmono_3iter.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_band_iqumap_r9_7yr_V_v4_udgraded32.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/wmap_temperature_analysis_mask_r9_7yr_v4_udgraded32.fits -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  copying healpy/test/data/justq_gal2ecl.fits.gz -> build/lib.macosx-10.12-x86_64-2.7/healpy/test/data
  running build_clib
  checking if configure script for library 'cfitsio' exists
  checking if configure script for library 'healpix_cxx' exists
  checking if library 'cfitsio' is installed
  found 'cfitsio' installed, using it
  checking if library 'healpix_cxx' is installed
  found 'healpix_cxx' installed, using it
  running build_ext
  building 'healpy._healpy_pixel_lib' extension
  creating build/temp.macosx-10.12-x86_64-2.7
  creating build/temp.macosx-10.12-x86_64-2.7/healpy
  creating build/temp.macosx-10.12-x86_64-2.7/healpy/src
  /usr/local/Cellar/gcc/8.1.0/bin/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/include -I/opt/local/include/healpix_cxx -I/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/include/python2.7 -I/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include -c healpy/src/_healpy_pixel_lib.cc -o build/temp.macosx-10.12-x86_64-2.7/healpy/src/_healpy_pixel_lib.o -fopenmp
  unable to execute '/usr/local/Cellar/gcc/8.1.0/bin/': Permission denied
  error: command '/usr/local/Cellar/gcc/8.1.0/bin/' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for healpy
  Running setup.py clean for healpy
Failed to build healpy
Installing collected packages: matplotlib, healpy, pyyaml, regions, click, gammapy, fermipy
  Found existing installation: matplotlib 1.2.1
Cannot uninstall 'matplotlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
MacBook-Pro-de-Estrella:~ estrella$ 

-------------------------------------------------------------------------------

Thanks for your help!!!

Estrella

**Comment by esayaso** [comment]
If I try it with sudo I get:
-------------------------------------------------------------------
MacBook-Pro-de-Estrella:~ estrella$ sudo pip install fermipy
Password:
The directory '/Users/estrella/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/estrella/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting fermipy
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Collecting matplotlib>=1.5.0 (from fermipy)
/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/61/38/d70e8bf77d5cb27d5f3595edd0b3978825063feadd023786d2591e393e6e/matplotlib-2.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.7MB)
    100% |████████████████████████████████| 13.7MB 3.0MB/s 
Collecting healpy (from fermipy)
  Downloading https://files.pythonhosted.org/packages/57/a8/d96f274e3f71763ddc31a2eace228ab682957284ad505948fde447b704a6/healpy-1.12.3.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.2MB 10.6MB/s 
Requirement already satisfied: astropy>=1.2.1 in ./.local/lib/python2.7/site-packages (from fermipy) (2.0.7)
Requirement already satisfied: numpy>=1.6.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from fermipy) (1.9.1)
Collecting gammapy (from fermipy)
Requirement already satisfied: scipy>=0.14 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from fermipy) (0.14.0)
Collecting pyyaml (from fermipy)
Requirement already satisfied: kiwisolver>=1.0.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (0.10.0)
Requirement already satisfied: subprocess32 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (3.5.2)
Requirement already satisfied: pytz in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2018.5)
Requirement already satisfied: six>=1.10 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (1.11.0)
Requirement already satisfied: backports.functools-lru-cache in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (1.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from matplotlib>=1.5.0->fermipy) (2.7.3)
Requirement already satisfied: pytest>=2.8 in ./.local/lib/python2.7/site-packages (from astropy>=1.2.1->fermipy) (3.6.2)
Collecting click (from gammapy->fermipy)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 18.2MB/s 
Collecting regions (from gammapy->fermipy)
Requirement already satisfied: setuptools in /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.0->fermipy) (40.0.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (0.6.0)
Requirement already satisfied: atomicwrites>=1.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.1.5)
Requirement already satisfied: more-itertools>=4.0.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (4.2.0)
Requirement already satisfied: py>=1.5.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.5.4)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (18.1.0)
Requirement already satisfied: funcsigs; python_version < "3.0" in ./.local/lib/python2.7/site-packages (from pytest>=2.8->astropy>=1.2.1->fermipy) (1.0.2)
Installing collected packages: matplotlib, healpy, click, regions, gammapy, pyyaml, fermipy
  Found existing installation: matplotlib 1.2.1
Cannot uninstall 'matplotlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
MacBook-Pro-de-Estrella:~ estrella$ 

-------------------------------------------

Thank you!

Estrella

**Comment by esayaso** [comment]
Hello @dimauromattia, 

I have solved the problem with MatplotLib: "pip install fermipy" could not uninstall matplotlib, also I could not do "pip uninstall matplotlib". Finally, I have solved the problem uninstalling "matplotlib" by deleting it manually.

My problem now is following the same that I posted firstly, the library GCC fails with the file "weight_utils.h". I get the following:

----------------------------------------------------------------------

building 'healpy._sphtools' extension
    gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/include -I/opt/local/include/healpix_cxx -I/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/include/python2.7 -I/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include -c healpy/src/_sphtools.cpp -o build/temp.macosx-10.12-x86_64-2.7/healpy/src/_sphtools.o -fopenmp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                     from /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from healpy/src/_sphtools.cpp:499:
    /Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    healpy/src/_sphtools.cpp:521:26: fatal error: weight_utils.h: No such file or directory
     #include "weight_utils.h"
                              ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Applications/fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-LJQOnV/healpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-geRKgO/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/tmp/pip-install-LJQOnV/healpy/
--------------------------------------------

Thank you in advance for your information,

Estrella
