### ISSUE TITLE
gta.optimize() after removing sources throws error

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#242]
Is this a feature or a bug? 

suppose you have a gta object with an associated roi containing several sources. I can use 
<code>
gta.roi.delete_sources(gta.roi.get_sources_by_name("source_to_delete"))
</code>
but when i now run gta.optimize():
<code>
Exception                                 Traceback (most recent call last)
<ipython-input-39-881ef647cbfd> in <module>()
----> 1 gta.optimize()

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/gtanalysis.pyc in optimize(self, **kwargs)
   2279 
   2280         print ("Joint fit ", joint_norm_fit)
-> 2281         self.fit(loglevel=logging.DEBUG, **config['optimizer'])
   2282         self.free_sources(free=False, loglevel=logging.DEBUG)
   2283 

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/gtanalysis.pyc in fit(self, update, **kwargs)
   2989 
   2990             free_params = self.get_params(True)
-> 2991             self._extract_correlation(o, free_params)
   2992             for name in self.like.sourceNames():
   2993                 freePars = self.get_free_source_params(name)

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/gtanalysis.pyc in _extract_correlation(self, fit_results, free_params)
   3152                 continue
   3153 
-> 3154             src = self.roi[p0['src_name']]
   3155             for j, p1 in enumerate(free_params):
   3156 

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/roi_model.pyc in __getitem__(self, key)
   1320 
   1321     def __getitem__(self, key):
-> 1322         return self.get_source_by_name(key)
   1323 
   1324     def __iter__(self):

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/roi_model.pyc in get_source_by_name(self, name)
   1751 
   1752         """
-> 1753         srcs = self.get_sources_by_name(name)
   1754 
   1755         if len(srcs) == 1:

/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy-0.16.0+179.g1a8e-py2.7.egg/fermipy/roi_model.pyc in get_sources_by_name(self, name)
   1781             return list(self._src_dict[index_name])
   1782         else:
-> 1783             raise Exception('No source matching name: ' + name)
   1784 
   1785     def get_nearby_sources(self, name, distance, min_dist=None,
</code>

**Comment by jefemagril** [comment]
I haven't looked into this closely, but I believe it should work if you use `gta.delete_source("source_to_delete")` or `gta.delete_sources(names=["source_to_delete"])` instead of the way you're doing it.

**Comment by dimauromattia** [comment]
Hi Stephan, I tried to use the function gta.roi.delete_sources(gta.roi.get_sources_by_name("source_to_delete")) and then do a ta.optimize()
and it says that there is no source matching the source I have deleted. I guess that the reason is that it deletes the source only in the list of sources and not also in the source model. I suggest to delete the source as suggested by Jeff with gta.delete_source('name').

**Comment by woodmd** [comment]
You should never call `ROIModel.delete_sources` or `ROIModel.add_sources` on the `ROIModel` object owned by `GTAnalysis` as this will leave the analysis object in an inconsistent state.  Only the methods of `GTAnalysis` should be used for adding/removing sources (these methods already take care of updating the ROI model).  My original intention with the `ROIModel` methods was to give the user the option to construct an `ROIModel` object by hand and pass that to the `GTAnalysis` constructor when creating an analysis instance.  In retrospect it was a poor design choice to expose these as public methods of the `GTAnalysis` interface.

**Comment by zimmerst** [comment]
Just cleaning this thing up. Thanks @woodmd for the clarification. I'm closing this thread.
