### ISSUE TITLE
Problem with ROI optimization

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#246]
I run the following script
```
from fermipy.gtanalysis import GTAnalysis
import os

os.environ['DATADIR']='..'

gta = GTAnalysis('config.yaml')
gta.delete_sources(cuts={'Signif_Avg' : [0, 10]})
gta.setup(overwrite=True)
gta.write_roi('fit0')
gta.optimize()
gta.write_roi('fit1')
```

with the config file

> data:
>   evfile : ft1.txt
>   scfile : ft2.txt
> 
>   binning:
>   roiwidth   : 60.0
>   binsz      : 0.2
>   binsperdec : 8
> 
> lightcurve: 
>   free_background : True
>   free_radius : 7.0
> 
> selection :
>   radius : 30.0
>   emin : 100
>   emax : 300000
>   zmax    : 90
>   evclass : 128
>   evtype  : 3
>   tmin  : 239557483
>   tmax  : 240767084
>   target : '3FGL J0721.9+7120'
> 
> gtlike:
>   edisp : True
>   irfs : 'P8R2_SOURCE_V6'
>   edisp_disable : ['isodiff','galdiff']
> 
> model:
>   src_radius : 50.0
>   galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v06.fits'
>   isodiff  : '$FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_v06.txt'
>   catalogs :
>     - '3FGL'

ROI contains 199 point sources. When it gets to ROI optimization, a warning occurs

> Joint fit  /home/bulat/anaconda3/envs/python2/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:224: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

From this point, nothing happens. I tried `gta.delete_sources(cuts={'Signif_Avg' : [0, 20]})` which left 93 sources, with the same result. `gta.delete_sources(cuts={'Signif_Avg' : [0, 40]})` left 42 point sources, and the code finished successfully. But I see that `cuts={'Signif_Avg' : [0, 40]}` is too restrictive to me. What's wrong with the large number of sources? What should I do to handle, say, a couple of hundreds of them?
I use fermipy 0.17.2.

**Comment by dimauromattia** [comment]
Hi @jeget I see from you configuration file that you are considering an ROI width of 60 degrees with src_radius=50deg. This is a really larger region of interest. Usually we consider for the for search of points sources or point source analysis ROIs of 20x20 degrees. May I ask you what this analysis is designed for?

**Comment by jeget** [comment]
I noticed that even with the warning I mentioned before the calculation doesn't stop because the log file continues to update. Perhaps the issue can be closed unless the warning is an important one and should be addressed.
Regarding your question, @dimauromattia, my analysis is a basic point source analysis, like that described in the [Binned Likelihood Tutorial](https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html) where one sets a selection radius of 30 gedrees for usual likelihood analysis in the range 0.1-500 GeV. (But I need quite a long light curve which makes the computation speed important.) I supposed 'width = 2 * radius'. Hmm, now I think it should be 'width = sqrt(2) * radius'. Which one is correct? [Cicerone](https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Likelihood/Choose_Data.html) says the default ROI radius for 100 MeV is 20 degrees (for unbinned analysis). Does your experience indicate that 20x20 degrees (and 30x30 for source selection) is sufficient for binned likelihood analysis above 100 MeV?

**Comment by dimauromattia** [comment]
The warning comes from Python interpolator and it not a great problem usually. When you perform a fit you have to control the fit quality reported in the end. If the fit quality is 3 it means that the fit was completely successful. From my experience, if you are performing an analysis of a source (with TS>25) that is in the center of the ROI a width of 20deg is sufficient.

**Comment by jeget** [comment]
Ok, thanks for your response!
