### ISSUE TITLE
Files missing in mkn421.tar.gz mentioned in quickstart guide?

### ISSUE THREAD

**Issue by ritabanc** [fermiPy/fermipy#257]
I am resuming Fermi data analysis after a while. I am trying to test if fermipy is working on my machine. In the example tarball there are several files. in the config.yaml file the only line regarding data is the following:
data:
  ltcube : ltcube_239557414_428903014_z090_r180_gti.fits

I am guessing the actual photon and spacecraft files are not included in the tarball. Is that right? Also, in the example config file on the web page the data related lines are:
data:
  evfile : ft1.lst
  scfile : ft2.fits
  ltcube : ltcube.fits

What is this ltcube.fits? Is it the file named ltcube_239557414_428903014_z090_r180_gti.fits given in the tarball? Previously the ltcube used to be generated during the analysis. It is for a given time range. If I want to get light curves, should I not include this? 
Is there a step-by-step example of light curve generation using fermipy?

**Comment by dimauromattia** [comment]
Hi @ritabanc,
regarding the example mkn421 the ltcube is the file ltcube_239557414_428903014_z090_r180_gti.fits and this type of file is for a given time range and zmax. I suggest to follow the notebook SMC if you want a step by step example to perform analysis with Fermipy including using light curve analysis. You can find the data for this example in the /data folder. There are other useful notebooks that provides a step by step examples such as phase_analysis, optimize_model, gtools_customize. I hope that this is useful.

**Comment by ritabanc** [comment]
Thanks. I shall check.

**Comment by ritabanc** [comment]
I am extracting daily and weekly binned light curves of blazars using
commands such as,

lc = gta.lightcurve('sourceA', binsz=86400.*7.0)

It is working fine but sometimes there is a problem. What I understand is
in some daily bins the analysis is failing (may be because of lack of
counts or such) and instead of ignoring that and moving on to the next time
bin, it is stopping and not even writing the results in the corresponding
.npy file or dictionary named lc. As a result the entire time that it took
to run until it stopped abruptly is being wasted. I need to get daily
binned light curves of ~20 blazars and it is quite difficult to achieve
that with such trial and error.
I have two questions: 1. Does this problem seem familiar? Should it do
that, i.e., stop altogether instead of moving on to the next bin?
2. Is there a better way to do what I want to do: Get daily binned lc of
~20 blazars with simple model (all parameters fixed except the
normalization of the target or may be other parameters of the target of the
TS value is high)?
Thank you for your time.

Ritaban.

**Comment by ritabanc** [comment]
I am attaching the fermipy.log file from that directory. At the bottom of
that file I have copied and pasted the output on the terminal that was not
there in the log file. That output spans line 483 to the end (line 5351).
It has quite a few error saying "MINUIT failed with status code 102 fit
quality 2" in some time ranges. I am ok to not have values on some bins but
it should run properly in the other bins. It ran overnight and should have
finished much earlier but did not finish and sort of stopped progressing at
some point. Did not write the .npy file. Strangely although I gave
"save_bin_data=False" it still makes one directory each for every bin and
saves results there. The last few lines in the terminal were the following:
2019-01-29 22:04:18 INFO    lightcurve_395020801_395107201
GTBinnedAnalysis.write_xml(): Writing
/home/rc/Desktop/3c454/test4/lightcurve_395020801_395107201/fit_model_final_00.xml...
2019-01-29 22:04:19 INFO    lightcurve_395020801_395107201
GTAnalysis._process_lc_bin(): Finished time range 395020801 395107201

It just stuck there and did not end or crashed or do anything.
*Is there an easy way to get the fluxes and errors from the saved
directories?*

The commands I used to start the run are the following:

*rc@rc2:~/Desktop/3c454/test1$ source activate fermi*
*rc@rc2:~/Desktop/3c454/test1$ python*
*>>> import matplotlib.pyplot as plt*
*>>> import matplotlib*
*>>> import numpy as np*
*>>> from fermipy.gtanalysis import GTAnalysis*
WARNING: version mismatch between CFITSIO header (v3.43) and linked library
(v3.41).
*>>> gta = GTAnalysis('config.yaml',logging={'verbosity': 3})*
2019-01-25 14:13:16 INFO    GTAnalysis.__init__():
--------------------------------------------------------------------------------
fermipy version 0.17.3
ScienceTools version ScienceTools-11-04-00
WARNING: UnitsWarning: 'photon/cm**2/MeV/s' contains multiple slashes,
which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'photon/cm**2/s' contains multiple slashes, which is
discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'erg/cm**2/s' contains multiple slashes, which is
discouraged by the FITS standard [astropy.units.format.generic]
*>>> matplotlib.interactive(True)*
*>>> gta.setup()*
*>>> time_bins1=np.arange(239587201,239587201+2100*86400,86400)*
*>>> time_bins2=time_bins1.tolist()*
*>>> lc = gta.lightcurve('3C454.3', time_bins=time_bins2, multithread=True,
use_scaled_srcmap=True, save_bin_data=False, shape_ts_threshold=25.0)*

**Comment by dimauromattia** [comment]
Hi @ritabanc,
I do not know why it got stuck in your last run and it is difficult to understand for me with the informations you provided. A useful information from you would be the error message you were getting before. I might have understood why it crashes but I need to know what is exactly the error message you are getting to confirm my hypothesis.
The warning messages "MINUIT failed with status code 102 fit
quality 2" are not a problem.

**Comment by ritabanc** [comment]
I copied most of the output at the bottom of the .log file. But I shall run
a similar thing again and try to save all the output and send to you.
In general, is there any situation where the code will run but not write
the results in a .npy file? Is it possible to make the program write the
information stored in the light curve output dictionary to some file even
if the program does not finish running? Also, is there an easy way to get
the light curve (center of time bin, flux, error, ts value) from the
sub-directories where output is written? All of these are, as you may
guess, to get some results even if the code does not run to the end. That
would help a lot.

**Comment by ritabanc** [comment]
Today, I am running gta.lightcurve to get some light curve with weekly
binning. That has worked well in some sources. However, in this case, it
has sort of stopped. The last few lines in the terminal are:
2019-01-31 13:44:45 INFO    lightcurve_516555814_517160614
GTAnalysis._process_lc_bin(): Finished time range 516555814 517160614
Generating SourceMap for 3FGL J0854.8+2006....................!
Generating SourceMap for 3FGL J0856.5+2057....................!
Generating SourceMap for 3FGL J0902.4+2050....................!
2019-01-31 13:45:00 INFO    lightcurve_537119014_537723814
GTBinnedAnalysis.write_xml(): Writing
/1TB_home/LAT_analysis/oj287_analysis/lightcurve_537119014_537723814/base_00.xml...
Joint fit  ['3FGL J0854.8+2006', '3FGL J0902.4+2050', '3FGL J0910.9+2248']
2019-01-31 13:45:00 INFO    lightcurve_537119014_537723814
GTBinnedAnalysis.write_xml(): Writing
/1TB_home/LAT_analysis/oj287_analysis/lightcurve_537119014_537723814/fit_model_final_00.xml...
2019-01-31 13:45:00 INFO    lightcurve_537119014_537723814
GTAnalysis._process_lc_bin(): Finished time range 537119014 537723814

Now it's 16:35 and it is stuck there.
I am attaching the log files from the directories it writes for individual
time bins (although I have used "*save_bin_data=False").*

**Comment by dimauromattia** [comment]
Hi if you attached something to your message I don not see it.

**Comment by ritabanc** [comment]
[fermipy_logfiles.zip](https://github.com/fermiPy/fermipy/files/2825291/fermipy_logfiles.zip)

**Comment by ritabanc** [comment]
**I am trying to get a weekly binned light curve of the bright blazar 3C 454.3. I am using the following commands:**
>>> import matplotlib.pyplot as plt
>>> import matplotlib
>>> import numpy as np
>>> from fermipy.gtanalysis import GTAnalysis
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> gta = GTAnalysis('config.yaml',logging={'verbosity': 3})
2019-01-25 14:13:16 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.17.3 
ScienceTools version ScienceTools-11-04-00
WARNING: UnitsWarning: 'photon/cm**2/MeV/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'photon/cm**2/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING: UnitsWarning: 'erg/cm**2/s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]

>>> matplotlib.interactive(True)
>>> gta.setup()
>>> lc_weekly = gta.lightcurve('3C454.3',binsz=86400.0*7.0,use_scaled_srcmap=True, save_bin_data=False,shape_ts_threshold=25.0, multithread=True)

**It is running for ~2 hr, producing folders for each time bin (although I have said save_bin_data=False) and everything seems to be going well. Then it gets stuck at some time bin and just stays there. The last few lines of output on the terminal are:**
2019-02-01 18:41:21 INFO    lightcurve_506304001_506908801 GTAnalysis._process_lc_bin(): Finished time range 506304001 506908801
Generating SourceMap for 3FGL J2250.3+1747....................!
Generating SourceMap for 3FGL J2246.2+1547....................!
Generating SourceMap for 3FGL J2254.0+1403....................!
Generating SourceMap for 3FGL J2254.0+1608....................!
Generating SourceMap for 3FGL J2305.8+1658....................!
2019-02-01 18:41:26 INFO    lightcurve_526867201_527472001 GTBinnedAnalysis.write_xml(): Writing /home/rc/Desktop/3c454/test6/lightcurve_526867201_527472001/base_00.xml...
Joint fit  ['3FGL J2254.0+1608', '3FGL J2232.5+1143', '3FGL J2243.9+2021', '3FGL J2250.3+1747', '3FGL J2307.7+1449']
Generating SourceMap for 3FGL J2250.3+1747....................!
Fitting shape 3FGL J2254.0+1608 TS:     96.690
Fitting shape 3FGL J2232.5+1143 TS:     64.061
2019-02-01 18:41:27 INFO    lightcurve_526867201_527472001 GTBinnedAnalysis.write_xml(): Writing /home/rc/Desktop/3c454/test6/lightcurve_526867201_527472001/fit_model_final_00.xml...
2019-02-01 18:41:27 INFO    lightcurve_526867201_527472001 GTAnalysis._process_lc_bin(): Finished time range 526867201 527472001
Generating SourceMap for 3FGL J2246.2+1547....................!
Generating SourceMap for 3FGL J2254.0+1403....................!
Generating SourceMap for 3FGL J2305.8+1658....................!
2019-02-01 18:41:31 INFO    lightcurve_537148801_537753601 GTBinnedAnalysis.write_xml(): Writing /home/rc/Desktop/3c454/test6/lightcurve_537148801_537753601/base_00.xml...
Joint fit  ['3FGL J2254.0+1608', '3FGL J2232.5+1143']
Fitting shape 3FGL J2232.5+1143 TS:   1757.811
Fitting shape 3FGL J2254.0+1608 TS:    399.383
2019-02-01 18:41:32 INFO    lightcurve_537148801_537753601 GTBinnedAnalysis.write_xml(): Writing /home/rc/Desktop/3c454/test6/lightcurve_537148801_537753601/fit_model_final_00.xml...
2019-02-01 18:41:32 INFO    lightcurve_537148801_537753601 GTAnalysis._process_lc_bin(): Finished time range 537148801 537753601

**It seems it has produced some result in the srcmdl_00.xml file in all of the time bins. But it does not produce the lc_weekly dictionary. Although in the log files of individual folders there are lines like "Generating source dict for 3FGL J2254.0+1608".

The main folder does not have a log file. I am attaching log files and src model files from the folders created in some of the time bins.** 
[srcmdl_00.xml.txt](https://github.com/fermiPy/fermipy/files/2827278/srcmdl_00.xml.txt)
[fermipy.log](https://github.com/fermiPy/fermipy/files/2827281/fermipy.log)
[srcmdl_00.xml.txt](https://github.com/fermiPy/fermipy/files/2827282/srcmdl_00.xml.txt)

[fermipy.log](https://github.com/fermiPy/fermipy/files/2827283/fermipy.log)

**Comment by ritabanc** [comment]
I am also attaching a large portion of the terminal output which ends with it stuck at 

[terminal_output.txt](https://github.com/fermiPy/fermipy/files/2827315/terminal_output.txt)
2019-02-01 18:41:32 INFO lightcurve_537148801_537753601 GTAnalysis._process_lc_bin(): Finished time range 537148801 537753601

**Comment by ritabanc** [comment]
ok, I shall try that.

**Comment by dimauromattia** [comment]
Did you try doing what I suggested?

**Comment by ritabanc** [comment]
Thanks for checking. I did try but then I left town for a conference. So I
did not contact you about it. I copied only the lightcurve.py from github
and replaced my existing lightcurve.py with it. Then I ran gta.lightcurve
again along with the usual preliminary steps. But the result was the same.
It got stuck at some time bin. So I did not see any change or improvement.
But I am not sure if just replacing the old lightcurve.py with the one at
github now will do the trick or I need to do something else. Please let me
know.
Again, thanks for checking in and sorry about not reporting back to you.

**Comment by dimauromattia** [comment]
Hi @ritabanc, If you send me the full details of your analysis (IEM and ISO templates that you use, configuration file, source of interest,...) I will try to do the analysis my self and check if and why you find the results.

**Comment by ritabanc** [comment]
ok, I shall do that on Monday. Those are on my office computer and I cannot
access it from home.
