### ISSUE TITLE
Light curve with daily bins

### ISSUE THREAD

**Issue by ritabanc** [fermiPy/fermipy#261]
In a relatively bright source I analysed LAT data to obtain a light curve with weekly bins using fermipy. This ran without any trouble. Some weekly bins had TS value ~0. The flux there are very small and the relative error is very large as it should be. Now I am trying to get a light curve for the same source with daily bins. I get errors like the following:
Analysis failed in time range 442627201 442713601
<type 'exceptions.OSError'
Analysis failed in time range 403488001 403574401
<class 'mmap.error'>, etc.
I assume it is because there is not enough signal in the daily bins. Is there a way to tell the gta.lightcurve process to not find out flux, upper limit or any other result in a bin if the TS value is smaller than some threshold. Just abandon that bin and move on. I do not need those values anyway but it is preventing me from getting a daily binned light curve at all.

**Comment by dimauromattia** [comment]
Hi @ritabanc, I have just pulled a fix to this issue .You may try to redo the analysis using the github version of Fermipy. The changes is at lines 187-191 of fermipy/lightcurve.py and should prevent the analysis from crashing if it is not successful in one bin. Let me know if you encounter any issue.

**Comment by ritabanc** [comment]
Thanks. I shall definitely try it and let you know what I find.

**Comment by dimauromattia** [comment]
@ritabanc Did you try running the analysis with the new Fermipy version?

**Comment by ritabanc** [comment]
I have sent you the config file via email.

**Comment by dimauromattia** [comment]
Hi @ritabanc I have not received any attachment in the email. Could you give me an update if you are still having the problem reported in this issue? If yes please send me the config.yaml directly on my personal email.
