### ISSUE TITLE
Preliminary 4FGL Not Importing

### ISSUE THREAD

**Issue by limyansky** [fermiPy/fermipy#262]
Hello, 

When I attempt to use the latest preliminary 4FGL version I get: KeyError: 'Cutoff_Energy'.
The error message indicates that this comes from line 396 in catalog.py. Indeed, when I look in the fits file, there is no key called "Cutoff_Energy". 

Best, 
Brent

**Comment by dimauromattia** [comment]
Hello @limyansky, 
Could you let me know what version of Fermipy you are using and where did you take the 4FGL catalog. Right now the Fermi-LAT Collaboration has released a preliminary 8 years list that is available here https://fermi.gsfc.nasa.gov/ssc/data/access/lat/fl8y/ and that we call FL8Y.

**Comment by limyansky** [comment]
I am using fermipy version 0.17.3. 

The catalogue I am using comes from an internal confluence page, and is the most recent preliminary run of 4FGL. I will send you an email to the page, as I don't know if there is any privileged information in the URL.

**Comment by dimauromattia** [comment]
Hi @limyansky for the moment it is better to use the publicly available FL8Y catalog. We will work on rendering Fermipy compatible with the 4FGL once this catalog will be public.

**Comment by dimauromattia** [comment]
Hi @limyansky for the moment it is better to use the publicly available FL8Y catalog. We will work on rendering Fermipy compatible with the 4FGL once this catalog will be public.
