### ISSUE TITLE
ccube.fits' already exists.

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#264]
I find this error 
IOError: File '/home/ubuntu/J1830+2847/data/ccube.fits' already exists.
I have update everything and here I done the same steps done fore others coordinates in the sky. But only in this case doesn't work. Why?

**Comment by dimauromattia** [comment]
Hi @imereu we recently add a fix for this. It happens when the ccube.fits already exists in the folder where you run the analysis. So probably for the source J1830+2847 you had already the cube.fits in the folder.

**Comment by imereu** [comment]
The analysis creates the ccube in a an empty folder created by the the analysis itself. ccube.fits can't already exists in the folder. So I don't understand this problem.

**Comment by imereu** [comment]
The fermipy version is 0.17.3.

**Comment by imereu** [comment]
I have updated fermipy and now I try my analysis again.

**Comment by imereu** [comment]
@dimauromattia now it works. I have update fermipy using
pip install git+https://github.com/fermiPy/fermipy.git

**Comment by ldivenere** [comment]
Is this fix also in the fermipy version available via conda?

**Comment by dimauromattia** [comment]
Not yet, we are planning to make a new PR soon that includes this fix.

**Comment by astro-fermi** [comment]
Now, I am getting the same error. To avoid it, I had to delete existing files and start from zero again. I am using 0.17.3 installed using anaconda.

**Comment by kialio** [comment]
I'm getting this error in 0.17.3 in the Fermi Summer School docker container.  Just putting this here for the record.

**Comment by kialio** [comment]
This effectively breaks the light curve functionality since it creates this with each step (I think).

**Comment by kialio** [comment]
This is fixed in 0.17.4.
