### ISSUE TITLE
error while running gta.optimize()

### ISSUE THREAD

**Issue by basuparth** [fermiPy/fermipy#266]
File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2270, in optimize
    npred_frac = npred_sum / self._roi_data[npred_str]
ZeroDivisionError: float division by zero. 

I ran into the above error, how can I fix this. I am using the recent version of FST installed with anaconda. Thanks in advance.

**Comment by dimauromattia** [comment]
Hi @basuparth, Could you give me more informations about the analysis you are trying to perform and the configurations file you are using?

**Comment by basuparth** [comment]
I am going through the tutorial of fermipy with Markarian421 as the source. After the first steps of importing GTAnalysis from fermipy when I run gta.optimize() I get the above error.
[config.txt](https://github.com/fermiPy/fermipy/files/2887652/config.txt)

**Comment by basuparth** [comment]
This error occurs for Fermipy installed with conda. I removed the said version and installed the master version from github and everything runs smoothly.
