### ISSUE TITLE
light curve plots

### ISSUE THREAD

**Issue by basuparth** [fermiPy/fermipy#268]

**Comment by basuparth** [comment]
I am working with mkn421 and everything works fine however after completing the light curve analysis I cannot find the relevant plots. I specified the option make_plots = True as mentioned in the documentation.

**Comment by dimauromattia** [comment]
@basuparth the current version of Fermipy does not provide the Lightcurve plot. In order to do that you should take the flux and time bins and make the plot on your own. We will probably add the Lightcurve plot in the next Fermipy version.

**Comment by cameronrulten** [comment]
Any ETA on the next release? We haven't had a release since July '18!
Yes, I'm an advocate of the release early, release often approach :)
