### ISSUE TITLE
Create Documentation for Plotting Features

### ISSUE THREAD

**Issue by woodmd** [fermiPy/fermipy#27]
It would be useful to have some documentation on the use of the plotting features -- particularly some illustrations of how to generate plots from a FITS file.  This could go in a new page of the sphinx documentation.

**Comment by cdeil** [comment]
@adonath is currently working on improved docs for [gammapy.image](https://gammapy.readthedocs.io/en/latest/image/index.html).

Maybe we can avoid duplication between Fermipy and Gammapy on this.
