### ISSUE TITLE
Query: lightcurve

### ISSUE THREAD

**Issue by Fredtrotteville** [fermiPy/fermipy#276]
It is mentioned in the official fermi tutorial for generating lightcurves
https://fermi.gsfc.nasa.gov/ssc/data/p7rep/analysis/scitools/python_tutorial.html

that all the parameters except 'Index' and 'Integral' should be fixed . However in fermipy the free_params option is set to default 'None' implying all the parameters are fixed. I am not sure as to what are the consequences of having all the parameters fixed as opposed to having the said two parameters freed. Also, what is the reasoning behind freeing the 'Index' and 'Integral' only? What if all the parameters were freed. It would be a great help if anyone could please explain or perhaps direct me towards a tutorial with detailed explanations about the query.

Thanks in advance

**Comment by dimauromattia** [comment]
Hi @Fredtrotteville, Fermipy when performs the analysis in each time bin first tries to leave free to vary the normalization and spectral index of the source of interest. If the fit is not successful then it fixes the spectral index. Therefore, Fermipy proceeds exactly as explained in the Science Tools tutorial. The free_params option is intended to contain a list of parameters of the source of interests that are left free to vary in the fit. If the parameter is not specified all the parameters are left free to vary. The None label means that by default the free_params is not consider. It does not mean thought that all the parameters of the sources are fixed. 

Regarding your question about freeing or not the parameter of the source, it depends on how bright is the source and the kind of analysis you plan to do. In general if the source is bright enough in each time bin I would advocate to leave free both index and normalization.
