### ISSUE TITLE
Warning: Invalid value will be ignored . . .

### ISSUE THREAD

**Issue by basuparth** [fermiPy/fermipy#277]
I ran into the following warning message while executing 
>>> gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})

I had used the same configuration file with fermi version 1.0.0, fermitools data 0.13 and fermipy 0.17.4 without any such problem. But after upgrading to fermi 1.0.1 and fermitools data 0.16 I get this warning. And I cannot understand which value is going to be ignored and how the analysis is going to be affected by that.(the only changes in the config file were the galdiff, isodiff files and the catalog(from 3FGL to 4FGL)).

2019-04-03 01:58:16 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.17.4 
ScienceTools version ScienceTools-11-04-00
WARNING: VerifyWarning: Invalid keyword for column 8: Column null option (TNULLn) is invalid for binary table columns of type 'E' (got 16959).  The invalid value will be ignored for the purpose of formatting the data in this column. [astropy.io.fits.column]
WARNING: VerifyWarning: Invalid keyword for column 46: Column null option (TNULLn) is invalid for binary table columns of type 'E' (got 16959).  The invalid value will be ignored for the purpose of formatting the data in this column. [astropy.io.fits.column]

**Comment by basuparth** [comment]
update: The warning is displayed only when the catalog is set to 4FGL. However if I add the file gll_psc_v18.fit in the /fermipy/data/catalogs and also change line 416 in catalog.py from gll_psc_v17.fit to gll_psc_v18.fit there are no warning messages when my config.yaml file specifies the catalog as 4FGL. Having done the changes I checked fermipy through creating residmaps and everything worked fine. Could you please let me know whether the warning messages are something serious and if it is indeed a consequence of using the initial release of 4FGL catalog.

**Comment by dimauromattia** [comment]
Hi @basuparth I have just created a pull request with the updated fits file of the 4FGL and the changes to catalog.py to ingest it.

**Comment by basuparth** [comment]
Thanks, @dimauromattia . But what was the warning message referring to ?
