### ISSUE TITLE
All .fits files under the folder "fermi/data/" are pointer files

### ISSUE THREAD

**Issue by ktzhao** [fermiPy/fermipy#278]
Hi,
I tried to install fermipy using the following commands:
conda install fermipy
pip install fermipy
or 
git clone  https://github.com/fermiPy/fermipy.git

BUT, all .fits files under the folder fermipy/data/ are pointer files.

such as "gll_iem_v07.fits" , open it with vi, I can see these:
"version https://git-lfs.github.com/spec/v1
oid sha256:2cef0173af218c6aa3d644b5a477eae00b0079d7a11d1a911f897e33fcc56285
size 464817600"

**Comment by basuparth** [comment]
Hi, @ktzhao as the data file galdiff(gll_iem_version) is already included in  the fermi ST installation. We simply have to make a configuration file as explained in the documentation page. The model section of the configuration file specifies the path to the galdiff file(incidentally the only large file) and will access it directly from the Fermi ST directories.

model:
  src_roiwidth : 15.0
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v06.fits'
  isodiff  : 'iso_P8R2_SOURCE_V6_v06.txt'
  catalogs : ['3FGL']  

Hope this answers your question.

**Comment by ktzhao** [comment]
I see, thanks for helping.
