### ISSUE TITLE
extracting parameters from 'Peaks' dictionary while running gta.find_sources()

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#28]
Hi,

I am trying to locate unmodeled sources present within the ROI using the following command

finder1=gta.find_sources(prefix='find',model=model2,sqrt_ts_threshold=5.0,min_separation=0.5,max_iter=10,sources_per_iter=1,tsmap_fitter='tsmap')
Now, I want to extract optimized coordinates and associated 95 % error circle radius. I tried the following
>>> print finder1.keys()
['sources', 'peaks']
>>> print finder1['peaks']   
[{'iy': 47L, 'ix': 49L, 'skydir': <SkyCoord (ICRS): (ra, dec) in deg
    (22.32678325, 14.73532697)>, 'fit_loc': {'p0': [54.508596981735295, 47.029043772296575, 49.153409853827597, 0.41382481744963878, 0.45442137627332674, 0.0], 'eccentricity2': 0.54792964782768394, 'z0': 53.658958900805466, 'popt': array([ 53.6589589 ,  46.84779717,  49.27264302,   0.45321406,
         0.51678862,   0.06778254]), 'rchi2': 2.4775997984441749, 'sigmay': 0.51678862459824437, 'sigmax': 0.45321405775379237, 'theta': 0.067782542583753297, 'eccentricity': 0.48052415868991766, 'y0': 49.272643019796639, 'fit_success': True, 'sigma': 0.68736705235252804, 'x0': 46.847797172176925}, 'amp': 7.4224458659137893, 'fit_skydir': <SkyCoord (ICRS): (ra, dec) in deg
    (22.29859018, 14.72011128)>}]
>>> print finder1['peaks']['sigma']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers, not str
>>> print len(finder1['peaks'])     
1
>>> type(finder1['peaks'])
<type 'list'>

Please help me in extracting the parameters from 'peaks' dictionary/list. I like 'find_sources' tool over 'localize' because it automatically determines the best fit location of unmodeled objects and thus very good for scripting large number of sources.
Thanks.
Vaidehi

**Comment by woodmd** [comment]
`peaks` is actually a list of dictionaries (one per peak) so to reference an element of it you need to use an integer, e.g.:

```
print 'sigmax: ', finder1['peaks'][0]['sigmax']
print 'sigmay: ', finder1['peaks'][0]['sigmay']
```
The best-fit sky position of each peak is contained in the `fit_skydir` element.  At present there's no good way to extract the 95% error circle.  I'll plan to add parameters for the positional uncertainty in the 0.7.1 release which should be ready later this week.

**Comment by vaidehiratna** [comment]
Thanks for the info. I found in one of the Fermipy script that R95 = 5.99**0.5*sigma. Now, since sigma is in pixels, so to get R95 in degrees, I guess we should multiply it by binsize (0.1 in my case). Do you think it is correct?

**Comment by woodmd** [comment]
As of the 0.8.0 release the localization errors are now automatically filled for sources found with `find_sources`.  The relevant quantities in the source dictionary are those that start with `pos` (e.g. `pos_r95` for the 95% error circle).
