### ISSUE TITLE
compute_srcprob not working

### ISSUE THREAD

**Issue by atreachar** [fermiPy/fermipy#281]
trying to calculate ptobablities of detected photons using

jupyter input

gta.compute_srcprob(self,xmlfile=None, overwrite=False)

but getting error message

jupyter output

AttributeError: 'GTAnalysis' object has no attribute 'compute_srcprob'

Thanks in advance

**Comment by dimauromattia** [comment]
Hello @atreachar, you should run gta.compute_srcprob without the self option. This is how you should do: gta.compute_srcprob(xmlfile=None, overwrite=False)

**Comment by atreachar** [comment]
Thanks mate but I'm afraid I'm getting the same error even with that change. Think I may be doing something silly

**Comment by dimauromattia** [comment]
In case you still find the same error, the problem is in how you define the object gta.
