### ISSUE TITLE
numpy load issue 

### ISSUE THREAD

**Issue by Fdepalma** [fermiPy/fermipy#282]
Restarting an analysis with a previously generated npy file, with the latest version of fermipy  (0.17.4) installed with conda at SLAC I get this error:
gta = GTAnalysis.create(filename)
 File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 538, in create
   roi_file, roi_data = utils.load_data(infile)
 File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/fermipy/utils.py", line 78, in load_data
   return infile, load_npy(infile)
 File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/fermipy/utils.py", line 60, in load_npy
   return np.load(infile).flat[0]
 File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
   pickle_kwargs=pickle_kwargs)
 File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/numpy/lib/format.py", line 692, in read_array
   raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

In my local installation I have solved the issue changing in fermipy/utils.py:
def load_npy(infile):
   return np.load(infile).flat[0]  
to
def load_npy(infile):
   return np.load(infile,allow_pickle=True).flat[0]

**Comment by dimauromattia** [comment]
Hi @Fdepalma, I tried myself using gta = GTAnalysis.create('roi_prova.npy') or gta.load_roi('roi_prova.npy') and I don't find the error that you report. Can you send me the script and configuration file you used?

**Comment by Fdepalma** [comment]
Hi @dimauromattia , I was simply reloading the npy file for evaluating the SED. I'm using at slac the ST 11-07-00 and the fermipy 0.17.4 downloaded using conda on my directory. I don't have this issue anymore since I did this simple change:

diff /afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/fermipy/utils.py~ /afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/fermipy/utils.py
60c60
<     return np.load(infile).flat[0]
---
>     return np.load(infile,allow_pickle=True).flat[0]

There was a numpy change in version 1.16.13, and in this version the allow_pickle option is False by default. 
The version of numpy that I'm using is the one that is in conda:
numpy.__file__
'/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/numpy/__init__.pyc'

Let me know if I can provvide you any other information.

**Comment by dimauromattia** [comment]
Hi Francesco, may I ask you how exactly you are reloading the npy file? In Fermipy there are different ways to do that and with the ones I tried I have not find that error.

**Comment by Fdepalma** [comment]
Hi @dimauromattia  sorry, I just saw your comment.
OK I use this simple line of code:
gta = GTAnalysis.create(filename)
in this file:
/afs/slac/g/glast/users/fdepalma/new_hess_sources/fermipy_analysis_J1614_J1534/fermipy_sed5_split.py

If I can do more test please let me know.

**Comment by dimauromattia** [comment]
Hi @Fdepalma I will add a fix for this. Thanks for bringing this up.
