### ISSUE TITLE
P8R3_SOURCE_V2 IRF ISSUE

### ISSUE THREAD

**Issue by shahzahir** [fermiPy/fermipy#283]
I have problem of using new irfs (P8R3_SOURCE_V2) in Fermipy.  For me Fermipy works fine with older versions (P8R2). Since Fermipy installation needs fermi science tools, I tried to include manually new irfs in the fermi science tool directory, but it  did not work. I tried many things but no help.
I have latest version of Fermi Science tool installed (v11r5p3).
While running gta.setup(), I am getting this error
RuntimeError: irfInterface::IrfsFactory::create: Cannot create Irfs object named P8R3_SOURCE_V2::FRONT.

**Comment by dimauromattia** [comment]
Hello @shahzahir you have to install the new version of the Fermi Science Tools (that are now called fermitools). See for more information here https://fermi.gsfc.nasa.gov/ssc/data/analysis/software/
