### ISSUE TITLE
import dmpipe with example setup

### ISSUE THREAD

**Issue by Fdepalma** [fermiPy/fermipy#287]
Hi 
using fermipy version 0.17.4, on mac os Mojave 10.14.5, testing the example indicated here  https://dmpipe.readthedocs.io/en/latest/quickstart.html
we got the attached error after setting up the indicated variable (export DMSKY_PATH=<current_dir>)  pointing to the downoladed roaster directory.

[dsph__example_error.txt](https://github.com/fermiPy/fermipy/files/3246896/dsph__example_error.txt)

We got the same issue doing simply 
import dmpipe.pipeline 

Regards
Francesco & Pietro

**Comment by dimauromattia** [comment]
Hi @Fdepalma 

Can you try preliminarily to do the following?

import pymodeler
import dmsky
import fermipy
import dmpipe
import gammapy

Let me know if any of the above command fails.

Best

Mattia

**Comment by Fdepalma** [comment]
Hi @dimauromattia 
We installed dmpipe with pip on a linux machine (conda seems unable to find the dmpipe package following the instruction). 
If we don't set the variable $DMSKY_PATH we are able to import all the packages without any issue. If we set that variable to the directory where we download the example we get the same error:

```
>>> import dmpipe
Using /lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmsky/data for FileLibrary
Using /lustre/home/fdepalma/dmpipe_example/data for FileLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmpipe/__init__.py", line 8, in <module>
    from .dm_plotting import PlotDMSpectra, PlotLimits, PlotDM, PlotLimits_SG, PlotStackedLimits_SG,\
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmpipe/dm_plotting.py", line 22, in <module>
    from dmpipe.dm_spectral_utils import DMCastroData, DMSpecTable
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmpipe/dm_spectral_utils.py", line 16, in <module>
    from dmsky.priors import create_prior_functor
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmsky/priors.py", line 18, in <module>
    filelib = FileLibrary()
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmsky/library.py", line 77, in __init__
    self.library = self.load_library(self.paths)
  File "/lustrehome/exp_soft/glast_local/miniconda2/envs/fermi/lib/python2.7/site-packages/dmsky/library.py", line 87, in load_library
    subdirs = [path] + next(os.walk(path))[1]


```
Ciao
Francesco & Antonio

**Comment by dimauromattia** [comment]
What files/directories you have inside current_dir (that you use to configure DMSKY_PATH)?

**Comment by Fdepalma** [comment]
Hi @dimauromattia I was able to replicate the issue at slac. My variable is set as following:
echo $DMSKY_PATH 
/afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data/
as said on the README file and on the web page.
after I set this variable I get the same issue importing dmpipe.
Ciao
Francesco

**Comment by dimauromattia** [comment]
Hi @Fdepalma I am asking what files and directories you have inside dmsky_data.

**Comment by Fdepalma** [comment]
Hi @dimauromattia 
Those are the files in the directory:
ls dmsky_data/
rosters

ls dmsky_data/rosters/
roster.yaml

**Comment by dimauromattia** [comment]
As I suspected there were missing information in that folder. You have to add also the target folder and put inside the yaml file with the information of the J factor for the objects you want to study. Without that file the pipeline does not know what J factor use in the analysis.

**Comment by Fdepalma** [comment]
We just tried the example that is here:
https://dmpipe.readthedocs.io/en/latest/quickstart.html
downloading the directory linked on the page.
Are the J factor for this example posted somewhere?
Could the  quickstart guide be updated?

Thanks
Francesco

**Comment by dimauromattia** [comment]
You can find examples of those files in the Github page of the Dmsky package.

**Comment by Fdepalma** [comment]
So we should put those:
https://github.com/fermiPy/dmsky/tree/master/dmsky/data/targets
inside the dmsky_data directory?
Are you referring to those files?

**Comment by dimauromattia** [comment]
Yes exactly

**Comment by Fdepalma** [comment]
We copied this directory:
/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/data/targets/
inside the dmsky_data directory.
Now we have: 
 ls /afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data/
rosters  targets

We still get exactly the same error, we tested it on 2 different OS

**Comment by dimauromattia** [comment]
I looked into you folder at SLAC and I do not see the reason why it is failing. You have all the required files. Can you send me the error you have when you run the pipeline in the SLAC area? Before running it can you create a folder logs?

**Comment by Fdepalma** [comment]
The error is always the same:
```
bash-4.1$ export DMSKY_PATH=/afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data
bash-4.1$ python
Python 2.7.15 | packaged by conda-forge | (default, Feb 28 2019, 04:00:11) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dmpipe
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to dhcp195.ba.infn.it:0.0
Using /afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/data for FileLibrary
Using /afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data/data for FileLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmpipe/__init__.py", line 8, in <module>
    from .dm_plotting import PlotDMSpectra, PlotLimits, PlotDM, PlotLimits_SG, PlotStackedLimits_SG,\
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmpipe/dm_plotting.py", line 22, in <module>
    from dmpipe.dm_spectral_utils import DMCastroData, DMSpecTable
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmpipe/dm_spectral_utils.py", line 16, in <module>
    from dmsky.priors import create_prior_functor
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/priors.py", line 18, in <module>
    filelib = FileLibrary()
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/library.py", line 77, in __init__
    self.library = self.load_library(self.paths)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/library.py", line 87, in load_library
    subdirs = [path] + next(os.walk(path))[1]
StopIteration
>>> 
```

Which log do you need? Could you let me know how to create it?
I checked the version of the requested packages, all are compatible with the README and this are the results:
```
>>> gammapy.__version__
u'0.10'
>>> pymodeler.__version__
u'0.1.3'
>>> dmsky.__version__
u'0.2.3'
>>> fermipy.__version__
'0.17.4'
```

**Comment by dimauromattia** [comment]
I checked that the version of the packages is the same I use. Can you try to replace into the file /afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data/targets/dwarfs/albert2017.yaml 

segue_1:
  ackermann2016_photoj_0.6_nfw:
    extension: -0.44
    extsigma: 0.46
    j_integ: 2.399e+19
    j_sigma: 0.6
    profile: {type: NFW}

with 

segue_1:
  ackermann2016_photoj_0.6_nfw:
    extension: -0.44
    extsigma: 0.46
    j_integ: 2.399e+19
    j_sigma: 0.6
    d_integ: 2.399e+19
    d_sigma: 0.6
    profile: {type: NFW}

and 

draco:
  ackermann2016_photoj_0.6_nfw:
    extension: -0.59
    extsigma: 0.25
    j_integ: 2.188e+18
    j_sigma: 0.6
    profile: {type: NFW}

with 

draco:
  ackermann2016_photoj_0.6_nfw:
    extension: -0.59
    extsigma: 0.25
    j_integ: 2.188e+18
    j_sigma: 0.6
    d_integ: 2.188e+18
    d_sigma: 0.6
    profile: {type: NFW}

Then try to rerun the import dmpipe and let me know if you have the same error.

**Comment by Fdepalma** [comment]
I edited following your inputs the file (adding the d_ informations):
/afs/slac/g/glast/users/fdepalma/dmpipe_example/dmsky_data/targets/dwarfs/albert2017.yaml
but I get the same issue.

**Comment by eacharles** [comment]
Can you just use the DMCAT distribution, it works fine for me.
Do do this you need to be using bash, then if you can see the disk /gpfs/slac/kipac/fs1/u/dmcat then do
export DMCAT_DISK=gpfs
otherwise do
export DMCAT_DISK=nfs

Then you do:
source /$DMCAT_DISK/slac/kipac/fs1/u/dmcat/software/config/setup_dmcat.sh
dmsetup stable

Let me know if that works for you.

**Comment by eacharles** [comment]
Ok, so I figure out that the problem you are seeing is caused by pointing dmsky at a directory that doesn't have any subdirectories via the DMSKY_PATH variable.  I've updated the code so the error message is more useful and it doesn't crash, but the root cause is that you are not setting DMSKY_PATH to the right directory.

**Comment by Fdepalma** [comment]
Hi @eacharles 
the directory that I'm pointing at:
/afs/slac/g/glast/users/fdepalma/anaconda/lib/python2.7/site-packages/dmsky/data
has 2 subdirectories, I copied the relevant files as suggested by Mattia, so the problem should not be related to the missing subdirectories.
I think that it is really useful it the example found in the web page works as described.
Thanks
Francesco

**Comment by eacharles** [comment]
Ok, I should have been more specific, you DMSKY_PATH need to have 3 subdirectoires: rosters, targets and data.   It looks like your area only has targets and rosters.  I copied it and added an empty "data" directory and it worked

**Comment by eacharles** [comment]
The area is here: /gpfs/slac/kipac/fs1/u/dmcat/workdir/sandbox/test_dmpipe/fdepalma_data
so i do:
dmsetup stable
export DMSKY_PATH=/gpfs/slac/kipac/fs1/u/dmcat/workdir/sandbox/test_dmpipe/fdepalma_data
and then it works.

**Comment by Fdepalma** [comment]
@eacharles adding the empty data direct, solves the issue of loading dmpipe. I'll test it further.
