### ISSUE TITLE
Problem with Extension fitting

### ISSUE THREAD

**Issue by emmaow** [fermiPy/fermipy#294]
Dear all,

I am using the fermipy (Version: 0.17.4) tool to obtain the extension of a source. I used the standard analysis (not different PSF or EDISP).
Whenever I try to run it I get the following error: "AttributeError: 'GTBinnedAnalysis' object has no attribute '_bexp'"
I tried point source, radial gaussian or radial disk, and nothing changed. Also, it happens for different sources in my FoV not just for one particular one. 

Do you have any idea what might be happening? 

Thanks a lot for the help in advance
Emma

**Comment by dimauromattia** [comment]
Hi @emmaow can you provide me more info on the analysis that you are trying to make? What is the configuration file you are using and which source you are trying to find the extension of?

**Comment by eacharles** [comment]
Ok, I've updated the error message that so that it will indicate why gta._bexp is not set.
