### ISSUE TITLE
Error adding source before setup

### ISSUE THREAD

**Issue by cameronrulten** [fermiPy/fermipy#296]
According to the online documentation it is possible to add a source before or after running GTA setup. See https://fermipy.readthedocs.io/en/latest/model.html#editing-the-model-at-runtime
However, when attempting to add a source before running setup (as in the example) I get the following error:
```IOError: [Errno 2] No such file or directory: 'srcmap_00.fits'```
Is this seen by others? If, so please can someone fix the problem or update the online documentation if it is not possible to add a source prior to running setup.
Thank you!!!

**Comment by dimauromattia** [comment]
Hi @cameronrulten can you give me more info of the setup you are using? Can you post here the configuration file you are using?

**Comment by cameronrulten** [comment]
Hi @dimauromattia thanks for looking into this for me. The details as follows...
I'm testing using Jupyter notebook interactive session running fermipy version 0.17.4 with
ScienceTools version ScienceTools-11-04-00.

If it helps, in the Traceback the error appears to start with the add_source command in my notebook, then references the add_source function in gtanalysis.pyc, before highlight line 4594 in gtanalysis.pyc: srcmap_utils.delete_source_map(self.files['srcmap'], name). So my guess is the problem maybe lies here where it tries to delete a non existent source map file.

Anyway my python commands are exactly as per the online documentation and the config.yaml file I'm using is attached as a plain text file. Obviously I've adjusted the paths for my system, and what you see here is generic.

[config.txt](https://github.com/fermiPy/fermipy/files/3450498/config.txt)

**Comment by dimauromattia** [comment]
Hi @cameronrulten, I think there is an other error message before 'IOError: [Errno 2] No such file or directory: 'srcmap_00.fits''. Can you delete the srcmap.xml rerun the script and send me all the output of the run?

**Comment by eacharles** [comment]
It is probably better to update the documenation.   gta.setup() has been doing more and more things, and keeping the ROI model in sync with is tricking enough.

**Comment by eacharles** [comment]
Ok, I've updated the docs.   This will get pulled into build 0.19.1 or later.

**Comment by cameronrulten** [comment]
Thanks Eric 👍
