### ISSUE TITLE
Allow user to specify type to save plots as

### ISSUE THREAD

**Issue by terrijb** [fermiPy/fermipy#3]
I suggest allowing users to specify the file type to save as, eg png or pdf or ... or multiple! in functions like make_sed_plots(). Could leave png as default. 
(Not critical atm but can be v important for publication.)

**Comment by woodmd** [comment]
Closing this issue.  I added support for setting a default image file type some time ago (via `plotting.format` option).  Note that the plots generated by fermipy are really only intended for diagnostic purposes.  The underlying data for maps, SEDs, etc. are always saved to FITS so for publication figures it's probably better that the user just generates their own.
