### ISSUE TITLE
utility to generate LT cubes

### ISSUE THREAD

**Issue by terrijb** [fermiPy/fermipy#30]
It'd be great to have a utility to generate LT cubes automatically.
Since a set of monthly LT cubes would take up less than 1GB (by Matt's estimate :), having them accessible and sumable could also be worthwhile, particularly as a number of analyses don't need time series (at least till verifying that the source is not appreciably variable).

**Comment by woodmd** [comment]
I've implemented a faster method for generating LT cubes which can be enabled with `ltcube.use_local_ltcube`.  This can calculate a LT cube for the whole mission in a few minutes so I think this mostly eliminates the need for something like a LT cube cache.
