### ISSUE TITLE
Read XML model files with attributes

### ISSUE THREAD

**Issue by jballet** [fermiPy/fermipy#304]
In the source catalog process I have existing XML files for each RoI.
I would like to be able to enter them to fermipy.
This is only possible at present if I clean them of all the attributes that are written at source level (eg Flux100, Energy_Flux100, TS_value, Pivot_Energy, ...).
If I leave those attributes fermipy will not work.
It woud be nice if it could simply ignore them.

**Comment by eacharles** [comment]
Ok, this is just to let you know that I'm unlikely to do this.   The reason being that the code that reads the xml files for fermipy is checking to make sure that the xml makes sense, and crashes if the xml tried to define parameters that don't exist, specifically because a number of people asked for that feature.   The only way that I could image this working is if you provided an explicit list of attributes that should be ignored.

**Comment by jballet** [comment]
I must admit I do not understand your reasoning, or maybe it is just a question of English. Are you saying that you will not do this (ignore the attributes at source level) precisely because several people asked for it ("specifically because a number of people asked for that feature")?
In addition, your first sentence is referring to "parameters". My query is not about parameters of the model (of course I am not asking to ignore putative additional parameters) but about attributes at source level.
As far as I know, fermipy does nothing with those attributes, so why can't you simply ignore them?

**Comment by eacharles** [comment]
Sorry, I wasn't clear before.  
The point I was making is that several people have asked for some sort of checking that the xml files are correct, and requested that fermipy catch errors if the xml files are not correctly structured.   
What you are asking for is for the xml files structure to be more flexible and to ignore cases where they don't match the rigid structure.  
The only way I can do both those things is if you define a precise set of things I should be ignoring.   In this case it sound like you want me to ignore any xml attributes that are defined at the source level.    
If you send me an example XML file as an example I can have a look.

**Comment by jballet** [comment]
The 4FGL catalog (in its XML incarnation) is what I have in mind.

**Comment by eacharles** [comment]
Ok, I'll have a look.

**Comment by eacharles** [comment]
Hi Jean, How are you loading the xml model into fermipy?

I took the draco region test analysis 
https://raw.githubusercontent.com/fermiPy/fermipy-extras/master/data/fermipy_test_draco.tar.gz

And replaced the line to define the catalog (see below) to use the xml file I downloaded from the FSSC and it seemed to work fine.

  # List of catalogs to be used in the model.
  catalogs : 
    - gll_psc_v21.xml

**Comment by jballet** [comment]
I concur. I could not reproduce the problem with fermipy 0.19. All the better!
