### ISSUE TITLE
GTAnlaysis

### ISSUE THREAD

**Issue by fermimc** [fermiPy/fermipy#305]
Good morning.
    I'm installing Fermipy in my macOS 10.13.6. I have followed all the steps (installing the fermitools and then I followed https://fermipy.readthedocs.io/en/latest/install.html) installing with pip. I'm using Python 2.7 and I'm having troubles importing GTAanalysis (from fermipy.gtanalysis import GTAnalysis). Apparently it's giving errors with healply, but I don't have any idea how to solve it.

    Thank you in advance.

    The error that terminal is giving me is the following:

    ImportError: dlopen(/Users/martacarrasco/opt/anaconda2/envs/fermi/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Symbol not found: __Z11alm2map_polIdEvRK3AlmINSt3__17complexIT_EEES7_S7_R11Healpix_MapIS3_ESA_SA_b
      Referenced from: /Users/martacarrasco/opt/anaconda2/envs/fermi/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so
      Expected in: flat namespace
     in /Users/martacarrasco/opt/anaconda2/envs/fermi/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so

**Comment by eacharles** [comment]
The installation instructions have changed a lot for fermipy version 0.19.0 to try and avoid issues like this.
