### ISSUE TITLE
How to plot a light curve from already generated data?

### ISSUE THREAD

**Issue by TomCayf** [fermiPy/fermipy#308]
Hi,

I'm not very experienced with Fermipy and the documentation isn't much help. I generated a light curve for an object ages ago, and just have all the light curve folders containing the data inside the object's directory (i.e. lightcurve_561726149_564881477, ... etc plus all the other files generated during a standard analysis).
I would like to re-plot the light curve without having to run the entire analysis again. As far as I'm aware, typing lc = gta.lightcurve(...) will run the analysis again rather than using the already-generated data.

So how then do I use what I have to plot the light curve and extract the raw data for each point?
Any tips greatly appreciated - thanks in advance.

**Comment by basuparth** [comment]
Hi, @TomCayf  the lightcurve analysis should have produced a **"4fgl(source name) _lightcurve"** file in both **.npy** and **.fits** format. You can access your data from either of those files and plot the lightcurve. The documentation page of fermipy has a section called "Advanced Analysis Methods" the subsection "Light Curves" over there gives a detailed description of the contents of the LC analysis output.
