### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#309]
In Gammapy we have a CI build that checks a few things for Fermipy.

It started failing today:
https://travis-ci.org/gammapy/gammapy/jobs/612273278#L1681

```
__________________ ERROR collecting fermipy/stack/__init__.py __________________
ImportError while importing test module '/home/travis/build/gammapy/gammapy/fermipy/fermipy/stack/__init__.py'.
```

Locally I see `six` import fails, because I'm using the latest Astropy dev:
https://gist.github.com/cdeil/25a1d813c0408f41b5cf98b295d3702a

If you want `fermipy` to keep working with the upcoming Astropy 4.0 release, you'd have to either `import six` and list it as a dependency, or vendor a copy in your package (it's a single file to copy), and in either case adapt the imports.

@dimauromattia @eacharles - What to do? Can you fix? Should I send a PR?

cc @adonath @registerrier - If it's not fixed within the next ~ day, I'll go ahead and disable the Gammapy CI build using Fermipy temporarily.

**Comment by eacharles** [comment]
For now there is a workaround in 0.19.0 that allow both the new and the old version of astropy.    We will have to update this to explicitly include six once we can move away from python2.7

**Comment by henrikef** [comment]
I'm hoping this is not an issue anymore with `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. @cdeil please re-open if there are still remaining issues!
