### ISSUE TITLE
4FGL catalog with docker 

### ISSUE THREAD

**Issue by Javier911210** [fermiPy/fermipy#310]
I have an issue at the moment that I try to include the 4FGL catalog in my config.yaml. I made the installation of fermipy with Docker at it does not recognize this catalog, does anyone know how can I update it?

**Comment by jleagle94** [comment]
Hi! Check what version of FermiPy you have. 

conda list fermipy


if it is NOT 0.17.4, you need to upgrade it to use 4FGL.

conda upgrade fermipy

This should solve your issues as I faced the same one.

Best,

Jordan
