### ISSUE TITLE
Corrupted file linked in SC installation tutorial

### ISSUE THREAD

**Issue by newjerseyversusvalhalla** [fermiPy/fermipy#312]
Your installation guide recommends downloading Fermi Science Tools by downloading it directly from http://fermi.gsfc.nasa.gov/ssc/data/analysis/software/tar/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.19-10-without-rootA.tar.gz

But this file produces error when anpacking with tar. I've had this issue on several machines so it looks like there's something wrong with the file. Installation following this Conda-wiki (https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide) works fine.

**Comment by eacharles** [comment]
The installation instructions have been updated in version 0.19.0 to simply installation and avoid issues like this.
