### ISSUE TITLE
tscube test crash on Mac OS

### ISSUE THREAD

**Issue by tibaldo** [fermiPy/fermipy#321]
I had a crash while running the units tests on my laptop. test_gtanalysis_tscube crashes throwing a message `Illegal Instruction:4`.

OS: Mac OS High Sierra 10.13.6. Anaconda Python 2.7.14.

I installed using anaconda as follows:
```
conda create -n fermipy-dev -c conda-forge/label/cf201901 -c fermi fermitools
conda activate fermipy-dev
conda install ipython
conda install fermipy
conda remove fermipy --force
```
The last two steps enable me to install all the dependencies using conda. Relying on setup.py to install them via pip always led to problems and dysfunctional installation. After that I installed the local code by
```
python setup.py install
```

All the other test units run fine if I comment out test_gtanalysis_tscube.

As discussed by email with @eacharles this bug should be tracked down, but I can't figure out how. Please let me know if I can provide more information or assistance.

**Comment by eacharles** [comment]
Ok, this is related to the d'tor of the FitScanner class.   I'm working on debugging it.

**Comment by eacharles** [comment]
Ok, this was down to an non-virtual destructor in a class used by FitScanner.

**Comment by eacharles** [comment]
And I've added a PR in fermitools/Likelihood that fixes this.
