### ISSUE TITLE
Can't install Fermipy v0.19

### ISSUE THREAD

**Issue by aribrill** [fermiPy/fermipy#337]
When [installing Fermipy](https://fermipy.readthedocs.io/en/latest/install.html) using the recommended condainstall.sh script, I am unable to install the latest version (v0.19.0). I'm running Scientific Linux 6.

Running the following commands installs Fermipy v0.17.4:

```
curl -OL https://raw.githubusercontent.com/fermiPy/fermipy/master/condainstall.sh
export CONDA_PATH=/a/data/tehanu/brill/miniconda3/
export FERMIPY_CONDA_ENV=fermi
source condainstall.sh
```

Running `export INSTALL_CMD="conda install -y --name  $FERMIPY_CONDA_ENV -c $CONDA_CHANNELS fermipy=0.19.0"` before `source condainstall.sh` results in a failure with the following error:

```
<...>
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abor| 
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fermipy=0.19.0 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by eacharles** [comment]
Ok, I suspect that the issue you are having is b/c you are pointing CONDA_PATH at an existing conda installation that already has a bunch of stuff that depends on python 3.   So what is happening is that fermipy is picking up a dependency on python 3 via some package it depends on.    I suggest making a dedicated CONDA installation for your python 2 stuff. 
Doing CONDA_PATH=/a/data/tehanu/brill/miniconda2 before running condainstall.sh will cause it to download miniconda and make a clean conda installation.
You will want some way of switching between conda versions.   For example, I have this in my .bashrc file:

```
anaconda2_setup() {
  export ANACONDA2PATH="/Users/echarles/anaconda2"
  echo "setting anaconda to point at $ANACONDA2PATH"
  . $ANACONDA2PATH/etc/profile.d/conda.sh
}

anaconda3_setup() {
  export ANACONDA3PATH="/Users/echarles/anaconda3"
  echo "setting anaconda to point at $ANACONDA3PATH"
  . $ANACONDA3PATH/etc/profile.d/conda.sh
}
```

**Comment by eacharles** [comment]
Ah.  I investigate more and, it looks like that dependency is coming in from conda-forge.   

You can avoid the issue you using pip to install fermipy, after using conda to install everything else.

Just do 
export INSTALL_CMD='pip install fermipy=0.19.0' 
before running condainstall.sh

**Comment by aribrill** [comment]
Thanks a lot for the quick reply. Installing fermipy with pip worked - I needed to use `export INSTALL_CMD='pip install fermipy==0.19.0'` with two equals signs. I'm installing into (at least what I think is) a brand-new miniconda installation.

**Comment by eacharles** [comment]
Ok, thanks, I fixed the comment above.   I'm going to leave this issue open for now, until we figure out what is going on with conda.  Thanks for reporting this.
