### ISSUE TITLE
pylikelihood not installed with fermipy

### ISSUE THREAD

**Issue by kcdage** [fermiPy/fermipy#348]
I installed fermipy using pip, and when I tried to use fermipy ("from fermipy.gtanalysis import GTAnalysis" as in the quickstart example), I got the following error: ImportError: No module named pyLikelihood

**Comment by basuparth** [comment]
Hello @kcdage could you please check if you installed the fermipy in the fermi environment? As pyLikelihood is a part of the Fermi science tools maybe the reason you get the error is that while installing fermipy with pip you chose the default python environment of your system and not the one associated with FST.

**Comment by kcdage** [comment]
That was exactly it, thank you!

**Comment by aminasuneer** [comment]
@kcdage 
Can you please tell what steps exactly you followed for installation of fermipy within fermi env.
Bcs I tried with some commands like

$ conda create --name fermipy -c conda-forge -c fermi fermipy
   $ conda env create --name fermipy -c conda-forge -c fermipy python=3.7 fermitools=2.0.8
   $ conda install --name fermipy -c conda-forge fermipy
it is making another env for fermipy and I am getting the same error as you mentioned.

my fermitools version is 2.0.8
