### ISSUE TITLE
Error while loading config.yaml file

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#35]
Hi,
I just upgraded to fermipy 0.8.0 and tried to understand the new additions. When I loaded a sample yaml file, which I was using flawlessly earlier, I got the following error:

>>> gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})

... lots of lines ...
  File "/Users/vaidehi/Softwares/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/roi_model.py", line 1108, in load_diffuse_srcs
    self._load_diffuse_src('isodiff')
  File "/Users/vaidehi/Softwares/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/roi_model.py", line 1137, in _load_diffuse_src
    resolve_file_path(src_dict['file'],
UnboundLocalError: local variable 'src_dict' referenced before assignment

In the config file, I am supplying isodiff file location as follows

components:
  - { selection : { evtype : 4  }, model: {isodiff: $FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_PSF0_v06.txt} } 
  - { selection : { evtype : 8  }, model: {isodiff: $FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_PSF1_v06.txt} } 
  - { selection : { evtype : 16 }, model: {isodiff: $FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_PSF2_v06.txt} } 
  - { selection : { evtype : 32 }, model: {isodiff: $FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_PSF3_v06.txt} } 

Please help me in getting rid of this error.

Thanks.

**Comment by woodmd** [comment]
I've just checked in a fix for this error.  Until I make a patch release you'll need to use the HEAD version.  There are instructions for installing fermipy from the git repo [here](http://fermipy.readthedocs.io/en/latest/install.html#building-from-source).

**Comment by vaidehiratna** [comment]
Thanks for the help. It is working now. Just one more doubt. I am trying component wise analysis for four PSFs. The input is as follows (similar to given on Fermipy documentation)
components:
  - { selection : { evtype : 4, zmax: 70 }, model: {isodiff: iso_P8R2_SOURCE_V6_PSF0_v06.txt} }
  - { selection : { evtype : 8, zmax: 75 }, model: {isodiff: iso_P8R2_SOURCE_V6_PSF1_v06.txt} }
  - { selection : { evtype : 16, zmax: 85 }, model: {isodiff: iso_P8R2_SOURCE_V6_PSF2_v06.txt} }
   - { selection : { evtype : 32, zmax: 90 }, model: {isodiff: iso_P8R2_SOURCE_V6_PSF3_v06.txt} }

For time saving, I am using an all sky LTCube.fits file but it was generated using zmax=90 (we can supply only one ltcube in the yaml file and so I used zmax=90, i.e., the largest angle cut). The analysis has completed without any error but I am suspicious whether using the same ltcube for components with different zmax could affect the accuracy of the results?
Thanks.
