### ISSUE TITLE
How to draw a TS Map including the new source found from gta.find_sources. 

### ISSUE THREAD

**Issue by Fredtrotteville** [fermiPy/fermipy#354]
After running the find new_source command how can I draw a TS Map with my target source in the center and the new source at its discovered co-ordinates ? The default resulting TS Map does not display the newly added source named PS xxxx+xxx anywhere on the map.

**Comment by zzzlllccc** [comment]
Hi [Fredtrotteville](https://github.com/Fredtrotteville),Do I need to include the sources we added when creating the TS Map ? Or do we need to use the 'exclude' command to remove the new sources we added?
Thanks.
