### ISSUE TITLE
PyYAML yaml.load(input) Deprecation

### ISSUE THREAD

**Issue by cameronrulten** [fermiPy/fermipy#363]
Recommended that all the load statements for the config.yaml file be updated for safe loading, please see

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by Alex-Broughton** [comment]
Hello, I am currently running into an issue that I believe is associate with this while trying to load a config file with `binning={"npix": [625,50]}` , which the loader is not accepting. Is there a good work around to this?

**Comment by eacharles** [comment]
switch yaml.load to yaml.safe_load.
I've gone ahead and done this, and this will be in fermipy version > 1.0.1
