### ISSUE TITLE
Minimum TSext to replace the update model of a source with an extended template

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#37]
Running gta.extension('sourceA') it's possible to add the option "update" that updates the source model with the best-fit spatial extension. As the function is written now with this option it replaces the source model with an extended template regardless the value of TSext.

It would be great to have the possibility to give as an option of gta.extension('sourceA') a value for the minimum TSext that the source should have to update the source model with an extended template.

**Comment by woodmd** [comment]
This is now implemented with ``sqrt_ts_threshold`` argument to ``extension`` in the 0.9.2 release.  Note that when setting this to None (the default) no threshold will be applied.
