### ISSUE TITLE
TypeError when trying to print(gta.roi['source']), fermipy 1.0.0

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#374]
When I type `print(gta.roi['4FGL J0540.3-6920'])`, I get an error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/roi_model.py", line 819, in __str__
    return '\n'.join(output).format(**data)
TypeError: unsupported format string passed to list.__format__

I tried to debug and found that the output is prepared in `fermipy.roi_model.Source.__str__`. In the line 798 of fermipy/roi_model.py, we see
`output += ['{:15s}:'.format('Associations') + ' {names:s}']`
which requires `Source.data['names']` to be of the type `string`. However, this attribute is actually a list, and this causes the TypeError. Is it a bug? I changed the above line to
`output += ['{:15s}:'.format('Associations') + ' {names}']`
and it works now.

**Comment by jleagle94** [comment]
This was also an issue for me until I just pulled the latest version of Fermipy 1.0.0 this morning. thanks @ndilalla!

**Comment by eacharles** [comment]
Closed with #380
