### ISSUE TITLE
lightcurve _pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x7fc504da0050>: it's not the same object as gammapy.maps.wcs.WcsGeom.get_coord

### ISSUE THREAD

**Issue by astroSyvertHE** [fermiPy/fermipy#375]
Hi,
I installed fermibottle:2020-10-08 with fermipy v1.0.0. I'm trying to generate a lightcurve with multithread, but a pickling error arises. In particular:

" Traceback (most recent call last):
  File "FermiAnalysis_20d.py", line 112, in <module>
    lc = gta.lightcurve('4FGL J1555.7+1111', nbins = 18, multithread=True, nthread=8, free_radius = 3.0, shape_ts_threshold = 16.0, make_plots = True) #, outdir='1y') #20d
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 291, in lightcurve
    o = self._make_lc(name, **config)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 437, in _make_lc
    mapo = p.map(wrap, itimes)
  File "/opt/anaconda/envs/fermi/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/anaconda/envs/fermi/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/opt/anaconda/envs/fermi/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/opt/anaconda/envs/fermi/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/anaconda/envs/fermi/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x7fc504da0050>: it's not the same object as gammapy.maps.wcs.WcsGeom.get_coord "

Could you help me?

Thank you very much!

Best,

sofiav

**Comment by adonath** [comment]
@astroSyvertHE Which version of Gammapy do you have installed along with `fermipy`? You can check using `import gammapy; print(gammapy.__version__)`...

**Comment by astroSyvertHE** [comment]
@adonath gammapy version 0.17

**Comment by adonath** [comment]
Ok, this a known Gammapy issue then. To fix the issue you can either update to v0.18.2 or downgrade to <v0.14. I guess the best solution is to setup a dedicated fermipy environment, which specifies the compatible Gammapy version...

**Comment by astroSyvertHE** [comment]
@adonath  thank you very much! I installed the last version, gammapy-0.18.2. Now there's this error:

"  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/gammapy/maps/core.py", line 332, in write
    hdulist = self.to_hdulist(**kwargs)
TypeError: to_hdulist() got an unexpected keyword argument 'conv' "

**Comment by adonath** [comment]
@astroSyvertHE This means `fermipy` is not compatible with Gammapy v0.18.2. It seems so far fermipy is only tested with Gammapy v0.10...

**Comment by jeget** [comment]
@astroSyvertHE you can fix this gammapy-0.18.2 problem as described in issue #372 (the second post there).

**Comment by henrikef** [comment]
This should be fixed in `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
