### ISSUE TITLE
Fermipy-1.0.0 lightcurve(multithread=True): TypeError: list object is not an iterator

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#376]
The error is raised in line 450 of lightcurve.py:
`next_fit = next(mapo)`
where `mapo` is the result of time bins processing:
```
if kwargs.get('multithread', False):
    p = Pool(processes=kwargs.get('nthread', None))
    mapo = p.map(wrap, itimes)
    p.close()
else:
    mapo = map(wrap, itimes)
```
The problem is Pool.map() returns a list which is not an iterator. I found a workaround by changing `map` to `imap` in line 435:
`mapo = p.imap(wrap, itimes)`

**Comment by eacharles** [comment]
Fixed by #380
