### ISSUE TITLE
GTAnalysis: create() got an unexpected keyword argument 'frame'

### ISSUE THREAD

**Issue by medoug7** [fermiPy/fermipy#378]
I've been trying to understand how to use fermipy and fermitools, so i decided to follow the steps outlined in the jupyter notebook https://github.com/fermiPy/fermipy-extra/blob/master/notebooks/pg1553.ipynb but i get an error in the following step:
`gta = GTAnalysis('pg1553/config.yaml',logging={'verbosity': 3})`

The error says:
`create() got an unexpected keyword argument 'frame'`

and I still haven't been able to figure out what the issue is.

When reading the fermipy documentation I saw that if the path for the ltcube.fits is not defined in the config.yaml file (as is the case for the config file in the notebook), then a new ltcube would be created when using GTAnalysis.
Based on this I believed that the problem could be the failure to produce a new ltcube, however, I've also tried creating a ltcube using the same photon and spacecraft files and the expCube.run() function from fermitools (as shown in many examples from the nasa fermitools site), and then putting the path for this file in the config.yaml as the ltcube parameter.
Unfortunately the error persisted and I don't know what to do.
I'm using fermipy 1.0.0 and sciencetools 1.2.23, could it be a compatibility issue?

![Captura de tela de 2021-01-25 17-17-06](https://user-images.githubusercontent.com/68132829/105761964-876cf380-5f32-11eb-8cd9-0d9ee14e9928.png)

**Comment by abhradeep-1996** [comment]
I am also getting the exact same error. I am using fermipy 1.0.0 and fermitools 2.0.8. Can somebody help us out?
Thanks.

**Comment by medoug7** [comment]
I discussed this issue with someone from the fermi colaboration and they said it coud be a compatibility issue. This error happened when I was using python 2.7, but then I reinstalled everything in python 3.7 and it worked fine.

**Comment by abhradeep-1996** [comment]
Thanks, @medoug7 for your help.
I have two different fresh fermipy and fermitools installations with python 2.7 and python 3.7. But I am getting same error in both of them! Maybe the gammapy maps related issue still persists.

**Comment by eacharles** [comment]
Nicollo updated fermipy to be compatible with the latest gammapy
