### ISSUE TITLE
Need help with persisting Fermipy errors: GTI

### ISSUE THREAD

**Issue by wjryan** [fermiPy/fermipy#381]
Hello!

I am an undergraduate at UCSC using fermipy to analyze the source Mrk 421. I have produced 1 day and 2 day binned lightcurves using fermipy, but I have encountered what I call "problematic time periods" where there exists no good GTI (Good time interval) in a photon fits file. These Periods of no GTI have lasted anywhere from a day to a month. In my original analysis I believe there existed a month period where Fermi-LAT was down due to some maintenance issue, so a lack of GTI made sense. 

However, I have recently begun adding new data to my lightcurve, and there exists a 4 month period (MJD 58815-58927) where no GTI exists but there is relevant photon events. This can visually be seen in the attached plot, where I have plotted the GTI against itself on the left, and I have plotted the photon events against itself on the right. Furthermore, the automatically generated lightcurve on the Fermi website has data points for this time period. So, there is a bit of a conundrum.

Given fermipy breaks whenever a bin has no GTI, I can not analyze this 4 month time period despite there existing plenty of photon events. And, I am unsure of how to fix it. Any help is appreciated. If you are interested in the original "problematic time periods"  I mentioned then they can be found at the very bottom of the attached link.

Lastly, whenever a GTI error occurs while computing a lightcurve, fermipy's analysis breaks and does not appear to save the previously computed bins. I feel like fermipy should have the ability to skip problematic days and continue the analysis, outputting any problematic periods to a file. But, I do not know if this option exists or if it is easy to implement into fermipy.

Much thanks!
Will

Attachments area
https://wjryan.github.io/William-J-Ryan/fermipy_guide.html
![discrepency (1)](https://user-images.githubusercontent.com/43651659/107305398-c83b3100-6a37-11eb-9c19-afc94734b256.PNG)

**Comment by henrikef** [comment]
Hi @wjryan !

Could you please try installing the new versions `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open this issue you still get the same error after a fresh install of the new versions.
