### ISSUE TITLE
Error with gta.write_roi()

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#384]
Hello everyone,

I am using:
fermipy version v1.0.0 with the branch p3_master. Thus this version includes the latest changes that @ndilalla did.
ScienceTools version 2.0.8
I have Astropy 4.2 installed.
When I do gta.write_roi() I get the following error. I tried with different ROIs and the error still remains.

In [4]: gta.write_roi('roi_optimized_newsources_TS64')
2021-03-06 23:51:52 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/slac/kipac/fs1/u/dmcat/workdir/mattia/GC_DMPSR/try/GCexcess_extension_energy/Alt_IEM_baseline/ROI40x40/TestMacias2021/test_findsources/roi_optimized_newsources_TS64_00.xml...
2021-03-06 23:51:52 INFO    GTAnalysis.write_fits(): Writing /nfs/slac/kipac/fs1/u/dmcat/workdir/mattia/GC_DMPSR/try/GCexcess_extension_energy/Alt_IEM_baseline/ROI40x40/TestMacias2021/test_findsources/roi_optimized_newsources_TS64.fits...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/astropy-4.2-py3.7-linux-x86_64.egg/astropy/table/table.py in insert_row(self, index, vals, mask)
   2812 
-> 2813                 newcol = col.insert(index, val, axis=0)
   2814 

/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/astropy-4.2-py3.7-linux-x86_64.egg/astropy/table/column.py in insert(self, obj, values, axis)
   1196         else:
-> 1197             self_for_insert = _expand_string_array_for_values(self, values)
   1198             data = np.insert(self_for_insert, obj, values, axis=axis)

/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/astropy-4.2-py3.7-linux-x86_64.egg/astropy/table/column.py in _expand_string_array_for_values(arr, values)
    146         # Find the length of the longest string in the new values.
--> 147         values_str_len = np.char.str_len(values).max()
    148 

<__array_function__ internals> in str_len(*args, **kwargs)

/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/numpy/core/defchararray.py in str_len(a)
    282     # due to the dtype itemsize limitation.
--> 283     return _vec_string(a, int_, '__len__')
    284 

TypeError: string operation on non-string array

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-b283f20a3e38> in <module>
----> 1 gta.write_roi('roi_optimized_newsources_TS64')

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in write_roi(self, outfile, save_model_map, **kwargs)
   3720 
   3721         self.write_xml(xmlfile)
-> 3722         self.write_fits(fitsfile)
   3723 
   3724         if not self.config['gtlike']['use_external_srcmap']:

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in write_fits(self, fitsfile)
   3758         self.logger.info('Writing %s...', fitsfile)
   3759 
-> 3760         tab = self.roi.create_table()
   3761         hdu_data = fits.table_to_hdu(tab)
   3762         hdu_data.name = 'CATALOG'

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/roi_model.py in create_table(self, names)
   2222             if names is not None and s.name not in names:
   2223                 continue
-> 2224             s.add_to_table(tab)
   2225 
   2226         return tab

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/roi_model.py in add_to_table(self, tab)
    520 
    521         row = [row_dict[k] for k in tab.columns]
--> 522         tab.add_row(row)
    523 
    524     def get_catalog_dict(self):

/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/astropy-4.2-py3.7-linux-x86_64.egg/astropy/table/table.py in add_row(self, vals, mask)
   2703              3   6   9
   2704         """
-> 2705         self.insert_row(len(self), vals, mask)
   2706 
   2707     def insert_row(self, index, vals=None, mask=None):

/nfs/slac/kipac/fs1/u/mdimauro/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/astropy-4.2-py3.7-linux-x86_64.egg/astropy/table/table.py in insert_row(self, index, vals, mask)
   2835         except Exception as err:
   2836             raise ValueError("Unable to insert row because of exception in column '{}':\n{}"
-> 2837                              .format(name, err))
   2838         else:
   2839             self._replace_cols(columns)

ValueError: Unable to insert row because of exception in column 'Spatial_Filename':
string operation on non-string array

**Comment by eacharles** [comment]
This looks like it is coming in b/c you have astropy 4.2 which is incompatible with the other stuff.   This should be fixed by the new installation scheme, which will handle the dependecies better.
