### ISSUE TITLE
Installation of Fermipy

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#385]
Dear all,

I have:
fermipy version v1.0.0 and in particular I am using the master of the py3_master with the latest updates done by @ndilalla 
ScienceTools version 2.0.8
When I checked-out the fermipy version in py3_master I did python setup.py develop --user to install it and the installation went well. However, when it is checking the dependencies it gets this error:
Installed /nfs/slac/kipac/fs1/u/mdimauro/software/fermipy
Processing dependencies for fermipy==1.0.0+1.ge6ba.dirty
error: astropy 3.2.3 is installed but astropy>=4.0 is required by {'gammapy'}
However, I have installed satrapy 4.2. In facto if I do conda list I get:
astropy                   4.2                      pypi_0    pypi

**Comment by eacharles** [comment]
I've update the installation instructions and put in an environment.yml file to make it much easier to install fermipy from source.   This will be in version 1.0.1
