### ISSUE TITLE
Error with gta.load_roi()

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#386]
Hello everyone,

I am having also an error using gta.load_roi()
The error is the following:

In [7]: gta.load_roi('roi_final')
2021-03-07 13:04:29 INFO    GTAnalysis.load_roi(): Loading ROI file: /nfs/slac/kipac/fs1/u/mdimauro/workdir/dmcat/multitargets/Clusteranalysis/Test_PL/roi_10/roi_final.npy
2021-03-07 13:04:29 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-c7c92ddd7d4d> in <module>
----> 1 gta.load_roi('roi_final')

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in load_roi(self, infile, reload_sources, params, mask)
   3658             self._lck_params = copy.deepcopy(lck_params)
   3659 
-> 3660         self._create_likelihood(infile)
   3661         self.set_energy_range(self.loge_bounds[0], self.loge_bounds[1])
   3662 

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in _create_likelihood(self, srcmdl)
   1110         self._like = SummedLikelihood()
   1111         for c in self.components:
-> 1112             c._create_binned_analysis(srcmdl)
   1113             self._like.addComponent(c.like)
   1114 

/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py in _create_binned_analysis(self, xmlfile, **kwargs)
   5439         self.logger.debug('Updating source maps')
   5440         if not self.config['gtlike']['use_external_srcmap']:
-> 5441             self.like.logLike.saveSourceMaps(str(self.files['srcmap']))
   5442 
   5443         # Apply exposure corrections

~/kipac/software/anaconda/envs/fermipy-py3/lib/python3.7/site-packages/fermitools/pyLikelihood.py in saveSourceMaps(self, *args)
  12216     def saveSourceMaps(self, *args):
  12217         r"""saveSourceMaps(BinnedLikelihood self, std::string const & filename="", bool replace=False, bool includecountsmap=True)"""
> 12218         return _pyLikelihood.BinnedLikelihood_saveSourceMaps(self, *args)
  12219 
  12220     def saveSourceMap_partial(self, filename, source, kmin=0, kmax=-1, replace=False):

RuntimeError: Unable to create file named "/nfs/slac/kipac/fs1/u/mdimauro/workdir/dmcat/multitargets/Clusteranalysis/Test_PL/roi_10/srcmap_00.fits" (CFITSIO ERROR 105: couldn't create the named file)

**Comment by eacharles** [comment]
This is typically caused by a previous step failing, which in this case is likely b/c of an incompatible version of fermitools or astropy.   Lets see if version 1.0.1 installation solves this.
