### ISSUE TITLE
Adding a custom model

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#39]
Hi Matthew,
 Me and Marco are trying to use fermipy to study EBL effects in blazars. I noticed that in fermipy I can change the model type, say from power law to log parabola etc. using delete_source and add_source tool. Is it possible to include EBL attenuated models within fermipy? For example,
https://confluence.slac.stanford.edu/display/ST/Likelihood+Usage+Notes#LikelihoodUsageNotes-EBLAttenuationmodels%2820June2009%29
Actually fermipy has made the Fermi analysis very efficient and therefore we are keen to use it for EBL related study also. Please let me know if it is possible.
Thank you very much.
Vaidehi

**Comment by woodmd** [comment]
It should be possible to use any of the models defined in the STs with fermipy as long as you pass the appropriate string for ``SpectrumType``.  For instance you should be able to use the following dictionary argument to add_source to instantiate a "EblAtten::PowerLaw2" model:
```
{'SpectrumType' : EblAtten::PowerLaw2', 'Integral' : 1E-06, 
'LowerLimit' : 20.0, 'UpperLimit' : 2E5, 'tau_norm' : 1.0, 'redshift' : 0.5, 'ebl_model' : 0 }
```
Note that I haven't actually tested fermipy with the EBL models myself so if you run into any issues please post the error log here.

**Comment by vaidehiratna** [comment]
Thanks for the help. I tried for a source but faced an error as mentioned below.
The source is having default 3FGL model as log parabola and to change it to EBL model, I first deleted it and then added as a new source using following command
>>> gta.delete_source('3FGL J1504.4+1029')
>>> gta.add_source('3FGL J1504.4+1029',{ 'ra' : 226.10458, 'dec': 10.49358, 'SpectrumType' : 'EblAtten::PowerLaw2', 'Integral' : 1e-06, 'Index' : -2.0, 'LowerLimit' : 20.0, 'UpperLimit' : 2e5, 'tau_norm' : 1.0, 'redshift' : 1.838, 'ebl_model' : 0, 'SpatialModel' : 'PointSource' })

First command ran without any issue but the second one threw the following error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.8.0+22.g11ac-py2.7.egg/fermipy/gtanalysis.py", line 1006, in add_source
    self._update_roi()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.8.0+22.g11ac-py2.7.egg/fermipy/gtanalysis.py", line 405, in _update_roi
    rm['loglike'] = -self.like()
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-00-00/python/SummedLikelihood.py", line 112, in __call__
    negLogLike = -self.composite.value()
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-00-00/python/pyLikelihood.py", line 8597, in value
    return _pyLikelihood.SummedLikelihood_value(*args)
RuntimeError: vector::_M_range_check

I am using ST version 11-00-00 in SLAC and thought the error could be due to the new version of ST and so tried with an older version 10-00-04 but the issue persists.
Please help.
Thanks.

**Comment by woodmd** [comment]
I'm not able to reproduce this error using fermipy 0.9.2-35-ge73f5d9 and ST 11-01-01.  Could you try upgrading to the latest version of fermipy and STs?

**Comment by vaidehiratna** [comment]
Well, I am trying to upgrade fermipy in SLAC since last 2 days but it gets hanged as follows
pip install fermipy --user --upgrade --no-deps
Collecting fermipy
  Downloading fermipy-0.9.2.tar.gz (11.7MB)
    99% |############################### | 11.7MB 19.6MB/s eta 0:00:01

I will keep trying and will let you know the results as soon as I get them.

**Comment by woodmd** [comment]
Actually for now it's probably better for you to run with the HEAD version of the package since that's the version I've been running to test the errors you were seeing.  There are instructions for installing from source here:

http://fermipy.readthedocs.io/en/latest/install.html#building-from-source

**Comment by vaidehiratna** [comment]
I just followed your suggestions. It is working now with no errors. Thanks.
