### ISSUE TITLE
CFITSIO ERROR 202 due to missing keyword in header of srcmap-file

### ISSUE THREAD

**Issue by agokus** [fermiPy/fermipy#396]
Hello,
I get an error regarding a missing header after gtsrcmaps, whose origin I cannot pin-point.
I have found another closed issue here on Github with the same error (Issue #253), however my problem does not occur due to the same circumstances. 
I am performing a standard analysis using the sources in the 4FGL, and I'm not adding an additional source.
I use
fermipy version 0.20.0
ScienceTools 1.2.23
python 2.7.
The full output of my analysis is attached in the text file.

I seem to encounter an error during the computation of the source map of one of the sources in the ROI, namely
`2021-03-26 21:07:08 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 4FGL J0058.0-7245e 10Caught N10facilities14UntranslatableE at the top level: LATEXTDIR`
This seems to lead to the crash (or at least I think so).
I'm running this on a cluster of my Institute, and, now it gets super-weird, when I run the same analysis (same versions of the tools, same diffuse files, etc.) on my own laptop, I don't get this error and the analysis works just fine.
I'm wondering whether there is something I overlooked, when setting up fermipy on our Institute's cluster.

I very much appreciate your feedback on this!

[output_fermipy_analysis.txt](https://github.com/fermiPy/fermipy/files/6221650/output_fermipy_analysis.txt)

**Comment by agokus** [comment]
Well, I have found the solution for this error message, actually. It seems the LATEXTDIR is a variable linking to the extended source templates, which has not been properly set on the machines of my Institute.

**Comment by Time-Cheung** [comment]
Hello, I got the same error,. Could you tell me how did you deal with it in more detail? Thanks!

**Comment by agokus** [comment]
Hi, so as I wrote, the global variable named LATEXTDIR is not set in the shell you are working on. This variable links to the templates for extended sources, like components of the large magellanic cloud. If you are analysing a source without an extended source in your ROI, you don't notice that it might not be set correctly yet.
I fixed this by adding the following to my .cshrc file:
`setenv LATEXTDIR $FERMI_DIR/4FGL_extended_sources`
where $FERMI_DIR is another variable that should link to where the catalog file are stored. At this place, there should be the folder that includes the templates for your extended sources.
If you are working with a bash-shell, the command to add to your .bashrc file would be:
`export LATEXTDIR=$FERMI_DIR/4FGL_extended_sources`

**Comment by Time-Cheung** [comment]
> Hi, so as I wrote, the global variable named LATEXTDIR is not set in the shell you are working on. This variable links to the templates for extended sources, like components of the large magellanic cloud. If you are analysing a source without an extended source in your ROI, you don't notice that it might not be set correctly yet.
> I fixed this by adding the following to my .cshrc file:
> `setenv LATEXTDIR $FERMI_DIR/4FGL_extended_sources`
> where $FERMI_DIR is another variable that should link to where the catalog file are stored. At this place, there should be the folder that includes the templates for your extended sources.
> If you are working with a bash-shell, the command to add to your .bashrc file would be:
> `export LATEXTDIR=$FERMI_DIR/4FGL_extended_sources`

Thank you very much for your reply! Where can I find the path of FERMI_DIR? Like "/home/Fermi/Fermi_data/LAT_extended_sources_8years/Templates"?
