### ISSUE TITLE
Add GTAnalysis.create() method

### ISSUE THREAD

**Issue by woodmd** [fermiPy/fermipy#4]
Currently reloading the analysis from a previous state requires the user to manually instantiate a new GTAnalysis object and then call setup() and load_roi().  The create() method would combine this into a single static method that would accept an output file generated with write_roi() and return a new GTAnalysis object.

**Comment by woodmd** [comment]
Now implemented in e735b985167c1531dc5751ae4debbd8f94123f02.

**Comment by terrijb** [comment]
Great!
And verified with different file structure.
