### ISSUE TITLE
Question Regarding Fermipy TS Calculations

### ISSUE THREAD

**Issue by pjstanley1** [fermiPy/fermipy#401]
I had a few questions regarding Fermipy and how the source TS values are calculated. I have looked over the documentation but haven't been able to find anything about how the source TS values are calculated. 

Thus far I have been unable to reproduce the output source TS values starting from the log likelihood values. Then which "null" log likelihood value is used for the source TS calculation, and is there some way to output this?

**Comment by henrikef** [comment]
See the last paragraph here: https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Likelihood/Likelihood_overview.html 

Does this help? 

As for how to reproduce: Save the overall likelihood value after optimizing and fitting your ROI. Then, remove the source you are interested in from the model, re-optimize and fit and get the new likelihood value. From these two values you should be able to calculate the TS.

Please re-open this if you have further questions.
