### ISSUE TITLE
Missing check for failed LC bins in lightcurve.py (KeyError: fit_success)

### ISSUE THREAD

**Issue by agokus** [fermiPy/fermipy#405]
Hi,
after getting a `KeyError: fit_success` error message and looking into the lightcurve.py file, I found that the code misses an additional check whether the fit for a light curve bin has been performed. In line 450 of the lightcurve.py script, it is checked, whether the fit was successful, however, there is no check whether a fit was even performed. This results in a crash at the end, when all light curve bins have been computed and the results are put together in one light curve fits file, and gives me a keyerror for fit_success, because at least one bin has not been fit at all.

I'm using fermipy version 0.20.0, however, I also checked the current one and I think the error will still occur, if something breaks in one bin (see line 452 in lightcurve.py of the current version).

**Comment by henrikef** [comment]
This should be fixed in `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
