### ISSUE TITLE
Installation of fermipy 1.0.1

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermiPy/fermipy#408]
I was trying to install fermipy 1.0.1 following `conda-based installation' from [https://fermipy.readthedocs.io/en/latest/install.html](url). 
When I gave ' conda create --name fermipy -c conda-forge -c fermipy python=3.7 fermitools=2.0.8' , following was the output

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fermitools=2.0.8

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/fermipy/linux-64
  - https://conda.anaconda.org/fermipy/noarch
  - http://ssb.stsci.edu/astroconda/linux-64
  - http://ssb.stsci.edu/astroconda/noarch
  - https://conda.anaconda.org/astropy/linux-64
  - https://conda.anaconda.org/astropy/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I can not understand what should I do now. Kindly, let me know the possible solution(s).

**Comment by Malikzahoor** [comment]
Hi ..For conda based installation on python3 use following two commands instead to install fermitools and fermipy...

conda create -n fermipy -c conda-forge -c fermi fermitools python=3

conda install --name fermipy -c conda-forge fermipy

It will work for you.

**Comment by Sanjuphysics12** [comment]
Problem solved. Thank you @Malikzahoor .
