### ISSUE TITLE
Issue in generating lighcurve.npy file

### ISSUE THREAD

**Issue by Malikzahoor** [fermiPy/fermipy#409]
Hi,
After running the required commands for the lc generation, the process goes to the end by finishing the fit to the last time interval. But the whole process gets stuck there without giving the required files (lightcurve.npy, lightcurve. fits). This I m running for the weekly lightcurve while before this I generated the files for monthly binned lightcurve successfully. 

While having a manual check I found there is a problem with some weeks having no GTIs. By skipping them manually the lightcurve generation works. Is there any option to skip the problematic time intervals as it is and get a lightcurve with the remaining time without doing it manually? 

Will be thankful for any solutions.

I'm using the latest version of fermipy version 1.0.1 with python 3.

**Comment by jleagle94** [comment]
#368

**Comment by Sanjuphysics12** [comment]
@Malikzahoor, I am facing the same problem. Did you get the solution?
