### ISSUE TITLE
`maxit'

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermiPy/fermipy#410]
I encountered with this warning message during running gta.optimize() & gta.sed(). I have checked the `fitpack2.py' file. It is not clear to me how to increase the number of iteration. Kindly, let me know how to solve the following warning.

........fermipy/lib/python3.7/site-packages/scipy/interpolate/fitpack2.py:279: UserWarning: 

The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

**Comment by henrikef** [comment]
I believe it is ok to ignore this warning.
