### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'params' as almost every output

### ISSUE THREAD

**Issue by lenzo0611** [fermiPy/fermipy#412]
Yesterday, I worked on my analysis of an object and everything worked fine. However, today when I tried to run the code again almost every line resulted in an error message like this:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-5d29dbb23149> in <module>
----> 1 gta.write_roi('fit1.npy')

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py in write_roi(self, outfile, save_model_map, **kwargs)
   3719         npyfile = pathprefix + '.npy'
   3720 
-> 3721         self.write_xml(xmlfile)
   3722         self.write_fits(fitsfile)
   3723 

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py in write_xml(self, xmlfile)
   3266         """
   3267         for c in self._components:
-> 3268             c.write_xml(xmlfile)
   3269 
   3270     def load_parameters_from_yaml(self, yamlfile, update_sources=False):

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py in write_xml(self, xmlfile)
   5763         xmlfile = self.get_model_path(xmlfile)
   5764         self.logger.info('Writing %s...', xmlfile)
-> 5765         self.like.writeXml(str(xmlfile))
   5766 
   5767     def get_model_path(self, name):

AttributeError: 'NoneType' object has no attribute 'writeXml'`

I am quite new to python and fermipy, so maybe this is an easy to solve problem. If you need any more information I am happy to provide it. 

Thanks

**Comment by henrikef** [comment]
@lenzo0611 were you able to resolve this issue or are you still getting the same error? If so, please try upgrading to `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
