### ISSUE TITLE
KeyError: 'fit_success' when running gta.lightcurve

### ISSUE THREAD

**Issue by sushmitaagarwal** [fermiPy/fermipy#415]
I followed the Quickstart quide and started with:
`from fermipy.gtanalysis import GTAnalysis`
`gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})`
`gta.setup()`

The setup was complete and I continued with:

`gta.optimize()`
`gta.print_roi()`

I am trying to generate the lightcurve using :
`lc = gta.lightcurve('source_name, binsz=86400.*1.0, free_radius=5.0, use_scaled_srcmap=True)`

I am getting this error:
>>> lc = gta.lightcurve('source_name', binsz=86400.*1.0, free_radius=5.0, use_scaled_srcmap=True)
2021-06-30 18:38:37 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for 4FGL J1833.6-2103
2021-06-30 18:38:39 INFO    lightcurve_567648005_567734405 GTAnalysis._process_lc_bin(): Fitting time range 567648005 567734405
2021-06-30 18:38:39 INFO    lightcurve_567648005_567734405 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [fermipy.ltcube]
/home/user/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/irfs.py:51: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  log_ratio = np.log(x[xs1] / x[xs0])
/home/user/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/irfs.py:52: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return 0.5 * (y[ys0] * x[xs0] + y[ys1] * x[xs1]) * log_ratio
Analysis failed in time range 567648005 567734405
<class 'FileNotFoundError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 289, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/user/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 452, in _make_lc
    if not next_fit['fit_success']:
KeyError: 'fit_success'

My fermipy version  is v1.0.1  and ScienceTools version 2.0.8.
Please let me know what might me going wrong?

**Comment by basuparth** [comment]
Please refer to this issue [https://github.com/fermiPy/fermipy/issues/368](url)

**Comment by sushmitaagarwal** [comment]
Got it! Thanks
