### ISSUE TITLE
Issue in generating long term lightcurve

### ISSUE THREAD

**Issue by Malikzahoor** [fermiPy/fermipy#417]
Hi,
While generating the lightcurve of a source using the command 
lc = gta.lightcurve('Source_name', free_params=['Prefactor'], time_bins=binLC, multithread=True,use_scaled_srcmap=True)
i binned the lightcurve in 800 bins(2 day binning). While running for the 800 bins the lightcurve generation goes to the end and gets stuck there without giving any files(i waited for a whole day long at the stuck point). Then used the same command for 200 bins each for all 800 bins ...then the lightcurve generation is ok and giving the required files(Here 4 .npy files). So that means even though there is no error or absence of GTIs in any of the bin why then it gets stuck for long time data lc generation.
Any solutions please ....
Thanks in advance.

**Comment by henrikef** [comment]
Hi @Malikzahoor! Could you please try installing the new versions `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
