### ISSUE TITLE
Weird long number printout from print_roi() method after running a fit 

### ISSUE THREAD

**Issue by Pfesi** [fermiPy/fermipy#420]
Good day,
I've been working on my analysis using jupyter notebooks and have come across some mysterious errors. So when I try to view my ROI after fitting the data I get the following output.

<img width="1073" alt="Screenshot 2021-07-15 at 18 17 11" src="https://user-images.githubusercontent.com/17878158/126631007-8b6f6c1b-9d31-4483-80b6-89564aec0bf6.png">

There is a problem writing the output and not sure where this is. I'm using fermipy version v1.0.1 and 
ScienceTools version 2.0.8 . Any help on resolving this will be much appreciated. Cheers.

**Comment by henrikef** [comment]
Hi @Pfesi , were you able to resolve this? To me it looks like you have some sources with a TS that is much larger than it should be. Does this persist in `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions.

**Comment by henrikef** [comment]
Please re-open if this is still a problem in `fermitools 2.2.0` and `fermipy 1.1.5` or later.
