### ISSUE TITLE
tupple error

### ISSUE THREAD

**Issue by GajVan** [fermiPy/fermipy#423]
/home/gajanan/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/irfs.py:52: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return 0.5 * (y[ys0] * x[xs0] + y[ys1] * x[xs1]) * log_ratio

**Comment by henrikef** [comment]
This should be fixed in `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.

**Comment by GajVan** [comment]
Thank you for your response
I already resolved the issue
