### ISSUE TITLE
RuntimeError: Cannot read keyword "NDSKEYS" in file [srcmap_00.fits] (CFITSIO ERROR 202: keyword not found in header) 2

### ISSUE THREAD

**Issue by llsico** [fermiPy/fermipy#428]
Hi everyone,

I'm trying to perform an analysis using fermipy version v1.0.1 and ScienceTools version 2.0.8.

But, when I do I get an error and I'm not able to find out why. The traceback is as follow:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_105392/1244684129.py in <module>
----> 1 gta.setup()

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, init_sources, overwrite, **kwargs)
   1083 
   1084         # Create likelihood
-> 1085         self._create_likelihood()
   1086 
   1087         # Determine tmin, tmax

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py in _create_likelihood(self, srcmdl)
   1110         self._like = SummedLikelihood()
   1111         for c in self.components:
-> 1112             c._create_binned_analysis(srcmdl)
   1113             self._like.addComponent(c.like)
   1114 

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py in _create_binned_analysis(self, xmlfile, **kwargs)
   5400         self.logger.debug(kw)
   5401 
-> 5402         self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
   5403 
   5404 

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermitools/BinnedAnalysis.py in __init__(self, srcMaps, expCube, binnedExpMap, irfs, phased_expmap)
     69         # EAC switch to using AppHelpers...
     70         self.countsMap = pyLike.AppHelpers_readCountsMap(srcMaps)
---> 71         self._createObservation(srcMaps, expCube, self.irfs)
     72     def _createObservation(self, srcMaps, expCube, irfs):
     73         self._respFuncs = pyLike.ResponseFunctions()

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermitools/BinnedAnalysis.py in _createObservation(self, srcMaps, expCube, irfs)
     72     def _createObservation(self, srcMaps, expCube, irfs):
     73         self._respFuncs = pyLike.ResponseFunctions()
---> 74         self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
     75         self._expMap = pyLike.ExposureMap()
     76         self._scData = pyLike.ScData()

~/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermitools/pyLikelihood.py in load_with_event_types(self, respFuncs, respBase, filename, extname)
   6592     def load_with_event_types(self, respFuncs, respBase, filename, extname):
   6593         r"""load_with_event_types(ResponseFunctions self, std::string const & respFuncs, std::string const & respBase, std::string const & filename, std::string const & extname)"""
-> 6594         return _pyLikelihood.ResponseFunctions_load_with_event_types(self, respFuncs, respBase, filename, extname)
   6595 
   6596 # Register ResponseFunctions in _pyLikelihood:

RuntimeError: Cannot read keyword "NDSKEYS" in file "/home/llsiconato/Documents/Docs/Estudos/Grad_studies/Mestrado/Fermi/notebooks/projeto_sagitario/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)
```

This is a similar error to the one found in #425 but my situation is other, nonetheless. For my analysis, I have downloaded the weekly photons files, so I haven't chosen an energy range before to download the photons! I also have downloaded in the same way the spacecraft file of all mission. 

[Here is](https://github.com/fermiPy/fermipy/files/7289290/ERRO2.txt) my full terminal output, in case it is needed. 

Edit: I saw in other issues that some other things could be useful. So, the message from gta.setup() that I have before the error occurring is:

`021-10-06 21:09:18 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 4FGL J1713.5-3945e 31Caught N10facilities14UntranslatableE at the top level: LATEXTDIR
2021-10-06 21:09:18 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 62.65 s
2021-10-06 21:09:18 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2021-10-06 21:09:18 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component `00.``
[My YAML config file is this one](https://github.com/fermiPy/fermipy/files/7297764/config.txt)

I already tried to do the analysis with different tmin, tmax, another target source, other PSF selections, for example, in all of that, I get the error.

**Comment by henrikef** [comment]
@llsico  Does this issue persist with `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. Please make sure to delete and recreate all intermediate data files such as the `srcmap_00.fits` etc. Please let me know if still get the same error after a fresh install of the new versions.

**Comment by henrikef** [comment]
Please re-open if this is still a problem in `fermitools 2.2.0` and `fermipy 1.1.5` or later.

**Comment by shiqiyugit** [comment]
is it resolved? I'm seeing the same error with fermipy-1.3.1 and fermitool 2.2.0
