### ISSUE TITLE
Failed to resolve file path 

### ISSUE THREAD

**Issue by parth161** [fermiPy/fermipy#434]
While trying to do Quickstart guide on fermipy site, after running command `gta = GTAnalysis('/Users/parthpatil/mkn421/config.yaml',logging={'verbosity' : 3})` in Jupiter notebook. I am getting following error 
I am using Mac OS 12.1, I am on a intel Mac.

_2022-01-13 10:44:47 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version v1.0.1 
ScienceTools version 2.0.8_

`Exception                                 Traceback (most recent call last)
/var/folders/1m/9zsw2wb541g3rmdrtz0x2sb00000gn/T/ipykernel_2915/1700897548.py in <module>
----> 1 gta = GTAnalysis('/Users/parthpatil/mkn421/config.yaml',logging={'verbosity' : 3})

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py in __init__(self, config, roi, **kwargs)
    349                                         configs[0]['model'],
    350                                         fileio=configs[0]['fileio'],
--> 351                                         coordsys=configs[0]['binning']['coordsys'])
    352         else:
    353             self._roi = roi

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in create(cls, selection, config, **kwargs)
   1744         if selection['target'] is not None:
   1745             return cls.create_from_source(selection['target'],
-> 1746                                           config, **kwargs)
   1747         else:
   1748             target_skydir = wcs_utils.get_target_skydir(selection)

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in create_from_source(cls, name, config, **kwargs)
   1774 
   1775         roi = cls(config, src_radius=None, src_roiwidth=None,
-> 1776                   srcname=name, **kwargs)
   1777         src = roi.get_source_by_name(name)
   1778 

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in __init__(self, config, **kwargs)
   1350         self._src_radius = []
   1351 
-> 1352         self.load(coordsys=coordsys, srcname=srcname)
   1353 
   1354     def __contains__(self, key):

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in load(self, **kwargs)
   1682 
   1683         self.clear()
-> 1684         self.load_diffuse_srcs()
   1685 
   1686         for c in self.config['catalogs']:

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in load_diffuse_srcs(self)
   1437     def load_diffuse_srcs(self):
   1438 
-> 1439         srcs = self.create_diffuse_srcs(self.config)
   1440         for src in srcs:
   1441             self.load_source(src, False, self.config['merge_sources'])

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in create_diffuse_srcs(self, config)
   1445         srcs = []
   1446         srcs += self._create_diffuse_src('isodiff', config)
-> 1447         srcs += self._create_diffuse_src('galdiff', config)
   1448         srcs += self._create_diffuse_src('limbdiff', config)
   1449         srcs += self._create_diffuse_src('diffuse', config)

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/roi_model.py in _create_diffuse_src(self, name, config, src_type)
   1483             src_dict['file'] = \
   1484                 utils.resolve_file_path(src_dict['file'],
-> 1485                                         search_dirs=search_dirs)
   1486 
   1487             if 'name' not in src_dict:

/opt/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/utils.py in resolve_file_path(path, **kwargs)
    119 
    120     if out_path is None:
--> 121         raise Exception('Failed to resolve file path: %s' % path)
    122 
    123     if expand:

Exception: Failed to resolve file path: $FERMI_DIFFUSE_DIR/gll_iem_v06.fits
`

**Comment by basuparth** [comment]
Hi, seems like it can't locate the galactic diffuse model. Firstly v06 is not the latest version. So you might want to replace that with the latest version. And if it still persists try specifying the direct address to the diffuse model. It should look something like this 

' . . . .  ./anaconda3/envs/fermi/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits'

**Comment by henrikef** [comment]
@parth161 were you able to resolve the issue?
