### ISSUE TITLE
Dependencies and version incompatibilities

### ISSUE THREAD

**Issue by henrikef** [fermiPy/fermipy#437]
- Release 1.0.1 is incompatible with newer versions of matplotlib, but can still be made to work by pinning matplotlib and CLHEP to older versions, e.g. `mamba create -n fermi_old -c conda-forge -c fermipy -c fermi python=3.7 fermitools=2.0.8 fermipy clhep=2.4.4.1 matplotlib=3.2.1`

- Current github master depends on `gammapy>0.18`, which needs astropy 4, which is incompatible with fermitools 2.0.8 (latest release). Incompatibilities with matplotlib 3.5 have been fixed (see e.g. https://github.com/fermiPy/fermipy/pull/435 , https://github.com/fermiPy/fermipy/pull/400 ), but I can't find a combination of dependency versions that allows all tests to pass. We will probably need to wait for the next release of `fermitools`.

**Comment by MassimoCapasso90** [comment]
Hi Henrike, I see you have been working on some issues I have been finding, so I'll post my comment here. I was testing the version Leonardo posted here https://github.com/fermiPy/fermipy/issues/431 with support for PLSuperExpCutoff4. Here are the fermipy dependencies I am using 

- python 3.7.12 hb7a2778_100_cpython    conda-forge
- pyyaml 6.0              py37h5e8e339_3    conda-forge
- numpy 1.21.5           py37hf2998dd_0    conda-forge
- scipy 1.7.3            py37hf2a6cf1_0    conda-forge
- astropy 3.2.3            py37h516909a_0    conda-forge
- matplotlib 3.5.1            py37h89c1867_0    conda-forge
- healpy 1.15.0           py37hd0552aa_2    conda-forge
- astropy-healpix 0.6              py37hb1e94ed_1    conda-forge
- gammapy 0.18.2           py37h5e8e339_0    conda-forge
- fermitools 2.0.8                h3fd9d12_0    fermi

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_228135/3035176867.py in <module>
     10 
     11 #print("ts_exclude_list ", ts_exclude_list)
---> 12 resmap_initial = gta.residmap(prefix+"_initial", model=model, make_plots=True,write_fits=True,write_npy=True)
     13 #resmap = gta.residmap(prefix, model=model, make_plots=True,write_fits=True,write_npy=True)

~/software/fermipy/fermipy/residmap.py in residmap(self, prefix, **kwargs)
    263                                                logging=self.config['logging'])
    264 
--> 265             plotter.make_residmap_plots(o, self.roi)
    266 
    267         self.logger.info('Finished residual maps')

~/software/fermipy/fermipy/plotting.py in make_residmap_plots(self, maps, roi, **kwargs)
   1014         p.plot(vmin=-5, vmax=5, levels=sigma_levels,
   1015                cb_label='Significance [$\sigma$]', interpolation='bicubic',
-> 1016                cmap=cmap_resid, zoom=zoom)
   1017         plt.savefig(utils.format_filename(workdir,
   1018                                           'residmap_sigma',

~/software/fermipy/fermipy/plotting.py in plot(self, **kwargs)
    599         cb_kwargs = merge_dict(cb_kwargs, kwargs)
    600 
--> 601         im, ax = self._implot.plot(**im_kwargs)
    602 
    603         self._ax = ax

~/software/fermipy/fermipy/plotting.py in plot(self, subplot, cmap, **kwargs)
    325         kwargs_contour = merge_dict(kwargs_contour, kwargs)
    326 
--> 327         im = ax.imshow(data, **kwargs_imshow)
    328         im.set_cmap(colormap)
    329 

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py in imshow(self, X, *args, **kwargs)
    200                 X = X.transpose(FLIP_TOP_BOTTOM)
    201 
--> 202         return super().imshow(X, *args, origin=origin, **kwargs)
    203 
    204     def contour(self, *args, **kwargs):

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/_api/deprecation.py in wrapper(*args, **kwargs)
    454                 "parameter will become keyword-only %(removal)s.",
    455                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 456         return func(*args, **kwargs)
    457 
    458     # Don't modify *func*'s signature, as boilerplate.py needs it.

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1410     def inner(ax, *args, data=None, **kwargs):
   1411         if data is None:
-> 1412             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1413 
   1414         bound = new_sig.bind(ax, *args, **kwargs)

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, interpolation_stage, filternorm, filterrad, resample, url, **kwargs)
   5491             # image does not already have clipping set, clip to axes patch
   5492             im.set_clip_path(self.patch)
-> 5493         im._scale_norm(norm, vmin, vmax)
   5494         im.set_url(url)
   5495 

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/cm.py in _scale_norm(self, norm, vmin, vmax)
    379             if norm is not None:
    380                 raise ValueError(
--> 381                     "Passing parameters norm and vmin/vmax simultaneously is "
    382                     "not supported. Please pass vmin/vmax directly to the "
    383                     "norm when creating it.")

ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

I tried to hack it as follows, and it seems not to complain (not sure if it is a good implementation, but in this way both norm and vmin,vmax can be used as documented here https://matplotlib.org/stable/tutorials/colors/colormapnorms.html)

    def plot(self, subplot=111, cmap='magma', vmin=None, vmax=None, **kwargs):

        kwargs_contour = {'levels': None, 'colors': ['k'],
                          'linewidths': 1.0}
        
        #kwargs_imshow = {'interpolation': 'nearest',
        #                 'origin': 'lower', 'norm': None,
        #                 'vmin': None, 'vmax': None}
        
        kwargs_imshow = {'interpolation': 'nearest',
                         'origin': 'lower', 'norm': None}

        zscale = kwargs.get('zscale', 'lin')
        gamma = kwargs.get('gamma', 0.5)
        transform = kwargs.get('transform', None)

        if zscale == 'pow':
            kwargs_imshow['norm'] = PowerNorm(gamma=gamma,vmin=vmin,vmax=vmax)
        elif zscale == 'sqrt':
            kwargs_imshow['norm'] = PowerNorm(gamma=0.5,vmin=vmin,vmax=vmax)
        elif zscale == 'log':
            kwargs_imshow['norm'] = LogNorm(vmin=vmin,vmax=vmax)
        elif zscale == 'lin':
            kwargs_imshow['norm'] = Normalize(vmin=vmin,vmax=vmax)
        else:
            kwargs_imshow['norm'] = Normalize(vmin=vmin,vmax=vmax)
            
           
However, I get the following error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_231157/3035176867.py in <module>
     10 
     11 #print("ts_exclude_list ", ts_exclude_list)
---> 12 resmap_initial = gta.residmap(prefix+"_initial", model=model, make_plots=True,write_fits=True,write_npy=True)
     13 #resmap = gta.residmap(prefix, model=model, make_plots=True,write_fits=True,write_npy=True)

~/software/fermipy/fermipy/residmap.py in residmap(self, prefix, **kwargs)
    263                                                logging=self.config['logging'])
    264 
--> 265             plotter.make_residmap_plots(o, self.roi)
    266 
    267         self.logger.info('Finished residual maps')

~/software/fermipy/fermipy/plotting.py in make_residmap_plots(self, maps, roi, **kwargs)
   1018                                           'residmap_sigma',
   1019                                           prefix=[prefix],
-> 1020                                           extension=fmt))
   1021         plt.close(fig)
   1022 

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/pyplot.py in savefig(*args, **kwargs)
    956 def savefig(*args, **kwargs):
    957     fig = gcf()
--> 958     res = fig.savefig(*args, **kwargs)
    959     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    960     return res

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/figure.py in savefig(self, fname, transparent, **kwargs)
   3017                         ax.patch._cm_set(facecolor='none', edgecolor='none'))
   3018 
-> 3019             self.canvas.print_figure(fname, **kwargs)
   3020 
   3021     def ginput(self, n=1, timeout=30, show_clicks=True,

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2323                         orientation=orientation,
   2324                         bbox_inches_restore=_bbox_inches_restore,
-> 2325                         **kwargs)
   2326             finally:
   2327                 if bbox_inches and restore_bbox:

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/backend_bases.py in wrapper(*args, **kwargs)
   1646             kwargs.pop(arg)
   1647 
-> 1648         return func(*args, **kwargs)
   1649 
   1650     return wrapper

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/_api/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    410                          else deprecation_addendum,
    411                 **kwargs)
--> 412         return func(*inner_args, **inner_kwargs)
    413 
    414     DECORATORS[wrapper] = decorator

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args)
    538             *metadata*, including the default 'Software' key.
    539         """
--> 540         FigureCanvasAgg.draw(self)
    541         mpl.image.imsave(
    542             filename_or_obj, self.buffer_rgba(), format="png", origin="upper",

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    434              (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    435               else nullcontext()):
--> 436             self.figure.draw(self.renderer)
    437             # A GUI class may be need to update a window using this draw, so
    438             # don't forget to call the superclass.

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     71     @wraps(draw)
     72     def draw_wrapper(artist, renderer, *args, **kwargs):
---> 73         result = draw(artist, renderer, *args, **kwargs)
     74         if renderer._rasterizing:
     75             renderer.stop_rasterizing()

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer)
     51         finally:
     52             if artist.get_agg_filter() is not None:

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   2809             self.patch.draw(renderer)
   2810             mimage._draw_list_compositing_images(
-> 2811                 renderer, self, artists, self.suppressComposite)
   2812 
   2813             for sfig in self.subfigs:

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

/a/share/ged/src/miniconda3/envs/fermipy-1.0.1dev/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py in draw(self, renderer, inframe)
    456         self.coords.frame._update_patch_path()
    457 
--> 458         super().draw(renderer, inframe=inframe)
    459 
    460         self._drawn = True

TypeError: draw_wrapper() got an unexpected keyword argument 'inframe'

which seems to be similar to this issue: https://github.com/fermiPy/fermipy/issues/371, but I am definitely using a version of numpy older than 1.16. 

Apologies for the lengthy comment, hope this helps a bit!

**Comment by henrikef** [comment]
Fixed in pre-release.
