### ISSUE TITLE
Not able to analyse LAT data

### ISSUE THREAD

**Issue by ShabnamIyyani** [fermiPy/fermipy#443]
Hi

I have been trying to analyse the Fermi LAT data of a GRB within the 3ML setup. However, I have been encountering issues while running the following commands:

**powl = Powerlaw()
model = Model(PointSource('fit',ra,dec,spectral_shape=powl))
model.display()**

**evfile, scfile = download_LAT_data(ra, dec, 20.0, tstart, tstop, time_type="MET", destination_directory="LAT_trial")

config = FermipyLike.get_basic_config(evfile=evfile,scfile=scfile, ra=ra,dec=dec, fermipy_verbosity=1,fermitools_chatter=1,)

config.display()**

Output: 
binning:
  binsperdec: 8
  binsz: 0.1
  roiwidth: 10.0
data:
  evfile: /Users/shabnamiyyani/Gamma_ray_burst Dropbox/Shabnam Iyyani/Project_students_IISER/Manas_minor_project/LAT_trial/L804db3f139307eafaafdd397a765c7a8_FT1.fits
  scfile: /Users/shabnamiyyani/Gamma_ray_burst Dropbox/Shabnam Iyyani/Project_students_IISER/Manas_minor_project/LAT_trial/L220211013436AD7441F142_SC00.fits
logging:
  chatter: 1
  verbosity: 1
selection:
  dec: 22.014481926632996
  emax: 100000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: DATA_QUAL>0 && LAT_CONFIG==1
  ra: 83.63312208468774
  tmax: 493504614.039
  tmin: 493504611.039
  zmax: 100.0

**config["selection"]["emax"] = 300000.0
config["gtlike"] = {"edisp": False}

LAT = FermipyLike("LAT", config)
config.display()**

Output: 
binning:
  binsperdec: 8
  binsz: 0.1
  roiwidth: 10.0
data:
  evfile: /Users/shabnamiyyani/Gamma_ray_burst Dropbox/Shabnam Iyyani/Project_students_IISER/Manas_minor_project/LAT_trial/L804db3f139307eafaafdd397a765c7a8_FT1.fits
  scfile: /Users/shabnamiyyani/Gamma_ray_burst Dropbox/Shabnam Iyyani/Project_students_IISER/Manas_minor_project/LAT_trial/L220211013436AD7441F142_SC00.fits
fileio:
  outdir: __5e5f2130707e065b3c2dc2f7b7e77aa6
gtlike:
  edisp: true
logging:
  chatter: 1
  verbosity: 1
selection:
  dec: 42.343
  emax: 300000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: DATA_QUAL>0 && LAT_CONFIG==1
  ra: 171.248
  tmax: 493504614.039
  tmin: 493504611.039
  zmax: 100.0

**data = DataList(LAT)

jl = JointLikelihood(model, data)**

Output:
Fermipy Output directory: __5e5f2130707e065b3c2dc2f7b7e77aa6

Found Galactic template for IRF. P8R3_SOURCE_V3: /Users/shabnamiyyani/opt/miniconda3/envs/threeML/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits

Cutting the template around the ROI: 

Found Isotropic template for irf P8R3_SOURCE_V3: /Users/shabnamiyyani/opt/miniconda3/envs/threeML/share/fermitools/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/vq/jf14w4_j6n7_60zlyxzzkvg40000gn/T/ipykernel_19759/4293268498.py in <module>
     11 data = DataList(LAT)
     12 
---> 13 jl = JointLikelihood(model, data)

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py in __init__(self, likelihood_model, data_list, verbose, record)
     76         self._data_list: DataList = data_list
     77 
---> 78         self._assign_model_to_data(self._likelihood_model)
     79 
     80         # This is to keep track of the number of calls to the likelihood

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py in _assign_model_to_data(self, model)
    119         for dataset in list(self._data_list.values()):
    120 
--> 121             dataset.set_model(model)
    122 
    123             # Now get the nuisance parameters from the data and add them to the model

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py in set_model(self, likelihood_model_instance)
    461 
    462         self._gta, self._pts_energies = _get_fermipy_instance(
--> 463             self._configuration, likelihood_model_instance
    464         )
    465         self._update_model_in_fermipy( update_dictionary = True, force_update = True)

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py in _get_fermipy_instance(configuration, likelihood_model)
    171 
    172     # This will take a long time if it's the first time we run with this model
--> 173     gta.setup()
    174 
    175     # Substitute all spectra for point sources with FileSpectrum, so that we will be able to control

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, init_sources, overwrite, **kwargs)
   1080         # Run setup for each component
   1081         for i, c in enumerate(self.components):
-> 1082             c.setup(overwrite=overwrite)
   1083 
   1084         # Create likelihood

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, overwrite, **kwargs)
   5119 
   5120         self.logger.debug('Loading LT Cube %s', self.files['ltcube'])
-> 5121         self._ltc = LTCube.create(self.files['ltcube'])
   5122 
   5123         # Extract tmin, tmax from LT cube

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/ltcube.py in create(cls, ltfile)
    190             files = glob.glob(ltfile)
    191 
--> 192         ltc = cls.create_from_fits(files[0])
    193         for f in files[1:]:
    194             ltc.load_ltfile(f)

IndexError: list index out of range

usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory

Please advise me how to resolve the above issue.

**Comment by henrikef** [comment]
Hi @ShabnamIyyani ! Could you maybe crosspost this to the threeML github repo as well? 

Could you post the full script you are running so I can try and reproduce the error?

Also, can you confirm that the file download worked properly and that there was no timeout?
