### ISSUE TITLE
 Invalid Function Name: PLSuperExpCutoff4

### ISSUE THREAD

**Issue by DavidIsrayelyan** [fermiPy/fermipy#444]
Hello. 
When I updated catalog to 4FGL-DR3 I caught this kind of error. 
When will you review opened PR related to DR3 update?

raise Exception('Invalid Function Name: %s %s' % (name, get_function_spec.fndict.keys()))
Exception: Invalid Function Name: PLSuperExpCutoff4 dict_keys(['AbsEdge', 'BPLExpCutoff', 'BandFunction', 'BrokenPowerLaw', 'BrokenPowerLaw2', 'BrokenPowerLaw3', 'CompositeSource', 'ConstantValue', 'DMFitFunction', 'EblAtten::BPLExpCutoff', 'EblAtten::BandFunction', 'EblAtten::BrokenPowerLaw2', 'EblAtten::ExpCutoff', 'EblAtten::FileFunction', 'EblAtten::LogParabola', 'EblAtten::PLSuperExpCutoff', 'EblAtten::PowerLaw2', 'EblAtten::SmoothBrokenPowerLaw', 'EnergyBand::BPLExpCutoff', 'EnergyBand::BandFunction', 'EnergyBand::BrokenPowerLaw2', 'EnergyBand::ExpCutoff', 'EnergyBand::FileFunction', 'EnergyBand::LogParabola', 'EnergyBand::PLSuperExpCutoff', 'EnergyBand::PowerLaw2', 'EnergyBand::SmoothBrokenPowerLaw', 'ExpCutoff', 'ExpCutoffSEDPeak', 'FileFunction', 'Gaussian', 'LogGaussian', 'LogNormal', 'LogNormalLog', 'LogParabola', 'MapCubeFunction', 'MultipleBrokenPowerLaw', 'PLSuperExpCutoff', 'PLSuperExpCutoff2', 'PLSuperExpCutoff3', 'PiecewisePowerLaw', 'PowerLaw', 'PowerLaw2', 'RadialDisk', 'RadialGaussian', 'RadialProfile', 'ScaleFactor::FileFunction', 'ScaleFactor::Gaussian', 'ScaleFactor::PLSuperExpCutoff', 'ScaleFactor::PowerLaw2', 'SkyDirFunction', 'SmoothBrokenPowerLaw', 'SmoothDoubleBrokenPowerLaw', 'SpatialMap'])

Thank you.

**Comment by henrikef** [comment]
Hi @DavidIsrayelyan !

Currently, the automated tests are failing due to various incompatibilities in the dependencies. We're working on resolving those before accepting new pull requests such as #441 . In the mean time, you can try installing directly from the new branch ( https://github.com/ldivenere/fermipy/tree/431-plsec4 ) to test fermipy with 4FGL-DR3.

**Comment by henrikef** [comment]
I'm going to close this but please feel fee to re-open if you have any questions!
