### ISSUE TITLE
gtsrcmaps error : A Parameter named Expfactor is not a Parameter of Function 

### ISSUE THREAD

**Issue by LeandroMatheumatical** [fermiPy/fermipy#449]
Hello,

I'm trying to peforming a binned analyses, but i'm stoping in the step of **compute source maps** using **gtsrcmaps.** I did it previously with tutorial and other galaxies and i didn't have any problem. But, i recently  changed my computer and this error started to appear. has anyone run into the same problem?

Function::parameter(std::string &): 
A Parameter named Expfactor is not a Parameter of Function 

Caught N10optimizers17ParameterNotFoundE at the top level: Function::parameter(std::string &): 
A Parameter named Expfactor is not a Parameter of Function

CalledProcessError                        Traceback (most recent call last)
/tmp/ipykernel_2263/2471436870.py in <module>
----> 1 get_ipython().run_cell_magic('bash', '', 'gtsrcmaps\n    ./data/DracoII_binned_ltcube.fits\n    ./data/DracoII_binned_ccube.fits\n    ./data/DracoII_input_model.xml \n    ./data/DracoII_binned_allsky_expcube.fits\n    ./data/DracoII_binned_srcmaps.fits\n    CALDB\n')

~/anaconda3/envs/fermi/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2460             with self.builtin_trap:
   2461                 args = (magic_arg_s, cell)
-> 2462                 result = fn(*args, **kwargs)
   2463             return result
   2464 

~/anaconda3/envs/fermi/lib/python3.7/site-packages/IPython/core/magics/script.py in named_script_magic(line, cell)
    140             else:
    141                 line = script
--> 142             return self.shebang(line, cell)
    143 
    144         # write a basic docstring:

~/anaconda3/envs/fermi/lib/python3.7/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/anaconda3/envs/fermi/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3/envs/fermi/lib/python3.7/site-packages/IPython/core/magics/script.py in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'gtsrcmaps\n    ./data/DracoII_binned_ltcube.fits\n    ./data/DracoII_binned_ccube.fits\n    ./data/DracoII_input_model.xml \n    ./data/DracoII_binned_allsky_expcube.fits\n    ./data/DracoII_binned_srcmaps.fits\n    CALDB\n'' returned non-zero exit status 1.

**Comment by henrikef** [comment]
If you are still getting this error, could you please provide some more information? Which version of fermipy and the fermitools are you using? How does your config file look? Could you maybe run this as a script instead of notebook and send the full output? I'm really not sure where this error is coming from.

**Comment by LeandroMatheumatical** [comment]
> If you are still getting this error, could you please provide some more information? Which version of fermipy and the fermitools are you using? How does your config file look? Could you maybe run this as a script instead of notebook and send the full output? I'm really not sure where this error is coming from.

Helo henrikef!

i don't remember how this problem appear, but probabily it was related with the new versions of gll_psc27 and make4fgl.py . I really dont remember, but it was solved.
