### ISSUE TITLE
Weird aligned sources found with findsrc

### ISSUE THREAD

**Issue by benoitlott** [fermiPy/fermipy#452]
I ran find_sources on simulations with  enhanced diffuse components compared to the standrad ones to investigate the properties of the resulting sources.  The results from find_sources were reasonable most of the time but in some instances provided a weird cluster of sources closely aligned in space.  These sources were not located particularly near a ROI boundary.

**Comment by henrikef** [comment]
@benoitlott Could you provide some more information, such as output logfile/plots, which version of fermipy/fermitools you are using, and if possible a script or notebook to reproduce the issue?
