### ISSUE TITLE
MET to MJD conversion

### ISSUE THREAD

**Issue by spletts** [fermiPy/fermipy#460]
In `utils.py` why does the function `met_to_mjd()` return `54682.65 + (time - 239557414.0) / (86400.)`? I think this is initially offset from xTime by about 7 minutes.

In particular, why is the mission start in MJD, 54682.65527778 (according to xTime), truncated to 54682.65? And why is 239557414.0 subtracted from `time` instead of the mission start in MET, 23955741**7**.0?

**Comment by henrikef** [comment]
Nice catch! Comparing to the reference time listed [here](https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Data/Time_in_ScienceTools.html), I also see this 5 minute offset. It seems the `met_to_mjd()` utility is used only in `lightcurve.py`, to convert the bin edges to MJD after the lightcurve calculations. But, in my opinion it should still be fixed. Thoughts from anyone else?

**Comment by limyansky** [comment]
Hello, 

In my opinion it is worth fixing, as referencing the fermipy function was the first thing I tried when looking for an offline alternative to xTime.

I have attempted to address this in pull request #463.

This is my first time trying to contribute, so apologies if I have not followed the correct procedure! 

Best, 
Brent

**Comment by henrikef** [comment]
Fixed in #463
