### ISSUE TITLE
Args passed to optimize in lightcurve._process_lc_bin

### ISSUE THREAD

**Issue by spletts** [fermiPy/fermipy#467]
When `optimize` is called in `lightcurve._process_lc_bin`:

> `gta.optimize(skip=diff_sources, shape_ts_threshold=kwargs.get('shape_ts_threshold'))`

why is `shape_ts_threshold` (from the "_lightcurve_"" section of the config file) specified as an argument but not also `max_free_sources` (from the "_lightcurve_" section of the config file)? I believe that this results in `max_free_sources` from the "**roiopt**" section of the config file being used here. Is this the desired behavior?

**Comment by henrikef** [comment]
Yes, I think you are right, it does look like that parameter is not being passed on properly. I guess for some users it won't matter because the default values for `max_free_sources` are the same. Would you like to implement the fix yourself? If not, I will try to get to it soon.

**Comment by henrikef** [comment]
Take a look at #474 (branch `lc_fixes`) if you'd like.
