### ISSUE TITLE
save_bin_data == False breaks lightcurve creation 

### ISSUE THREAD

**Issue by pivosb** [fermiPy/fermipy#472]
I've been having unexpected issues with the lightcurve generation in fermipy once I set save_bin_data to False.

Here's the error:
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/tmp/ipykernel_134231/3996349889.py in <module>
      1 # Generate a lightcurve with 1-day binning
      2 #lc = gta.lightcurve('1es0229+200', binsz=86400. * 90)
----> 3 lc = gta.lightcurve('1es0229+200', time_bins=[611334005, 628423205, 645512405])

/afs/ifh.de/group/cta/scratch/pedroivo/Software/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py in lightcurve(self, name, **kwargs)
    287         self.logger.info('Computing Lightcurve for %s' % name)
    288 
--> 289         o = self._make_lc(name, **config)
    290         filename = utils.format_filename(self.workdir, 'lightcurve',
    291                                          prefix=[config['prefix'],

/afs/ifh.de/group/cta/scratch/pedroivo/Software/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py in _make_lc(self, name, **kwargs)
    451         for i, time in enumerate(zip(times[:-1], times[1:])):
    452             print(i, time)
--> 453             next_fit = next(mapo)
    454 
    455             if not 'fit_success' in next_fit:

StopIteration:  
```

After some digging, I realized that if `save_bin_data` is set to `False`, then in https://github.com/fermiPy/fermipy/blob/b0163085261a3112f3e0bb5ba050aa37aeb9560e/fermipy/lightcurve.py#L440-L442

you iterate over `mapo` , and then in https://github.com/fermiPy/fermipy/blob/b0163085261a3112f3e0bb5ba050aa37aeb9560e/fermipy/lightcurve.py#L450

the iterator is exhausted and raises the `StopIteration` error.

The solution I found for now is to simply set `save_bin_data` to `True` again, and it works just fine.

**Comment by henrikef** [comment]
I see what you mean. The iterator doesn't reset after you loop over it the first time. I think we can fix it by moving the file deletion into the 2nd loop. Let me give it a try.

**Comment by henrikef** [comment]
Take a look at #474 (branch `lc_fixes`) if you'd like.
