### ISSUE TITLE
Bow tie spectrum extraction

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#48]
Hi Matthew,

I was wondering if it possible to extract bow-tie spectrum values to a text file or something similar. I have noticed that fermipy plots bow tie spectrum when generating SEDs. It is be of great interest to use the bow-tie spectrum for further physical analysis such as the SED modeling of a blazar.
Thanks.
Vaidehi

**Comment by woodmd** [comment]
You can extract the bow-tie spectrum from the output of `sed()` in two ways.  The output dictionary contains a `model_flux` dictionary with the central value and +/- 1 sigma error bands:
```
sed = gta.sed('MySource')
mf = sed['model_flux']
np.savetxt('spectrum.txt',np.vstack((mf['energies'],mf['dfde_lo'],mf['dfde'],mf['dfde_hi'])).T)
```
The same information is also written to the SED FITS file in the MODEL_FLUX HDU:
```
from astropy.table import Table
sed = gta.sed('MySource')
model_flux = Table.read(sed['file'],'MODEL_FLUX')
np.savetxt('spectrum.txt',np.vstack((mf['ENERGY'],mf['DFDE_LO'],mf['DFDE'],mf['DFDE_HI'])).T)
```

**Comment by vaidehiratna** [comment]
Perfect. Thanks.
