### ISSUE TITLE
getting error with reference to matplotlib while generating TSmap

### ISSUE THREAD

**Issue by ajaykhoj** [fermiPy/fermipy#482]
Hi, 

i am getting error while generating TSmap 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_85537/1806551395.py in <module>
----> 1 tsmap_postfit = gta.tsmap(prefix='TSmap_start',make_plots=True,write_fits=True,write_npy=True)

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/tsmap.py in tsmap(self, prefix, **kwargs)
    701                                                logging=self.config['logging'])
    702 
--> 703             plotter.make_tsmap_plots(o, self.roi)
    704 
    705         self.logger.log(config['loglevel'], 'Finished TS map')

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/plotting.py in make_tsmap_plots(self, maps, roi, **kwargs)
   1114         p.plot(vmin=0, vmax=5, levels=sigma_levels,
   1115                cb_label='Sqrt(TS) [$\sigma$]', interpolation='bicubic',
-> 1116                zoom=zoom)
   1117         plt.savefig(utils.format_filename(workdir,
   1118                                           '%s_sqrt_ts' % suffix,

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/plotting.py in plot(self, **kwargs)
    583         cb_kwargs = merge_dict(cb_kwargs, kwargs)
    584 
--> 585         im, ax = self._implot.plot(**im_kwargs)
    586 
    587         self._ax = ax

~/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/plotting.py in plot(self, subplot, cmap, **kwargs)
    309         kwargs_contour = merge_dict(kwargs_contour, kwargs)
    310 
--> 311         im = ax.imshow(data, **kwargs_imshow)
    312         im.set_cmap(colormap)
    313 

~/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py in imshow(self, X, *args, **kwargs)
    200                 X = X.transpose(FLIP_TOP_BOTTOM)
    201 
--> 202         return super().imshow(X, *args, origin=origin, **kwargs)
    203 
    204     def contour(self, *args, **kwargs):

~/anaconda3/envs/fermi/lib/python3.7/site-packages/matplotlib/_api/deprecation.py in wrapper(*args, **kwargs)
    457                 "parameter will become keyword-only %(removal)s.",
    458                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 459         return func(*args, **kwargs)
    460 
    461     # Don't modify *func*'s signature, as boilerplate.py needs it.

~/anaconda3/envs/fermi/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1410     def inner(ax, *args, data=None, **kwargs):
   1411         if data is None:
-> 1412             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1413 
   1414         bound = new_sig.bind(ax, *args, **kwargs)

~/anaconda3/envs/fermi/lib/python3.7/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, interpolation_stage, filternorm, filterrad, resample, url, **kwargs)
   5484             # image does not already have clipping set, clip to axes patch
   5485             im.set_clip_path(self.patch)
-> 5486         im._scale_norm(norm, vmin, vmax)
   5487         im.set_url(url)
   5488 

~/anaconda3/envs/fermi/lib/python3.7/site-packages/matplotlib/cm.py in _scale_norm(self, norm, vmin, vmax)
    379             if norm is not None:
    380                 raise ValueError(
--> 381                     "Passing parameters norm and vmin/vmax simultaneously is "
    382                     "not supported. Please pass vmin/vmax directly to the "
    383                     "norm when creating it.")

ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
##########################################################################################################

matplotlib-3.5.2
fermipy-1.0.1
fermitools-2.0.8

Any help would be much appreciated.

**Comment by henrikef** [comment]
Hi Ajay! Please try updating to `fermitools 2.2` and `fermipy 2.1.4`: https://fermipy.readthedocs.io/en/latest/install.html . You will need a fresh install because the new version of fermitools requires `python 3.9`.

Another option would be to try downgrading matplotlib to an older version until the error goes away. 

Let me know if this helps!
