### ISSUE TITLE
Error with data_QuickLook notebook

### ISSUE THREAD

**Issue by CorneliaArcaro** [fermiPy/fermipy#484]
**Describe the bug**
The data_QuickLook notebook fales when running this piece of code:

time -p gtselect infile=/data_arcaro/1218/ST0307/events.txt outfile=/data_arcaro/1218/ST0307/counts.fits ra=185.341 dec=30.177 rad=15.0 tmin=56697.216 tmax=56699.279 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
/bin/sh: time: command not found

I had downloaded my data using the Fermi Lat query

**To Reproduce**

This is the part of the notebook data_QuckLook that produces an error:

#making a counts map using gtbin (gives an error in the notebook but works perfectly as shell command)

filter['infile'] = str(root_path+'/events.txt')
filter['outfile'] = str(root_path+'/counts.fits')
filter['ra'] = 185.341
filter['dec'] = 30.177
filter['rad'] = 15.0
filter['tmin'] = 56697.216
filter['tmax'] = 56699.279
filter['emin'] = 100
filter['emax'] = 300000
filter['zmax'] = 90
filter['evclass'] = 128
filter['evtype'] = 3
filter.run()

time -p gtselect infile=/data_arcaro/1218/ST0307/events.txt outfile=/data_arcaro/1218/ST0307/counts.fits ra=185.341 dec=30.177 rad=15.0 tmin=56697.216 tmax=56699.279 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
/bin/sh: time: command not found

**Expected behavior**
I would hav expected the commando to work and create a fits file based on the cuts applied

**Log files**
time -p gtselect infile=/data_arcaro/1218/ST0307/events.txt outfile=/data_arcaro/1218/ST0307/counts.fits ra=185.341 dec=30.177 rad=15.0 tmin=56697.216 tmax=56699.279 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
**/bin/sh: time: command not found**

**Environment (please complete the following information):**
 - OS: Centos7
 - fermipy 1.1.4, fermitools 2.2.0, fermitools-data 0.18               

**Additional context**
Strangely, when executing the command in my sheel after having activated the conda environment, there is no such error

**Comment by henrikef** [comment]
Hm. I'm not sure what could cause this. Anyway, assuming you are referring to this [Quicklook notebook](https://github.com/FermiSummerSchool/fermi-summer-school/blob/master/Data_Exploration/Data_QuickLook.ipynb), this is a problem with the fermitools, not fermipy. Please reach out to the [FSSC helpdesk](https://fermi.gsfc.nasa.gov/ssc/help/). Good luck with this!

**Comment by CorneliaArcaro** [comment]
Hi! I have a different opinion here: As I stated, the command :" time -p gtselect infile=/data_arcaro/1218/ST0307/events.txt outfile=/data_arcaro/1218/ST0307/counts.fits ra=185.341 dec=30.177 rad=15.0 tmin=56697.216 tmax=56699.279 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"  : works without any problems when executed as line command in the shell. Instead when running this in jupyter:


filter['infile'] = str(root_path+'/events.txt')
filter['outfile'] = str(root_path+'/counts.fits')
filter['ra'] = 185.341
filter['dec'] = 30.177
filter['rad'] = 15.0
filter['tmin'] = 56697.216
filter['tmax'] = 56699.279
filter['emin'] = 100
filter['emax'] = 300000
filter['zmax'] = 90
filter['evclass'] = 128
filter['evtype'] = 3
filter.run()


the output is the command line but with the following error:

time -p gtselect infile=/data_arcaro/1218/ST0307/events.txt outfile=/data_arcaro/1218/ST0307/counts.fits ra=185.341 dec=30.177 rad=15.0 tmin=56697.216 tmax=56699.279 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
/bin/sh: time: command not found
