### ISSUE TITLE
Get MINUIT contours from FermiPy

### ISSUE THREAD

**Issue by addyjea** [fermiPy/fermipy#486]
Hi all,

I am wondering if there's a way to call MNContour, the contour plotting method in MINUIT, from FermiPy. 
I'm trying to create a plot such as the one shown here, fig 8 https://journals.aps.org/prd/abstract/10.1103/PhysRevD.88.083521

Thanks!
-Addy

**Comment by henrikef** [comment]
Hi Addy! I'm not sure about accessing MINUIT functions directly. 

Fermipy actually already performs this scan for us in many instances. For example, after calling `gta.fit()`, the `gta.roi` object contains the results of a scan over the source normalization for each source in the [source dictionary](https://fermipy.readthedocs.io/en/latest/output.html). You can access it as e.g. `gta.roi['4FGL J0425.6+5522e']["flux_scan"], gta.roi['4FGL J0425.6+5522e']["dloglike_scan"]`. You can find similar entries for the flux per energy bin or time bin or the extension scan in the outputs of the relevant [advanced analysis functions](https://fermipy.readthedocs.io/en/latest/advanced/index.html). Let me know if you have any questions on how to extract the likelihood profiles.

If you want more control: `gta.fit() ` is a just a wrapper around the fit inside `fermitools`/`pyLikelihood`. You can access the underlying `pyLikelihood` object as `gta.like`. It does have a `scan` function to perform a likelihood scan over one parameter. This is its help text:
```
help(gta.like.scan)
```

```
Help on method scan in module AnalysisBase:

scan(srcName, parName, xmin=0, xmax=10, npts=50, tol=None, optimizer=None, optObject=None, fix_src_pars=False, verbosity=0, renorm=False) method of fermipy.gtutils.SummedLikelihood instance
    This function scans the values of a specific parameter
    specified by "parName" of a specific source specified by
    "srcName" in the range [xmin:xmax] with a resolution of npts.
    It then optimizes the active model.  This function returns two
    arrays: the first is an array of the x values evaluated and
    the second is an array of the change in likelihood value from
    the original model at those x values.  You can also pass True
    to "fix_src_pars" to fix all of the parameters of the source
    of interest.  The other options are similar to the fit and
    optimize functions.
```

If you have any questions about that or how to access the underlying MINUIT functions, I hope that the FSSC will be able to help.
