### ISSUE TITLE
Notebooks kernel died !

### ISSUE THREAD

**Issue by ghost** [fermiPy/fermipy#487]
Hello, all. When I run code in notebook, there is a prompt of kernel death. What's going on?
![image](https://user-images.githubusercontent.com/109416378/181022137-f5694605-a8d8-4dee-9c07-5ebb89c6221e.png)

**Comment by henrikef** [comment]
@HankGreurr 

Does the error reappear if you restart the notebook? Where in the notebook does the crash happen and is it always at the same place? 

Please provide the necessary information for troubleshooting, copied below for your convenience. 

> 
> **Describe the bug**
> A clear and concise description of what the bug is. What data are you using and how was it obtained? 
> 
> *NOTE:* This is for fermipy bug reports and not for questions about data analysis or issues with fermitools.
> 
> **To Reproduce**
> 
> Please provide enough information for someone else to reporoduce this bug. That means e.g. a script + (links to) necessary files + any command line options, or an ipython notebook or something similar.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Log files**
> Add log files or copy & paste the entire terminal output.
> 
> **Environment (please complete the following information):**
>  - OS: (e.g. MacOS Monterey version 12.3.1)
>  - Output of `uname -a`
>  - fermipy, fermitools, and fermitools-data versions (e.g. fermipy 1.0.1, fermitools 2.0.8)
> 
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by HankGreurr** [comment]
OK, @henrikef 
** Describe the err **
When I run the code in notebook, the kernel is dead, and the complete code is here[Untitled.pdf](https://github.com/fermiPy/fermipy/files/9216279/Untitled.pdf)

I know it's this `from` fermipy.gtanalysis import GTAnalysis` that makes the notebook kernel dead.

**Environment：**
- Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- fermipy, fermitools,  versions (e.g. fermipy  1.1.6, fermitools 2.2.0)

I hope this information can help me solve this problem, thank you!

**Comment by henrikef** [comment]
Hm, the notebook looks fine to me. Let's try to get some more error messages - unfortunately the notebook kernel dying is not very helpful for troubleshooting. 

Unfortunately, I am not familiar with the windows subsystem for Linux - I am not sure if the fermitools are compatible.

Could you please run the following from the command line (in your fermipy enviroment): `python -c "from fermipy.gtanalysis import GTAnalysis"`  and post any output here?

**Comment by Hank-Grurdw** [comment]
@henrikef Sorry, I just saw your information. Just now I tried. There was no error in running Python -c "from fermipy.gtanalysis import gtanalysis" on the terminal. I just don't understand why there are errors when running in notebook. I once ran in IPython without any error.
