### ISSUE TITLE
Something is wrong with the old extdended source templates

### ISSUE THREAD

**Issue by henrikef** [fermiPy/fermipy#495]
Extended source templates for some of the older catalogs are missing(?). E.g. https://github.com/fermiPy/fermipy/blob/master/fermipy/data/catalogs/Extended_archive_v15/Templates/CenALobes.fits seems to be just a text file with this content:

> version https://git-lfs.github.com/spec/v1
> oid sha256:da664d1562ae218909ee23103cbdf095bebda0746424a9c8cd6205eb4b93517d
> size 103680

The newer files are ok, e.g. https://github.com/fermiPy/fermipy/blob/master/fermipy/data/catalogs/Extended_12years/Templates/CenALobes.fits

**Comment by omodei** [comment]
I think this has to do with the git lfs quota. An easy solution is to get templates files directly from the FSSC, in the respective catalog pages.
