### ISSUE TITLE
Error installing threeml, fermitools, fermipy using conda

### ISSUE THREAD

**Issue by Jisans** [fermiPy/fermipy#498]
Hell all,
I am trying to install fermitools, fermipy and threeml in the same environment using conda. I created a virtual environment using `conda create -- name fermi3ML - c conda forge - c fermi - c threeml`. I continue to use `conda install - c conda forge - c xspecmodels xspec models` only, `conda install - c conda forge - c threemel - c fermi threeml fermipy fermitools`.It is strange that I can use `fermitools`, `threeml` and `fermipy` in `ipython`. I tried to import `threeml` in `jupyter lab`, but there was such a warning,I don't know where the problem is. Can you help me? thank you!
#Note:System:Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 [#1](https://github.com/fermi-lat/Fermitools-conda/pull/1) SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
conda env
Python 3.9.13, pip 22.2.2,fermitools 2.2.0,fermipy 1.0.1,fermitools-data 0.18,threeml  2.3.2

![image](https://user-images.githubusercontent.com/110452095/187140675-b874058b-3e80-4fe4-b2b2-3ba8205e19c8.png)

**Comment by henrikef** [comment]
Hi @Jisans ! This error message is very general, also the issue appears to be with `threeML`, so I don't think I can help much.

One thing though, please refer to the [installation instructions](https://fermipy.readthedocs.io/en/latest/install.html) and install `fermipy` from `pip` - the latest version is not available on conda.
