### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by naseefmhd** [fermiPy/fermipy#500]
Hii Dears
While trying to make lightcurve for 3C 279 , I found this error. It seems something related to binning time. Can anyone solve this issue?
Thanks in advance

NameError                                 Traceback (most recent call last)
Input In [39], in <cell line: 1>()
----> 1 lc = gta.lightcurve('4FGL J1256.1-0547', binsz=86400.*7.0 , multithread=True)

File ~/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/lightcurve.py:290, in LightCurve.lightcurve(self, name, **kwargs)
    286 config = schema.create_config(config, **kwargs)
    288 self.logger.info('Computing Lightcurve for %s' % name)
--> 290 o = self._make_lc(name, **config)
    291 filename = utils.format_filename(self.workdir, 'lightcurve',
    292                                  prefix=[config['prefix'],
    293                                          name.lower().replace(' ', '_')])
    295 o['file'] = None

File ~/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/lightcurve.py:385, in LightCurve._make_lc(self, name, **kwargs)
    382     times = np.append( times, self.tmax ) #np.arange never includes the end point
    384     if times[-1] - times[-2] < kwargs['binsz']:
--> 385         log.warning(f"Last lightcurve bin ({times[-1] - times[-2]} s) is shorter than nominal ({kwargs['binsz']} s).")
    387 diff_sources = [s.name for s in self.roi.sources if s.diffuse]
    388 skydir = self.roi[name].skydir

NameError: name 'log' is not defined

**Comment by henrikef** [comment]
Hi @naseefmhd , this was fixed in #490 but is not yet on `pip`. Will push it there soon and let you know when it's ready. Sorry about this!

**Comment by henrikef** [comment]
This should be fixed in version 1.2 which is available via pip now. `pip install --upgrade fermipy` should do it. I'm going to close this, please re-open if you still see any issues!
