### ISSUE TITLE
Semi-major and semi-minor axis length computation during source localization

### ISSUE THREAD

**Issue by astro-fermi** [fermiPy/fermipy#501]
## Feature Request

Hi All,

Thanks for this very nice package. I am trying to carry out the source localization of a few 4FGL sources. The task 'gta.localize' gives in the output 'pos_err_semimajor' and 'pos_err_semiminor', i.e., uncertainties in the semi-major/minor axes lengths. However, it does not save the corresponding values of the semi-major/minor axes lengths, i.e., 'pos_semimajor' and 'pos_semiminor'. Please see if it is possible to get these numbers in the output. Thanks.

**Comment by henrikef** [comment]
Hi @astro-fermi ! This sounds like a good idea, would you like to take a stab at implementing it yourself?

Otherwise, any volunteers are welcome.

**Comment by omodei** [comment]
Hi @astro-fermi! _pos_err_semimajor_ and _pos_err_semiminor_ are the semi axis (major and minor) of the error ellipse, not their uncertainty. The relevant code is [here](https://github.com/fermiPy/fermipy/blob/fbd4c95ffadbff31cbb9cc862ff84a78dc734ef5/fermipy/sourcefind_utils.py#L99)
