### ISSUE TITLE
Issue installing on a windows PC

### ISSUE THREAD

**Issue by DK492** [fermiPy/fermipy#504]
**Describe the error**
I'm unable to install fermipy on my windows PC - i think the issue lies with healpy not being supported for windows. any help in getting around this is appreciated

**To Reproduce**

when using the 
`mamba create --name fermipy -c conda-forge -c fermi python=3.9 "fermitools>=2.2.0" healpy gammapy` 
command, I am greeted by
```
Encountered problems while solving:
  - nothing provides requested fermitools >=2.2.0
  - nothing provides requested healpy
```

**Expected behavior**
I expected to be able to install fermipy

**Log files**
```
Looking for: ['python=3.9', "fermitools[version='>=2.2.0']", 'healpy', 'gammapy']

fermi/win-64                                                  No change
fermi/noarch                                                  No change
conda-forge/noarch                                   9.7MB @ 668.9kB/s 14.9s
conda-forge/win-64                                  16.6MB @ 938.5kB/s 18.7s
Encountered problems while solving:
  - nothing provides requested fermitools >=2.2.0
  - nothing provides requested healpy

```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Output of uname -a 
 ```
uname is not recognized as an internal or external command,
operable program or batch file.
```
 - fermipy, fermitools, and fermitools-data versions (for exameple, fermipy 1.0.1, fermitools 2.0.8)
 - not really applicable since I can't install them in the first place? 

**Additional context**
Sorry if this has been answered elsewhere I'm pretty new to github and everything so don't really know my way around!

**Comment by Jisans** [comment]
You can try to install WSL2(https://learn.microsoft.com/en-us/windows/wsl/install) in your windows PC,I am using WSL2, which can install fermitools, and fermipy and it works fine.

**Comment by DK492** [comment]
> 

It seems to be working through wsl2. Thank you so much, you are an absolute life-saver!
