### ISSUE TITLE
`std::runtime_error` when trying to load the library

### ISSUE THREAD

**Issue by garciagenrique** [fermiPy/fermipy#505]
**Describe the error**
Created new fresh environment (using mamba - conda 4.10.2) with python=3.9 fermitools healpy gammapy.
Installing `fermipy` with `pip install fermipy`

**To Reproduce**

```python
In [1]: import fermipy
terminate called after throwing an instance of 'std::runtime_error'
  what():  File not found: /refdata/fermi/caldb/software/tools/alias_config.fits
Aborted (core dumped)
jovyan@jupyter-garcia:~$ 
```

**Expected behavior**
Be able to load the library :)

**Log files**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LST (Focal Fossa) installed in a JupyterHub instance within a K8s cluster
 - Output of `uname -a`:  `Linux jupyter-garcia 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - fermipy: cannot be even loaded 
 - fermitools: `fermitools.  2.2.0  py39h93a0a19_0       fermi/linux-64`
 - fermitools-data: `fermitools-data   0.18  0  fermi/noarch`

**Additional context**

**Comment by henrikef** [comment]
@garciagenrique I will close this for now. Please re-open and provide the requested information if you are still experiencing issues.

**Comment by garciagenrique** [comment]
Hi @henrikef,
Thanks for your answer.
Both commands are currently running correctly (I get a large list of event classes/types, and the import of `pyLikehood` is done successfully). So you can leave the issue close :)

**Comment by garciagenrique** [comment]
For the record: the way that I solve the problem was creating the environment without the `fermipy` lib (our environment is spawned by a JupyterHub instance), and later installing the `fermipy` lib with the `--user` flag. Not sure why it worked this way.
