### ISSUE TITLE
IndexError while running gta.setup()

### ISSUE THREAD

**Issue by sushmitaagarwal** [fermiPy/fermipy#508]
I have downloaded data for a source that is on 4FGL catalog and carried out the analysis this way. However, I am getting IndexError for this particular source. 

I followed the commands as follows:
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('/home/hulk/Sources/NGC_1068/analysis/10d/config.yaml',logging={'verbosity' : 3})
gta.setup()

The gta.setup() shows this error for the input config file. 

> gta = GTAnalysis('/home/hulk/Sources/NGC_1068/analysis/10d/config.yaml',logging={'verbosity' : 3})
> 2022-11-05 15:03:45 INFO    GTAnalysis.__init__(): 
> fermipy version v1.1.2 
> ScienceTools version 2.1.30
>  **gta.setup()**
> 2022-11-05 15:03:54 INFO    GTAnalysis.setup(): Running setup.
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/hulk/Sources/NGC_1068/analysis/10d/evfile_00.txt outfile=/home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits ra=40.66699981689453 dec=-0.006899999920278788 rad=7.5710678118654755 tmin=673071970.0 tmax=689315169.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: File not in FITS format: /home/hulk/Sources/NGC_1068/analysis/10d/
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.16 s
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Running gtmktime.
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtmktime scfile=/home/hulk/Sources/NGC_1068/data/L2211050407462060299877_SC00.fits sctable="SC_DATA" filter="DATA_QUAL>0 && LAT_CONFIG==1" roicut=no evfile=/home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits evtable="EVENTS" outfile="/home/hulk/Sources/NGC_1068/analysis/10d/ft1_filtered_00.fits" apply_filter=yes overwrite=no header_obstimes=yes tstart=0.0 tstop=0.0 gtifile="default" chatter=2 clobber=yes debug=no gui=no mode="ql"
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: File not found: /home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtmktime. Execution time: 0.06 s
> mv: cannot stat '/home/hulk/Sources/NGC_1068/analysis/10d/ft1_filtered_00.fits': No such file or directory
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits" evtable="EVENTS" scfile=/home/hulk/Sources/NGC_1068/data/L2211050407462060299877_SC00.fits sctable="SC_DATA" outfile=/home/hulk/Sources/NGC_1068/analysis/10d/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: /home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits
> 2022-11-05 15:03:54 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.06 s
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hulk/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1087, in setup
>     **c.setup(overwrite=overwrite)**
>   File "/home/hulk/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5176, in setup
>     **self._ltc = LTCube.create(self.files['ltcube'])**
>   File "/home/hulk/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/ltcube.py", line 192, in create
>     **ltc = cls.create_from_fits(files[0])**
> **IndexError: list index out of range**

** Environment**
 - OS: Ubuntu 18.04.6 LTS
 - Fermipy v1.1.2 , ScienceTools v2.1.30

Kindly let me know if there is a way to solve this issue. 
Any help will be appreciated.

**Comment by henrikef** [comment]
@sushmitaagarwal If you look for errors further up in the output you posted, you will find this:

```
2022-11-05 15:03:54 INFO GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/hulk/Sources/NGC_1068/analysis/10d/evfile_00.txt outfile=/home/hulk/Sources/NGC_1068/analysis/10d/ft1_00.fits ra=40.66699981689453 dec=-0.006899999920278788 rad=7.5710678118654755 tmin=673071970.0 tmax=689315169.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2022-11-05 15:03:54 INFO GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2022-11-05 15:03:54 INFO GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: File not in FITS format: /home/hulk/Sources/NGC_1068/analysis/10d/
```

Please check ` /home/hulk/Sources/NGC_1068/analysis/10d/evfile_00.txt` to make sure the input file(s) are listed correctly here. If you are unable to resolve the issue, please post your `config.yml` and `evfile_00.txt` here and I will take a look.

**Comment by sushmitaagarwal** [comment]
I figured it out. I guess I had an extra empty line in my .config file which was resulting in this issue.
