### ISSUE TITLE
Issue fixing parameters in .xml file. 

### ISSUE THREAD

**Issue by sushmitaagarwal** [fermiPy/fermipy#518]
## Data Analysis Question

While doing analysis for a source, I wish to fix one of the parameters to a fixed value (which I want to specify myself). I specifically want to fix the value of Eb in the log-parabola model for a source that is by default set to 4FGL catalog value. 
After gta.setup() I find srcmdl__00.xml and I change the value of Eb for my source from the default value to the value I wish to fix. 

However, after the final analysis, I see the output xml file (fit1_00.xml) showing Eb shifted back to the default value. 

Please let me know if there is an alternate way to do it or something I am doing wrong. 
It will be great help for my work. 
Looking forward to a responde.

Thank you in advance.

**Comment by henrikef** [comment]
Hi @sushmitaagarwal ! 

Please try calling `gta.set_parameter(source_name, "Eb", value, true_value=True, scale=1, bounds=None, error=None, update_source=True)` after `fermipy.setup`. Please let me know if that helps.

You might have to call `gta.free_parameter(source_name, "Eb", free=True)` before and  `gta.free_parameter(source_name, "Eb", free=False)` after changing the value.

**Comment by sushmitaagarwal** [comment]
Hi @henrikef 
Thanks for your response. This worked. I need to also know the covariance matrix of the fitted parameters. 
Can you guide me where I can find it?

**Comment by henrikef** [comment]
See https://fermipy.readthedocs.io/en/latest/fitting.html

```
o = gta.fit()
o['covariance']
```

Note: As explained in the documentation page I linked, the covariance matrix is only accurate if `o['fit_quality']==3`.

**Comment by sushmitaagarwal** [comment]
Thank you for your response.
Can you also tell me how can I change the spectrum  type. For instance, if I wish to fit a broken power law on spectrum intead of the default log parabola model or power law model , what changes should I make in the script for that.

**Comment by henrikef** [comment]
You will need to delete the source and add a "new" one at the same position.

See https://github.com/FermiSummerSchool/fermi-summer-school/blob/master/Likelihood_Advanced/Curvature%20Test.ipynb for an example.
