### ISSUE TITLE
IndexError when running the pg1553 tutorial

### ISSUE THREAD

**Issue by ben1sheff** [fermiPy/fermipy#524]
I tried to use the ipython tutorial from the fermipy-extra directory and keep getting IndexErrors. I have adjusted the config file to include time information to avoid a basic error, then I ran with the config file in a separate folder from the pg1553 folder that is unzipped as part of the tutorial file which delayed the IndexError to later in processing. I am still getting an odd IndexError during the gta.setup() command. I attached the stack trace and the config file.
[stack_trace.txt](https://github.com/fermiPy/fermipy/files/10452039/stack_trace.txt)
[config.txt](https://github.com/fermiPy/fermipy/files/10452052/config.txt)

**Comment by henrikef** [comment]
Hi @ben1sheff ! Which version of fermipy are you using? If it is below version 1.2, please update to that version.

**Comment by ben1sheff** [comment]
This was the issue. Conda will install version 1.1 by default, and you have to use pip install to get version 1.2

**Comment by henrikef** [comment]
Great! Yes, we're aware of some issues with the conda distribution, we're working on it!

**Comment by ben1sheff** [comment]
All right, thanks for helping!
