### ISSUE TITLE
Set `$FERMI_DIFFUSE_DIR`

### ISSUE THREAD

**Issue by henrikef** [fermiPy/fermipy#534]
Let's try and set `$FERMI_DIFFUSE_DIR` within fermipy - it should default to `$FERMI_DIR/refdata/fermi/galdiffuse/`

See https://github.com/fermi-lat/Fermitools-conda/issues/139

**Comment by Areustle** [comment]
Consider not using an environment variable for this. EnvVars are fragile and error prone. Consider instead writing a function or method that will return the desired path as a string.

**Comment by omodei** [comment]
I am not seeing any traffic here. Closing this issue.
