### ISSUE TITLE
Issues with source localisation

### ISSUE THREAD

**Issue by fcotizelati** [fermiPy/fermipy#536]
Good morning,

I'm conducting a binned analysis on a set of data that cover the entire 12 years of the catalog for a source that is rather close to the Galactic plane. I'm conducting the analysis with fermipy and I managed to obtain a TS map of the region around the source. I am now trying to localise the source, but I'm getting some issues with the command. I report below the command that I used and the deriving error:

python3
from fermipy.gtanalysis import GTAnalysis
import pyLikelihood
gta = GTAnalysis(‘config.yaml’,logging={‘verbosity’ : 3})
loc = gta.localize(‘4FGL_J1110.3-6501’, make_plots=True)
[files.zip](https://github.com/fermiPy/fermipy/files/10929503/files.zip)

2023-03-08 14:24:27 INFO  GTAnalysis.localize(): Running localization for 4FGL_J1110.3-6501
Traceback (most recent call last):
File “<stdin>“, line 1, in <module>
File “/home/hidra4/cotizelati/anaconda3/envs/fermi/lib/python3.9/site-packages/fermipy/sourcefind.py”, line 283, in localize
 free_state = FreeParameterState(self)
File “/home/hidra4/cotizelati/anaconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtutils.py”, line 463, in __init__
 self._free = gta.get_free_param_vector()
File “/home/hidra4/cotizelati/anaconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py”, line 2163, in get_free_param_vector
 for p in self.like.params():
AttributeError: ‘NoneType’ object has no attribute ‘params’

I am also attaching the config.yaml and the XML model files, in case there's something wrong with them. 

Thank you,
Francesco

**Comment by henrikef** [comment]
Hi @fcotizelati , try calling `gta.setup()` before the `localize()` step.
