### ISSUE TITLE
Farith command not found

### ISSUE THREAD

**Issue by banafsh89** [fermiPy/fermipy#538]
**Describe the bug**
I installed fermipy using mamba as suggested in the website and so far every commands work except the "farith" command. When I call it it says, "command not found: farith".
I have a macOs machine version macOS Ventura 

Here is the complete info about my fermipy installation using conda info fermipy:

fermipy 1.1.0 pyhd8ed1ab_0
--------------------------
file name   : fermipy-1.1.0-pyhd8ed1ab_0.conda
name        : fermipy
version     : 1.1.0
build string: pyhd8ed1ab_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 36.0 MB
arch        : None
constrains  : ()
license     : BSD-3-Clause
license_family: BSD
md5         : 40598c79c84045e2f759184c23b608a9
noarch      : python
package_type: noarch_python
platform    : None
sha256      : 34e90ee6cd0642f98aea5d0c0c0f3b1850235be682cd4d91292dbfa048397c19
subdir      : noarch
timestamp   : 1673986628101
url         : https://conda.anaconda.org/conda-forge/noarch/fermipy-1.1.0-pyhd8ed1ab_0.conda
dependencies:
    astropy
    gammapy
    healpy
    matplotlib-base
    numpy
    python >=3.7,!=3.8.*
    pyyaml
    scipy

fermipy v1.2 pyhd8ed1ab_0
-------------------------
file name   : fermipy-v1.2-pyhd8ed1ab_0.conda
name        : fermipy
version     : v1.2
build string: pyhd8ed1ab_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 35.7 MB
arch        : None
constrains  : ()
license     : BSD-3-Clause
license_family: BSD
md5         : 80df06b2356a38f94a7cf644b9552831
noarch      : python
package_type: noarch_python
platform    : None
sha256      : 118b47256e18cba38a2dd9970f503e0b04aec91e444a7126768919092a878e76
subdir      : noarch
timestamp   : 1674168482807
url         : https://conda.anaconda.org/conda-forge/noarch/fermipy-v1.2-pyhd8ed1ab_0.conda
dependencies:
    astropy
    gammapy
    healpy
    matplotlib-base
    numpy
    python >=3.7,!=3.8.*
    pyyaml
    scipy

fermipy 0.19.0 pyh95af2a2_1
---------------------------
file name   : fermipy-0.19.0-pyh95af2a2_1.tar.bz2
name        : fermipy
version     : 0.19.0
build string: pyh95af2a2_1
build number: 1
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 28.2 MB
arch        : None
constrains  : ()
license     : BSD 3-Clause
md5         : 72f1726e860f62178d04782f33ed855f
noarch      : python
package_type: noarch_python
platform    : None
sha256      : f4bfe68644a73892fa2989f603bc0b3c5dc06b056fcd0f2103a5c067703186fc
subdir      : noarch
timestamp   : 1586545345388
url         : https://conda.anaconda.org/conda-forge/noarch/fermipy-0.19.0-pyh95af2a2_1.tar.bz2
dependencies:
    astropy
    gammapy
    healpy
    matplotlib-base
    numpy >=1.14.6,<2.0a0
    python
    pyyaml
    scipy

fermipy 0.19.0 pyh5ca1d4c_2
---------------------------
file name   : fermipy-0.19.0-pyh5ca1d4c_2.tar.bz2
name        : fermipy
version     : 0.19.0
build string: pyh5ca1d4c_2
build number: 2
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 28.2 MB
arch        : None
constrains  : ()
license     : BSD 3-Clause
md5         : 863d9e292985d65dc52b9924d7e4559f
noarch      : python
package_type: noarch_python
platform    : None
sha256      : a4913053f14f9d52fcf1eb7707b5198720b9916d40c4d79ee7abfa1eadb3471a
subdir      : noarch
timestamp   : 1586556272412
url         : https://conda.anaconda.org/conda-forge/noarch/fermipy-0.19.0-pyh5ca1d4c_2.tar.bz2
dependencies:
    astropy
    gammapy
    healpy
    matplotlib-base
    numpy >=1.14.6,<2.0a0
    python
    pyyaml
    scipy

**Comment by marti-devesa** [comment]
Hi @banafsh89 !

farith is part of the FTOOLS (https://heasarc.gsfc.nasa.gov/ftools/), and is not installed with fermipy
