### ISSUE TITLE
Extended sources model map with the fermipy.diffuse subpackage

### ISSUE THREAD

**Issue by casandjian** [fermiPy/fermipy#550]
Dear Fermipy friends, this issue concerns the fermipy.diffuse subpackage.
I am using this package to generate point and extended sources model maps.
For the fermipy and fermitools installation I followed the latest installation procedure provided by the website.
In order to create the catalog srcmaps I run the following functions:

-fermipy-srcmaps-catalog-sg
-fermipy-gather-srcmaps-sg
-fermipy-merge-srcmaps-sg

While the final point-source model map shows a correct representation of the Fermi counts, the extended-source model map largely underestimate (by a factor ~900) the real extended counts.
I tried to follow the fermipy.diffuse code in the python side and did not notice any issue. I was not able to continue to debug in the compiled fermitools but a bug in the fermitools regarding extended sources would have already been noticed. 
I am using the Extended_12years version for the extended-sources fits files.
Is there someone using the fermipy.diffuse subpackage for whom the extended source gives a correct estimation of the Fermi counts ?
Thanks,
Jean-Marc

**Comment by casandjian** [comment]
With Jean Ballet's assistance, we successfully identified the root cause of the issue, which can be traced back to the "fermipy-srcmaps-catalog" function. 
For your reference, we have included an example along with the necessary files to replicate the error, which involves just two extended sources and one point source.
It runs with the command:
fermipy-srcmaps-catalog --irfs P8R3_SOURCE_V3 --expcube ltcube_12years_none_zmax90.fits --bexpmap bexcube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL_V3.fits --cmap ccube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL.fits --srcmdl 4FGL.xml --outfile srcmaps.fits
The output file is the srcmap srcmaps.fits
We compared this file with the output of gtsrcmaps and noticed an agreement for the point source and a difference of close to 3 order of magnitude for the extended ones. 
[Uploading analyse_diffuse_github.tar.gz…]()

**Comment by casandjian** [comment]
[Uploading analyse_diffuse_github.tar.gz…]()

**Comment by casandjian** [comment]
Thanks, Nicola, for checking out the problem's origin. I tried finding the mistake but couldn't track it down.

**Comment by omodei** [comment]
Hi! I run the above command. I noticed that the code was still using "xrange" which is has been deprecated in python3. I committed this fix in the master of fermipy.
I than look into your issue, first I run:
`fermipy-srcmaps-catalog --irfs P8R3_SOURCE_V3 --expcube ltcube_12years_none_zmax90.fits --bexpmap bexcube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL_V3.fits --cmap ccube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL.fits --srcmdl 4FGL.xml --outfile srcmaps.fits`

and I compare the output with the output of gtsrcmaps:

`gtsrcmaps
Exposure hypercube file[ltcube_12years_none_zmax90.fits] 
Counts map file[ccube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL.fits] 
Source model file[4FGL.xml] 
Binned exposure map[bexcube_P8_P305_12years_source_none_zmax90_E0_PSF0123_GAL_V3.fits] 
Source maps output file[srcmaps_0.fits] 
Response functions[P8R3_SOURCE_V3] `

The two resulting source maps (srcmaps.fits and srcmaps_0.fits) are identical. What should I compare to replicate your issue? Can you try with the version in the master to see if you still have the same issue?

**Comment by jballet** [comment]
Thank you Nicola,
No need to do anything more on your side.
I was able to replicate your direct call to gtsrcmaps and result. It shows clearly that the normalization of the extended source entry is 1000 times lower than that I get with a non-HEALPix projection, although that of the point source is the same.
So the problem lies in gtsrcmaps itself, not in fermipy.
I will send an issue on the fermitools.
