### ISSUE TITLE
How to calculate TSvar for long term light curve

### ISSUE THREAD

**Issue by xihou** [fermiPy/fermipy#557]
Dear colleague,

I would like to know how to calculate TSvar for long term light curves. For now, I read in the fits file of light curve and use the columns of "loglike" and "loglike_const" and Eq. (4) in 2FGL to calculate it, i.e., sum the loglike difference in each time bin between the best fit and when fixing the norm of the source of interest to the full data fit value. In this way, I always got bigger TSvar than the one recorded in the npy file of light curve. I'm just confused.

Thanks!

best

**Comment by omodei** [comment]
Eq. (4) in 2FGL is not just the difference of TS. The calculation in fermipy is done here:
 https://fermipy.readthedocs.io/en/latest/_modules/fermipy/lightcurve.html#calcTS_var
 Please, reopen this issue if there is an issue with the code.

**Comment by xihou** [comment]
Thanks for the reply. After checking the code in fermipy and applied to my source, the TSvar decreased from >2sigma to <1sigma.

According to Eq. (4) in 2FGL, we need two columns of loglike vaues, one is obtained by freeing the norm of my source in each time bin, i.e., log Li (Fi), the other is obtained by fixing the norm of my source, i.e., logLi (Fconst). In my previous calculation, I have thought that logLi (Fi) is "loglike" and logLi (Fconst) is "loglike_const" in the fits file of fermipy.

But now I found that fermipy uses "loglike_fixed" rather than "loglike" in the calculation. I would like to know the difference among "loglike", "loglike_fixed" and "loglike_const". 

Thanks!
