### ISSUE TITLE
How can I get time series data from Unbinned likelihood  tutorial?

### ISSUE THREAD

**Issue by bluecandyrain** [fermiPy/fermipy#563]
## Data Analysis Question

I am a student and study processing Fermi LAT data independently. The cicerone said that the Unbinned likelihood analysis is the preferred method for time series analysis of the LAT data. I have followed the standard tutorial on the 'nasa.gov' and got the final 'output_model.xml' file, but I haven't found the time series data in it but the models of sources.
please and thanks!
(●'◡'●)

**Comment by omodei** [comment]
Unbinned likelihood analysis is not implemented in fermipy. Considering using fermitools, gtgrb or ThreeML instead.
