### ISSUE TITLE
fermipy-extra tutorial error in pg1553 (ValueError: None None)

### ISSUE THREAD

**Issue by omooon** [fermiPy/fermipy#564]
I followed the instructions in the fermipy site (https://fermipy.readthedocs.io/en/latest/install.html) to create an environment called fermi as follows;
$ mamba create --name fermi -c conda-forge -c fermi python=3.9 "fermitools>=2.2.0" healpy gammapy
$ mamba activate fermi
$ pip install fermipy
I then cloned "fermipy-extra.git" following the IPython Notebook Tutorials in the Quickstart Guide to make sure it worked in the tutorial. I am currently in the process of running pg1553.ipynb.

The following error occurred when creating a GTAnalysis instance; gta = GTAnalysis('pg1553/config.yaml',logging={'verbosity': 3}) 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[15], line 2
          1 from fermipy.gtanalysis import GTAnalysis
----> 2 gta = GTAnalysis('pg1553/config.yaml',logging={'verbosity': 3})
          3 matplotlib.interactive(True)

File [~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:361](https://file+.vscode-resource.vscode-cdn.net/Users/omooon/GLAST/fermipy-extra/notebooks/~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:361), in GTAnalysis.__init__(self, config, roi, **kwargs)
       358     self._roi = roi
       360 for cfg in configs:
--> 361     comp = self._create_component(cfg, loglevel=self.loglevel)
       362     self._components.append(comp)
       364 self._files = {}

File [~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:960](https://file+.vscode-resource.vscode-cdn.net/Users/omooon/GLAST/fermipy-extra/notebooks/~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:960), in GTAnalysis._create_component(self, cfg, **kwargs)
       957     if k in GTBinnedAnalysis.defaults:
       958         copy_cfg[k] = cfg[k]
--> 960 comp = GTBinnedAnalysis(
       961     copy_cfg, self.roi, logging=self.config['logging'], **kwargs)
       963 return comp

File [~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:4537](https://file+.vscode-resource.vscode-cdn.net/Users/omooon/GLAST/fermipy-extra/notebooks/~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermipy/gtanalysis.py:4537), in GTBinnedAnalysis.__init__(self, config, roi, **kwargs)
     4534 self._tmax = self.config['selection']['tmax']
     4536 if self._tmin is None or self._tmax is None:
-> 4537     raise ValueError("%s %s" % (self._tmin, self._tmax))
     4539 axes = [MapAxis.from_edges(self.energies, interp='log',
     4540                            name='energy', unit='MeV')]
     4542 frame_map = dict(CEL='icrs', cel='icrs', GAL='galactic', gal='galactic')

ValueError: None None

---------------------------------------------------------------------------

The environment in which we are running is as follows;
・fermipy 1.2.0                
・fermitools 2.2.0            
・fermitools-data 0.18
・python 3.9.18
・M2 macOS Ventura 13.0    
Also, since the path of FERMI_DIFFUSE_DIR is not passed after fermipy version 0.19.0, the following settings are made in .zshrc
$ export FERMI_DIFFUSE_DIR=/Users/omooon/miniconda3/envs/fermi/share/fermitools/refdata/fermi/galdiffuse

I did not see tmin and tmax in the selection key in pg1553/config.yaml, so I set tmin=239557417, tmax=256970880 (this is the Start Time (MET) to Stop Time (MET) as stated in the pg1553 analysis tutorial) I tried running it again, but it did not work. Also, tmin and tmax were missing from the config.yaml that I thought I had set up.

I would appreciate any help in resolving this issue. Thank you.

**Comment by omodei** [comment]
This is fixed in the master of fermipy-extra. See #571 . Feel free to reopen this issue if it is not solved.
