### ISSUE TITLE
Value error: None none with pg1553.ipynb notebook

### ISSUE THREAD

**Issue by ishaque-nonplussed-rabbit** [fermiPy/fermipy#571]
**Describe the bug**
I have installed fermipy using all the steps recommended with mamba on the fermipy webpage. I am just starting off using fermipy, and was looking at the notebooks for a better understanding. The following is the error message I obtained for pg1553.ipynb.

**For input line with the following code:**

from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('pg1553/config2.yaml',logging={'verbosity': 3})
matplotlib.interactive(True)

**The output (with error message) is:**

2024-02-27 19:38:14 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 1.2.2 
ScienceTools version 2.2.0

{'Prefactor': 0, 'Index1': 1, 'Scale': 2, 'Cutoff': 3, 'Index2': 4}
{'Prefactor': 0, 'Index1': 1, 'Scale': 2, 'Cutoff': 3, 'Index2': 4}

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 2
      1 from fermipy.gtanalysis import GTAnalysis
----> 2 gta = GTAnalysis('pg1553/config2.yaml',logging={'verbosity': 3})
      3 matplotlib.interactive(True)

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py:361, in GTAnalysis.__init__(self, config, roi, **kwargs)
    358     self._roi = roi
    360 for cfg in configs:
--> 361     comp = self._create_component(cfg, loglevel=self.loglevel)
    362     self._components.append(comp)
    364 self._files = {}

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py:960, in GTAnalysis._create_component(self, cfg, **kwargs)
    957     if k in GTBinnedAnalysis.defaults:
    958         copy_cfg[k] = cfg[k]
--> 960 comp = GTBinnedAnalysis(
    961     copy_cfg, self.roi, logging=self.config['logging'], **kwargs)
    963 return comp

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py:4537, in GTBinnedAnalysis.__init__(self, config, roi, **kwargs)
   4534 self._tmax = self.config['selection']['tmax']
   4536 if self._tmin is None or self._tmax is None:
-> 4537     raise ValueError("%s %s" % (self._tmin, self._tmax))
   4539 axes = [MapAxis.from_edges(self.energies, interp='log',
   4540                            name='energy', unit='MeV')]
   4542 frame_map = dict(CEL='icrs', cel='icrs', GAL='galactic', gal='galactic')

ValueError: None None

**Environment (please complete the following information):**
 - OS: (Ubuntu 20.04.6 LTS)

**Additional context**
N/A

**Comment by omodei** [comment]
Version updated in master and pip
