### ISSUE TITLE
XML parameter error

### ISSUE THREAD

**Issue by HealthyPear** [fermiPy/fermipy#572]
This happenes in easyfermi, see issue: ranieremenezes/easyfermi#49 

I'm unsure if this is exclusively a _fermitools_ issue: it crashes when using fermitools, but it gets triggered by _fermipy_.

To reproduce, use _easyfermi_ to analyze any source (at least with the system described in the downstream issue).

@ranieremenezes

**Comment by omodei** [comment]
It would be more useful if you could provide a test sample that we can run in fermipy. Looking at your reported error it looks like the fit is trying to set parameters outside the allowed range.

**Comment by HealthyPear** [comment]
This is a possible set of settings in _easyfermi_ which was triggering the issue sometome ago (for the moment I cannot reproce it due to a separate issue, but I can confirm asap if you cannot reproduce it directly from _fermipy_ alone)

<img width="1102" alt="image" src="https://github.com/fermiPy/fermipy/assets/17836610/97229d15-23db-4db0-add8-db2de3f4a3b2">

@ranieremenezes might give more details about what _fermipy_ is doing behind the curtains with these settings.

**Comment by omodei** [comment]
I am sorry, but I don't use easyfermi. Please, provide a way to reproduce this in fermipy.
