### ISSUE TITLE
SED high-energy data points are computed even if we only have 1 or 2 photons

### ISSUE THREAD

**Issue by ranieremenezes** [fermiPy/fermipy#574]
**First some context:**

The target in this example is not listed as a source in 4FGL-DRX. But this problem happens for the high-energy SED bins of any target. 

In the ft1_00.fits file generated with GTAnalysis.setup(), there are only 3 photons with energies > 80 GeV positionally coincident with this target. The TS for this target computed with GTAnalysis.fit() is ~27, which looks reasonable to me since higher energy photons have a higher TS due to less background and better spatial reconstruction. The problem happens in the SED data points, as shown in the figure below:

![SED_UGS_LHAASO](https://github.com/fermiPy/fermipy/assets/14879409/271f67ae-801a-466a-b8d3-0c28a9caa2a1)

It is clear from this plot that those 3 photons above 80 GeV are producing the two differential flux data points around 100 GeV, and this seems quite concerning to me. These "data points" are not real but can easily be misunderstood by fermipy users as real, especially due to their relatively high TS values of ~15 and 12. They can, for instance, considerably alter the results of an SED modeling.

**To Reproduce**

The parameters adopted here are:

emin : 1000.0
emax : 1000000.0
zmax    : 105
evclass : 128
evtype  : 3
ra: 184.98
dec:  29.25
tmin: 628789417
tmax: 726594181

**Comment by sarabuson** [comment]
Hi Raniere, this does not sound like a bug of fermipy, rather simply how the likelihood works. Fermipy uses the underling framework of the ST, where eventually the likelihood is estimated.  In the SED computation, Fermipy returns a file with flux estimates, corresponding errors, and UL for each energy bin. In the plot, bins are shown as data-points or arrows depending on the TS value of that bin. The user/scientist can choose the threshold value for plotting a point (detection) or limit to be more or less stringent. 

Regardless, based on the results and SED posted, the SED points have a pretty large error bar (one order of magnitude), consistently with the detection of few (one) events. In a standard SED modeling, I suspect that these points would not get much weight, and hence have overall no substantial impact from the physics perspective.

**Comment by omodei** [comment]
I agree with @sarabuson. This is an effect of how the likelihood works, it's not a bug in fermipy. It's user responsibility to interpret the results with grain of salt of the statistics is low or of the results are driven by only few events.

**Comment by ranieremenezes** [comment]
Hi @omodei ,

Thank you for the feedback.

Even if it is not a bug of fermipy, it is a problem that we can probably discuss better in the future. My point is that we can achieve very high TSs with only a couple of VHE photons and the users of fermipy are typically guided by TS values. For instance, in the SED below, done using 2 months of data centered on Mrk 421, the highest energy bins have TSs ~ 60, even if they have only a couple of photons. This is very misleading to the user (even to the experienced one), which can take such high TS points as if they were good representations of the real differential flux. Furthermore, statistical error bars are provided for these points even if we don't have a statistically significant sample (i.e. a large number of counts).

In the easyfermi version released a few days ago, we go around this problem with a warning system. If the number of counts is below 5 photons within 0.5° for a given SED energy bin, we flag the data point in the sed.fits file and print it in magenta in the  SED quickplot (as shown in the figure below). There are more details in the easyfermi documentation: https://easyfermi.readthedocs.io/en/latest/SED.html.

 Anyway, I hope we can discuss this in one of the future fermipy meetings.

![SED_Mrk421_GitHub](https://github.com/fermiPy/fermipy/assets/14879409/594c9037-a053-44f3-b311-30f71347b99f)
