### ISSUE TITLE
goodness of fit

### ISSUE THREAD

**Issue by NithyaSathyan** [fermiPy/fermipy#576]
## Data Analysis Question

What is that one thing which gives a measure of the goodnes of fit for FERMI LAT analysis using fermipy? Is it the TS value ? If so where can I find it ? In the fits file generated after the analysis, there is a column of TS and loglikelihood values specified for each data point. But how can I find the TS value for the overall fit ?

**Comment by NithyaSathyan** [comment]
I am asking about the sed fitting.

**Comment by omodei** [comment]
There is no overall value for the TS of the fit. Also, the TS is not a measure of the goodness of the fit. It is a statistical measurement of the significance of the source with respect the null hypothesis (background only). So, in the SED, the TS values are the significance of the source in each energy bin. If you want the TS of the source after the gta.fit() you can use gta.roi['draco']['ts'] where 'draco', for example is the name of your source.

**Comment by NithyaSathyan** [comment]
Hii..
I am trying to install fermipy using the following

 conda create --name fermipy -c conda-forge -c fermi python=3.9
"fermitools>=2.2.0" healpy gammapy conda activate fermipy pip install
fermipy

but i get the following error

conda create --name fermipy -c conda-forge -c fermi python=3.9
"fermitools>=2.2.0" healpy gammapy
2 channel Terms of Service accepted
Channels:
 - conda-forge
 - fermi
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - unsupported request
  - unsupported request
  - nothing provides cppunit needed by fermitools-2.2.0-py39h93a0a19_0

Could not solve for environment specs
The following packages are incompatible
├─ fermitools >=2.2.0 * is not installable because it requires
│  └─ cppunit =* *, which does not exist (perhaps a missing channel);
├─ gammapy =* * does not exist (perhaps a typo or a missing channel);
└─ healpy =* * does not exist (perhaps a typo or a missing channel).


Please help me with this.
