### ISSUE TITLE
Localization doc

### ISSUE THREAD

**Issue by jballet** [fermiPy/fermipy#585]
The [description ](https://fermipy.readthedocs.io/en/latest/advanced/localization.html) of the source localization functionality has a typo.
In the first green frame below the two maps, it should be written
o = gta.localize('3FGL J1722.7+6104', update=True)
instead of
o = gta.extension('3FGL J1722.7+6104', update=True)

**Comment by omodei** [comment]
Thanks for reporting this! I have fixed the documentation in the master.

**Comment by omodei** [comment]
I confirm that the dic has been updated accordingly.
