### ISSUE TITLE
Regarding GRB analysis with Fermi-LAT data

### ISSUE THREAD

**Issue by ajaykhoj** [fermiPy/fermipy#588]
Hey, I want to analyze the Fermi-LAT data of GRB with Fermipy and couldn't find proper documentation for it. If I have missed anything let me know. Is there any documentation dedicated to GRBs with Fermi-LAT or notebook? Please share with me. Any small help would be greatly appreciated.

Thanks

**Comment by omodei** [comment]
We don't usually suggest to use fermipy to analyze GRBs, unless you want to study long exposures. We suggest to use gtburst  (available with the science tools https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/gtburst.html) or its ThreeML plug-in (https://threeml.readthedocs.io/en/stable/notebooks/LAT_Transient_Builder_Example.html).
