### ISSUE TITLE
Fermipy v1.2.3 not available

### ISSUE THREAD

**Issue by jywoo0116** [fermiPy/fermipy#602]
Dear Fermipy developers,

I am hoping to use the PS map included in v1.2.3 (https://fermipy.readthedocs.io/en/latest/changelog.html)  but it doesn't seem to be available anywhere. I tried to upgrade Fermipy using pip in the mamba environment, but it was upgraded to v1.2.2. It's not available on Github either. Could you let me know how I can install v1.2.3?

Thank you and best regards,
Jooyun

**Comment by omodei** [comment]
Hi Jooyun, we will release 1.2.3 by the end of the week, but you can get the version with psmap implemented in the master using: `pip install git+https://github.com/fermipy/fermipy.git@master`

**Comment by omodei** [comment]
A new version of fermion is available  on pip (v1.3.1)
