### ISSUE TITLE
Exception: No source matching name: B2 1144+40

### ISSUE THREAD

**Issue by nyctophile-aayu** [fermiPy/fermipy#605]
On running config file using this step:
gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})

I am receiving this error:

2024-08-16 15:21:48 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 1.2.2 
ScienceTools version 2.2.0
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py:353, in GTAnalysis.__init__(self, config, roi, **kwargs)
    351 # Setup the ROI definition
    352 if roi is None:
--> 353     self._roi = ROIModel.create(configs[0]['selection'],
    354                                 configs[0]['model'],
    355                                 fileio=configs[0]['fileio'],
    356                                 coordsys=configs[0]['binning']['coordsys'])
    357 else:
    358     self._roi = roi

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/roi_model.py:1766, in ROIModel.create(cls, selection, config, **kwargs)
   1763 """Create an ROIModel instance."""
   1765 if selection['target'] is not None:
-> 1766     return cls.create_from_source(selection['target'],
   1767                                   config, **kwargs)
   1768 else:
   1769     target_skydir = wcs_utils.get_target_skydir(selection)

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/roi_model.py:1798, in ROIModel.create_from_source(cls, name, config, **kwargs)
   1794 coordsys = kwargs.pop('coordsys', 'CEL')
   1796 roi = cls(config, src_radius=None, src_roiwidth=None,
   1797           srcname=name, **kwargs)
-> 1798 src = roi.get_source_by_name(name)
   1800 return cls.create_from_position(src.skydir, config,
   1801                                 coordsys=coordsys, **kwargs)

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/roi_model.py:1835, in ROIModel.get_source_by_name(self, name)
   1817 def get_source_by_name(self, name):
   1818     """Return a single source in the ROI with the given name.  The
   1819     input name string can match any of the strings in the names
   1820     property of the source object.  Case and whitespace are
   (...)
   1833 
   1834     """
-> 1835     srcs = self.get_sources_by_name(name)
   1837     if len(srcs) == 1:
   1838         return srcs[0]

File ~/miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/roi_model.py:1865, in ROIModel.get_sources_by_name(self, name)
   1863     return list(self._src_dict[index_name])
   1864 else:
-> 1865     raise Exception('No source matching name: ' + name)

Exception: No source matching name: B2 1144+40

***************************************************************************

I have observed that this error is not occurring for all the sources but a few only. There are 2 other sources as well, which are showing data in LAT data server and their observations in LAT Monitored sources as well. But this step does not goes through. 

Any insights or solutions would be greatly appreciated.

**Comment by omodei** [comment]
Can you post the config.yaml file?

**Comment by nyctophile-aayu** [comment]
@omodei My apologies for the very late reply. However, that issue was resolved by changing the source's name from 'B2 1144+40' to 'S4 1144+40'. 

Nevertheless, I am sharing config files for a few other sources that are not recognized while doing the Fermipy analysis, but their lightcurve is monitored on the Fermi webpage.
`1633+382`, `0208-512`, `PMN J0948+0022`. Their name does not recognize the first two, and the last one is not recognized by its 4FGL name. Please look into it and let me know what changes are required for these.

[config.zip](https://github.com/user-attachments/files/17359774/config.zip)
