### ISSUE TITLE
ft1_00 empty. TS map blank.

### ISSUE THREAD

**Issue by SallySaturno** [fermiPy/fermipy#609]
**Describe the error**
I downloaded a set of data in the fermi LAT DATA. The data is ok but when I run the setup, the output (ft1_00.fits) is empty and when I try to plot a TS map, it generates an empty map.

*NOTE:* This is for errors in fermipy and not for questions about data analysis or issues with fermitools.

**To Reproduce**
This is my config 
logging :

  verbosity : 3

data:

  # Define input data files (FT1, FT2, LTCube)

  # FT1 file
  evfile : /home/shayna/Downloads/vela_september/route.lst

  # Spacecraft file
  scfile : /home/shayna/Downloads/vela_september/vela_data/SC00.fits

  #quitar en un analisis que comience de cero

binning:

  # Binning
  roiwidth   : 20.0
  npix       : null
  binsz      : 0.05 # spatial bin size in deg
  binsperdec : 10   # nb energy bins per decade
  coordsys   : 'CEL'

selection:

  # Data selections
  emin    : 1000
  emax    : 1000000
  zmax    : 105
  evclass : 128
  evtype  : 3
  tmin    : 239557417
  tmax    : 241093418
  filter  : 'DATA_QUAL>0 && LAT_CONFIG==1'
  ra : 346.0
  dec : 54.6

gtlike:
  # IRFs
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff']

# Settings for ROI model
model:

  # Include catalog sources within this distance from the ROI center
  src_radius  : 7.0

  # Include catalog sources within a box of width roisrc.
  src_roiwidth : null

  galdiff : '/home/shayna/miniconda3/pkgs/fermitools-data-0.18-0/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits'
  isodiff  : '/home/shayna/miniconda3/pkgs/fermitools-data-0.18-0/share/fermitools/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt'
  extdir : '/home/shayna/Downloads/vela_august/LAT_extended_sources_14years/Extended_14years'

  # List of catalogs to be used in the model.
  catalogs :
    - '/home/shayna/Downloads/vela_august/LAT_extended_sources_14years/gll_psc_v35.fit'
    
components: null

fileio:
  outdir : '/home/shayna/Downloads/vela_september/vela_output'

And this is the step by step 

from fermipy.gtanalysis import GTAnalysis

gta = GTAnalysis('/home/shayna/Downloads/vela_september/config10GeV.yaml',logging={'verbosity' : 3})

gta.setup() # Mandar log

gta.optimize()

gta.free_sources(distance=10.0,pars='norm') # deja libres para el ajuste las normalizaciones de fuentes a menos de 10 grados

gta.free_sources(distance=5,pars='norm') # deja libres todos los parametros para fuentes a menos de 5 grados

#pero solo la normalizacion de 'galdiff' debe liberarse:

gta.free_sources(distance=1.0,pars='norm')

gta.free_source('galdiff', free=False)

gta.fit()

# Se pueden ver algunos resultados con:

gta.print_roi()

# Luego del ajuste se puede hacer un mapa de TS de los residuos (TS esta relacionado con la probabilidad de que se detecte una fuente):

model = {'SpatialModel' : 'PointSource', 'Index' : 2.0,'SpectrumType' : 'PowerLaw'}

m1 = gta.tsmap('tsmap1', model=model, make_plots=True)

gta.plotter.make_tsmap_plots(m1, roi=gta.roi, zoom=2)

**Expected behavior**
No-empty ft1_00 and normal ts map

**Log files**
Add log files or copy & paste the entire output on the terminal or jupyer notebook cell.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - fermipy 1.3.1 fermitools 2.2.0 fermitools-data 0.18
[fermipy.log](https://github.com/user-attachments/files/17051665/fermipy.log)

**Comment by omodei** [comment]
I am sorry, I run your setup both the config file and the notebook, and I did not get any problem (the TS map looks ok to me). Can you try to run everything from scratch (removing all the output?)

**Comment by SallySaturno** [comment]
Hi, it was something with the coordinates! I was putting them wrong. Now it works. Thank you very much!

I'm having other issues but I guess it's better if I oper another issue. Thanks again <3
