### ISSUE TITLE
Use wcsaxes instead of pywcsgrid2

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#7]
I see you're telling users to install `pywcsgrid2` and `ez_setup`:
http://fermipy.readthedocs.org/en/latest/install.html

`pywcsgrid2` is unmaintained ... the new and maintained astropy-affiliated package is
[wcsaxes](https://github.com/astrofrog/wcsaxes).
For high-level stuff there's also [aplpy](https://github.com/aplpy/aplpy), but my suggestion would be to try and just make all the plots you like with only `wcsaxes`.

@woodmd If you agree it's a good idea, maybe we can try and make that update this week?
@adonath is also very good with the plotting libs.

**Comment by woodmd** [comment]
Ok i'll have a look at it this week.  If the api is similar to `pywcsgrid2` then making this transition shouldn't be too difficult.

**Comment by woodmd** [comment]
Ok switching to `wcsaxes` turned out to be quite easy and is now implemented in the latest commit.  I'll also update the installation instructions to reflect that `ez_setup` is no longer needed.

**Comment by cdeil** [comment]
:confetti_ball:
