### ISSUE TITLE
Error during "gta.write_roi" - OSError: Text file busy: 'fit_model.fits'

### ISSUE THREAD

**Issue by orestispavlou** [fermiPy/fermipy#72]
Hello everyone,

I am using the fermipy tools to run the analysis on some Cas A data using Pass8. After completing the _gta.fit()_ command successfully, I get an OSError on the next step which says that the text file is busy: 'fit_model.fits'. I attach a PDF file of my ipython notebook to this for further explanation at the end of this text.

I noticed that:
-The fit seems to return successfully, after gta.fit():
`#Execute a fit. This will maximize the likelihood with respect to the model parameters that are free:`
`gta.fit()`
`2016-07-16 18:37:55 INFO    GTAnalysis.fit(): Starting fit.`
`2016-07-16 19:11:26 INFO    GTAnalysis.fit(): Fit returned successfully. Quality:   3 Status:   0`
`2016-07-16 19:11:26 INFO    GTAnalysis.fit(): LogLike:   998923.162 DeltaLogLike:       95.611`

-"fit_success: 'True'" is stated further down as well:

`u'fit_quality': 3,`
`u'fit_status': 0,`
`u'fit_success': True,`

-Executing '_gta.write_roi_' gives the **OSError: [Errno 26] Text file busy: '...[path to folder]/fit_model.fits'**

`#After the fitting is complete we can write the current state of the model:`
`gta.write_roi('fit_model')`
`2016-07-16 19:17:38 INFO    GTBinnedAnalysis.write_xml(): Writing` `/media/sf_Shared/fermipy/fit_model_00.xml...`
`2016-07-16 19:17:38 INFO    GTAnalysis.write_roi(): Writing /media/sf_Shared/fermipy/fit_model.fits...`
`---------------------------------------------------------------------------`
`OSError                                   Traceback (most recent call last)`
`<ipython-input-19-e35b30fdd3d3> in <module>()`
`1 #After the fitting is complete we can write the current state of the model:`
`----> 2 gta.write_roi('fit_model')`
`/usr/local/lib/python2.7/dist-packages/fermipy/gtanalysis.pyc in write_roi(self, outfile,` `save_model_map, fmt, **kwargs)`
`3505         self.write_xml(xmlfile)`
`3506         self.logger.info('Writing %s...', fitsfile)`
`-> 3507         self.roi.write_fits(fitsfile)`
`3508`
`3509         for c in self.components:`
`/usr/local/lib/python2.7/dist-packages/fermipy/roi_model.pyc in write_fits(self, fitsfile)`
`1973         for h in hdulist:`
`1974             h.header['CREATOR'] = 'fermipy ' + fermipy.__version__`
`-> 1975         hdulist.writeto(fitsfile, clobber=True)`
`1976`
`1977 if __name__ == '__main__':`
`/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.pyc in writeto(self, fileobj,` `output_verify, clobber, checksum)`
`683         # file object that's open to write only, or in append/update modes`
`684         # but only if the file doesn't exist.`
`--> 685         fileobj = _File(fileobj, mode='ostream', clobber=clobber)`
`686         hdulist = self.fromfile(fileobj)`
`687`
`/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.pyc in __init__(self, fileobj, mode, memmap,` `clobber, cache)`
`139             self._open_fileobj(fileobj, mode, clobber)`
`140         elif isinstance(fileobj, string_types):`
`--> 141             self._open_filename(fileobj, mode, clobber)`
`142         else:`
`143             self._open_filelike(fileobj, mode, clobber)`
`/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.pyc in _open_filename(self, filename, mode,` `clobber)`
`465`
`466         if mode == 'ostream':`
`--> 467             self._overwrite_existing(clobber, None, True)`
`468`
`469         if os.path.exists(self.name):`
`/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.pyc in _overwrite_existing(self, clobber,` `fileobj, closed)`
`382                     if not closed:`
`383                         fileobj.close()`
`--> 384                     os.remove(self.name)`
`385             else:`
`386                 raise IOError("File %r already exists." % self.name)`
`OSError: [Errno 26] Text file busy: '/media/sf_Shared/fermipy/fit_model.fits'`

After checking that my Python paths are not causing conflicts, tried renaming/removing the specific file in question from the folder, I am stuck.
Please excuse the long code, but I wanted to make sure I include the entire error to be specific. Any help would be appreciated.

Thank you,
Orestis Pavlou
[CasA_fermipy_Analysis_error.pdf](https://github.com/fermiPy/fermipy/files/415734/CasA_fermipy_Analysis_error.pdf)

**Comment by woodmd** [comment]
It looks like the error occurs when you try to write to the `/media` filesystem so I don't think it's anything specific to fermipy.  Are you sure that you have write permission to the directory you're saving the file to?  You might try manually writing a FITS file with astropy to see if you can isolate the error.  You might also try running in a different disk partition.

**Comment by orestispavlou** [comment]
As I have performed similar analysis using the Fermi Science Tools in this filesystem and there is no problem with the particular path or writing FITS files to it. 
Nevertheless, thank you for the suggestions, I will try them both and get back to you as soon as I do.

**Comment by orestispavlou** [comment]
Update:
I have tried executing in a different disk partition and get the same errors.
I have also tried your suggestion of creating a new FITS file with astropy and the new file is created successfully without any issues (using this guide: [http://docs.astropy.org/en/stable/io/fits/#creating-a-new-fits-file](url) ).

**Comment by woodmd** [comment]
I think to make further progress diagnosing this issue I'll need to know a bit more about your system.  What OS are you using?  Did you install fermipy with the pip or anaconda instructions?

Did you try running the same script outside of jupyter notebook?

**Comment by orestispavlou** [comment]
Things might be a bit more complicated, as I am using a Virtual Machine (Oracle VirtualBox), on a Windows host OS and executing everything on a Linux (Ubuntu) VM. Everything is executed within a shared folder between the two OSs. 
Fermipy was installed using the pip instructions and I have yet to try running the same script with something other than jupyter notebook.

**Comment by woodmd** [comment]
I think there may be an issue with your python installation.  Based on the traceback it looks like you're running with a python installation in `/usr/local/`but if you followed the pip installation instructions you should be running the python installation which comes with the Fermi STs.  If the executable path returned by `which python` or `which ipython` doesn't point to the ST installation then there is likely a problem with your `PATH` variable.  Did you try following the anaconda installation instructions?

**Comment by woodmd** [comment]
Did you ever manage to resolve this issue?
