### ISSUE TITLE
Error in input data with CastroData.create_from_sedfile

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#74]
Hi everyone,

I'm getting the following error using the function CastroData.create_from_sedfile when I read the sed of some sources. This is the error that I'm getting:
## In [23]: castro_sed = CastroData.create_from_sedfile('3fgl_j1827.3-1446_sed.fits')

ValueError                                Traceback (most recent call last)
<ipython-input-23-1d59fa283c9f> in <module>()
----> 1 castro_sed = CastroData.create_from_sedfile('3fgl_j1827.3-1446_sed.fits')

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in create_from_sedfile(fitsfile, norm_type)
   1114         rs = ReferenceSpec.create_from_table(tab_s)
   1115 
-> 1116         return CastroData(norm_vals, nll_vals, rs, norm_type)
   1117 
   1118     @staticmethod

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in **init**(self, norm_vals, nll_vals, refSpec, norm_type)
    925 
    926         """
--> 927         super(CastroData, self).**init**(norm_vals, nll_vals, norm_type)
    928         self._refSpec = refSpec
    929 

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in **init**(self, norm_vals, nll_vals, norm_type)
    603         for i, (normv, nllv) in enumerate(zip(self._norm_vals,
    604                                               self._nll_vals)):
--> 605             nllfunc = self._buildLnLFn(normv, nllv)
    606             self._nll_null += self._nll_vals[i][0]
    607             self._loglikes.append(nllfunc)

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in _buildLnLFn(self, normv, nllv)
   1145         """
   1146         """
-> 1147         return LnLFn(normv, nllv, self._norm_type)
   1148 
   1149     def spectrum_loglike(self, specType, params, scale=1E3):

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in **init**(self, x, y, norm_type)
    151 
    152         """
--> 153         self._interp = Interpolator(x, y)
    154         self._mle = None
    155         self._norm_type = norm_type

/u/gl/mdimauro/.local/lib/python2.7/site-packages/fermipy-0.10.3+16.g868e-py2.7.egg/fermipy/castro.pyc in **init**(self, x, y)
     63 
     64         self._fn = UnivariateSpline(x, y, s=0, k=1)
---> 65         self._sp = splrep(x, y, k=1, s=0)
     66 
     67     @property

/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.10/lib/python2.7/site-packages/scipy/interpolate/fitpack.pyc in splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
    513         else:
    514             try:
--> 515                 raise _iermess[ier][1](_iermess[ier][0])
    516             except KeyError:
    517                 raise _iermess['unknown'][1](_iermess['unknown'][0])

ValueError:     Error on input data

For who of you have access to SLAC machines, an example of the error could be found in the following folder /nfs/slac/kipac/fs1/u/dmcat/workdir/mattia/GCPass8_tsmap_300MeV_ref/roi_4 reading the file 3fgl_j1827.3-1446_sed.fits with the following command:
castro_sed = CastroData.create_from_sedfile('3fgl_j1827.3-1446_sed.fits')

Thanks for the help.

Mattia

**Comment by woodmd** [comment]
I suspect the SED data is malformed for some reason.  This might happen if the fitter failed to converge in one of the energy bins.  I'll have a closer look at your file to see if I can track it down further.

**Comment by woodmd** [comment]
I had a look at the file and the normalization vector for one of the SED energy bins was out of order.  I've seen this issue before and it may be either a problem with fit convergence or something to do with the logic for defining the scan grid.  I don't have time to dig into this further right now so as a workaround in 68f5741587c708188056d7fbe6c8887108ae4fc1 I've added code in the constructor to `CastroData_Base` that automatically sorts the arrays for the likelihood scan.  This should resolve the error you were seeing when calling `CastroData.create_from_sedfile`.
