### ISSUE TITLE
newname parameter in localize() causes error

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#76]
I ran `localize()` with the `newname=` parameter defined, and it caused an error that the source with that name was not found. Obviously this is true, since it is being newly created.
I ran again without `newname=` defined and no error occured.
Using the latest fermipy from GitHub.

**Comment by woodmd** [comment]
This should now be fixed with 707c81882d20075a1b72d58feeb4f0f007d3f757.
