### ISSUE TITLE
Make fermipy package on PyPI

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#8]
I see `fermipy` is not available on PyPI:
https://pypi.python.org/pypi?%3Aaction=search&term=fermipy&submit=search

How about making a package and uploading it on PyPI?
Or at least registering the name, so that no-one else creates a `fermipy` package?

**Comment by cdeil** [comment]
If you declare the dependencies for `fermipy` in `setup.py`, then `pip install fermipy` should just work on many systems, i.e. the long list of things to install could just go in a "if `pip install fermipy` doesn't work" section: http://fermipy.readthedocs.org/en/latest/install.html

**Comment by kialio** [comment]
The main issue here is that many of the python packages installed in the Science Tools are broken when using the binary distribution.  This is mainly because libraries and paths are different on the users system than on the build system at Goddard.  The only way I could figure out how to make sure the dependencies are installed is to do manual upgrades of them (like in the instructions).  Is there a way to force this to happen in the setup.py script?  Maybe another way to do it would be to provide a script that fixes all of the known problems that a user could run.  This might not be part of fermipy.

**Comment by cdeil** [comment]
@kialio – I think you have to tell users to call `-U`.

Having the `fermipy` package on PyPI is still useful IMO, just to reserve the name and to make `pip install fermipy` work for people that don't want to much with git.

The binary distribution issues will always be there. I guess building and maintaining Science Tools conda packages is not an option.
Maybe bundling those Python packages and `fermipy` in the official distribution is an option?
That would be so nice, and also be a good way to focus the scattered efforts to build nice analysis scripts for Fermi on one package: fermipy!

**Comment by kialio** [comment]
I agree.  

I think we should start another thread about including fermipy in the STs.  @woodmd and I chatted about this early on and it would be good to gather other's opinions.

**Comment by woodmd** [comment]
I went ahead and registered and uploaded fermipy to pypi.  This is my first time creating a package on pypi so there's some aspects that I don't fully understand.  For instance when I run `python setup.py sdist` it doesn't actually appear to be packaging any of the package data files.  Is there some option I need to use to get this behavior?

**Comment by cdeil** [comment]
You need to declare in `setup.py` which data files should be installed:
You might also have to manually list them in `MANIFEST.in`.

Does this help?
https://github.com/pypa/sampleproject/blob/master/setup.py
https://packaging.python.org/en/latest/distributing/

**Comment by cdeil** [comment]
I covered this a bit in the tutorial on Monday ... you have to do something like this to find the bundled files in the right location, no matter if people use the version from the git repo or install and use the one from site-packages:
https://github.com/gammapy/fhee/blob/master/v04/fhee/utils.py#L6

**Comment by cdeil** [comment]
Thanks for putting it up: https://pypi.python.org/pypi/fermipy

It would be nice if `python setup.py egg_info` worked with any Python, so that package managers like pip can extract the metadata for this package.

Currently I get this error, which I think is because you list fermi.config as a package here:
https://github.com/fermiPy/fermipy/blob/master/setup.py#L29
But it's a module, not a package: `fermipy/config.py`
And there's a folder called `fermipy/config`, but that doesn't contain an `__init__.py`, so it's not a package either.
Maybe rename that folder and remove fermi.config from the packages list in setup.py?

```
$ pip-2.7 install fermipy
Collecting fermipy
  Using cached fermipy-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/fermipy.egg-info
    writing requirements to pip-egg-info/fermipy.egg-info/requires.txt
    writing pip-egg-info/fermipy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/fermipy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/fermipy.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/fermipy.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'fermipy/config' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-GJ3ou1/fermipy
```

**Comment by woodmd** [comment]
I made some changes to `setup.py` and added a `MANIFEST.in`.  The new source distribution is now uploaded to pypi so let me know if that fixes the issue you were having with `pip install`.

**Comment by cdeil** [comment]
Thanks!
