### ISSUE TITLE
matplotlib _macosx error when importing fermipy.gtanalysis

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#9]
I followed the install instructions and (I think) all the `pip install` steps worked.
Now I get this:

```
$ python
Python 2.7.8 (default, Aug 20 2015, 11:36:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fermipy.gtanalysis import GTAnalysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/fermipy-0.5.0_41_gfa4e-py2.7.egg/fermipy/gtanalysis.py", line 28, in <module>
    import matplotlib.pyplot as plt
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

Apart from the actual issue .... can you move all matplotlib imports into modules or functions or methods so that matplotlib becomes optional and is only imported when trying to create a plot?
(that's the pattern e.g. astropy uses)

**Comment by cdeil** [comment]
Yes, I did upgrade matplotlib.

Choosing e.g. the `agg` backend instead of using the default `osx` one works:
```
>>> import matplotlib
>>> matplotlib.use('agg')
>>> import matplotlib.pyplot
>>> matplotlib.__version__
'1.5.0'
```
I can hack the `fermipy` files for now and make this work, but you might want to explain this gotcha to users or make it somehow convenient for them to set the backend before running `fermipy` to make plots. Maybe via documentation, or a config file or even by handling the error and selecting a backend for the user in a clever way?

**Comment by woodmd** [comment]
Jeremy added a note in the installation instructions about this.  I'll also look into whether it would also make sense to add an option to the config file that could be used to set the matplotlib backend.

**Comment by woodmd** [comment]
I'm closing this issue now since I haven't received any other complaints about this error for the last year.  All of the plotting calls should now be isolated in `fermipy.plotting` and only get invoked when passing `make_plots=True`.  There is also a convenience method `fermipy.utils.init_matplotlib_backend` which can be used to automatically set matplotlib to the `agg` backend if DISPLAY is not set.
