### ISSUE TITLE
Sensitivity tool

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#96]
Hi Matthew,

I am trying to calculate detection threshold of LAT. I tried running the tool 
(i) in terminal
$ fermipy-flux-sensitivity --ltcube=LTCube_zmax_90.fits --galdiff=/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits --event_class=P8R2_SOURCE_V6 --glon=1.729 --glat=22.991

-bash: fermipy-flux-sensitivity: command not found

(ii) using the script
$ python ~/fermipy/fermipy/scripts/flux_sensitivity.py --ltcube=LTCube_zmax_90.fits --galdiff=/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits --event_class=P8R2_SOURCE_V6 --glon=1.729 --glat=22.991

Traceback (most recent call last):
  File "/u/gl/vaidehi/fermipy/fermipy/scripts/flux_sensitivity.py", line 310, in <module>
    main()
  File "/u/gl/vaidehi/fermipy/fermipy/scripts/flux_sensitivity.py", line 299, in main
    hdulist.append(fits.table_to_hdu(tab_diff))
AttributeError: 'module' object has no attribute 'table_to_hdu'

I am using all sky live time cube file & ST v 11-03-00 in SLAC. Please help me in this regard.

**Comment by woodmd** [comment]
What are you doing to setup your SLAC environment?  Are you using the latest version of the slacsetup script? 

You need to have the astropy v 1.2.1 or later to run the sensitivity script.  The latest version of `slacsetup.sh` should initialize your environment to use anaconda 4.2.0 installation in GLAST_EXT (which will have the required version of astropy).  Regarding the other error it looks like the python bin directory is not in your path.  If you use `slacsetup` this directory should get appended automatically to your path.  Is the PYTHON_USER_BIN variable defined after you run slacsetup?

**Comment by vaidehiratna** [comment]
I just downloaded latest version of slacsetup.sh and  did a fresh installation of fermiPy. The output of 'which python' is as follows
/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/bin/python

Then, I ran the command again
fermipy-flux-sensitivity --ltcube=LTCube_zmax_90.fits --galdiff=/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits --event_class=P8R2_SOURCE_V6 --glon=141.1584147 --glat=-61.7599872

But the error appeared again
Traceback (most recent call last):
  File "/u/gl/vaidehi/.local/bin/fermipy-flux-sensitivity", line 9, in <module>
    load_entry_point('fermipy==0.11.0+106.gc2c5', 'console_scripts', 'fermipy-flux-sensitivity')()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.11.0+106.gc2c5-py2.7.egg/fermipy/scripts/flux_sensitivity.py", line 299, in main
    hdulist.append(fits.table_to_hdu(tab_diff))
AttributeError: 'module' object has no attribute 'table_to_hdu'

I am using all sky LT cube file. Could the error be due to this fact that instead of using a pointed LT cube (for a given glon & glat), I am using all sky file?

**Comment by woodmd** [comment]
No this is still a problem with your python installation.  You have an older version of `astropy` that is being imported instead of the one in the GLAST_EXT installation.  You can verify the path to your astropy installation by running:
```
python -c "import astropy;print astropy.__file__"
```
I suspect that you may have a conflicting installation of astropy in your `.local` directory.  I would try deleting `/u/gl/vaidehi/.local/lib/python2.7/` and reinstalling fermipy again.

**Comment by vaidehiratna** [comment]
I followed your suggestions and it is working flawlessly. Thanks.
